### ISSUE TITLE
Create composer.josn for basic install in localgov repo

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#1]

**Comment by stephen-cox** [comment]
To get everything into Packagist I needed to create basic composer.json files. These will need reviewing and stuff like Drush, Console and other dev dependencies added:

- https://github.com/localgovdrupal/localgov/blob/master/composer.json
- https://github.com/localgovdrupal/localgov_core/blob/master/composer.json
- https://github.com/localgovdrupal/localgov_project/blob/master/composer.json

**Comment by stephen-cox** [comment]
I've created separate issues for further rationalisation of these. Closing.
