### ISSUE TITLE
Check issues on all of the repos and tidy

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#101]

**Comment by finnlewis** [comment]
Hi @willguv 

As it happens, that is what I'm doing, and came across this one! 

Was this for you or for me or for a general reminder?

**Comment by willguv** [comment]
Hi @finnlewis, it's a general reminder

If you're doing the work this can be removed

Thanks for taking the time

**Comment by andybroomfield** [comment]
A plus one here! If people have time can they clear up and close any issues?

**Comment by finnlewis** [comment]
Thanks @andybroomfield  - good shout!
