### ISSUE TITLE
Functional Javascript tests for the Localgov theme

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov#102]
Some parts of public facing pages have heavy dependency on Javascript.  Examples include mobile menu, site search, Service status pages, Step by step pages, etc.  When the localgov_theme is responsible for significant parts of any of these functionalities, it would be good to have some Functional Javascript tests to go along.

Relevant links:
- Drupal [documentation for Functional Javascript tests](https://www.drupal.org/docs/testing/phpunit-in-drupal/phpunit-javascript-test-writing-tutorial).
- Some of our modules already have such tests:
  - [Step by step](https://github.com/localgovdrupal/localgov_step_by_step/blob/master/tests/src/FunctionalJavascript/StepByStepSummariesTest.php).
  - [Alert banner](https://github.com/localgovdrupal/localgov_alert_banner/blob/master/tests/src/FunctionalJavascript/AlertBannerHideTest.php)
  - [Service landing page field widget]https://github.com/localgovdrupal/localgov_services/blob/master/modules/localgov_services_navigation/tests/src/FunctionalJavascript/LandingPageChildrenTest.php.  This one is not a public facing page of course, but serves as an example.

Drupal also supports [Nightwatch-based Javascript tests](https://www.drupal.org/docs/testing/javascript-testing-using-nightwatch).  These are also fine.

**Comment by paulpopus** [comment]
We can also write these using Mocha.js if people are comfortable with it. I've started working with it for automated tests involving PRs in the theme, but Mocha can be used for other tests as well.

**Comment by Adnan-cds** [comment]
Hi Paul,
We are writing all tests for **Backend** code using Drupal's testing framework which eventually gets run by PHPUnit.  I understand it would be too much to ask **Frontend** test code be written in PHP as well.  Even the Drupal core project uses [Nightwatch](https://www.drupal.org/docs/testing/javascript-testing-using-nightwatch) for some functional Javascript tests AFAIK.  Apparently you can write unit tests in Nightwatch too although I never tried either.  I prefer to stick to what Drupal core uses, but if you are more comfortable with Mocha.js then feel free to write tests for the Frontend in it.  For the Backend, let's not go too far from PHPUnit for now.

In any case, if you want these Mocha.js tests to run regularly like all the other PHPUnit tests then you will have to convince Stephen Cox to include it in the [test runner](https://github.com/localgovdrupal/drupal-container/blob/master/run-tests.sh) :)

FAO @paulpopus @stephen-cox @finnlewis

**Comment by Adnan-cds** [comment]
> In any case, if you want these Mocha.js tests to run regularly like all the other PHPUnit tests then you will have to convince Stephen Cox to include it in the test runner :)

Sorry, this won't be needed given that you are waking up Mocha from the Github test workflow for the theme as part of [another draft pull request](https://github.com/localgovdrupal/localgov_theme/pull/107/files#diff-d0e00ac661fca5721aa9982aca4904d015152b60bc70b6236cea5d349350752e).

**Comment by andybroomfield** [comment]
I'll close as localgov_theme is now being deprecated.
