### ISSUE TITLE
Add Bracknell campaign paragraphs

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#105]

**Comment by willguv** [comment]
- [x] Finalise the list of Bracknell paragraphs coming over @willguv @robhmicroserve and prioritise order of delivery
- [x] Gosia to speak with @stephen-cox before 12th to understand any technical detail
- [x] Create a card with acceptance criteria for each paragraph type
- [x] Agree with @stephen-cox @Adnan-cds the tests that can be delivered in the time available

**Comment by willguv** [comment]
@robhmicroserve @Adnan-cds @cjstevens78 agreed that basic layout element styling should go in the module if possible (enough styling to be functional)

Any LocalGov Drupal styling will be carried out by the project

**Comment by finnlewis** [comment]
Closing this one off for now, there are many other specific issues to cover all paragraphs,
