### ISSUE TITLE
Flesh out from skeleton theme according to Bracknell needs

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#106]

**Comment by willguv** [comment]
- [ ] @robhmicroserve can you make a list of things you'd expect to see
- [ ] @willguv to set up meeting for @robhmicroserve @cjstevens78 @Adnan-cds as required to discuss any requirements in detail

**Comment by willguv** [comment]
@robhmicroserve says:

- Templates that haven't been put into modules
- Bootstrap classes stripped out
- Pre-process functions
- No assets
- No documentation
- No build tools

- [ ] @cjstevens78 copy the theme templates over the skeleton theme, avoiding any that have been duplicated for bootstrap reasons
- [ ] @robhmicroserve to assess the templates and let us know what's needed/ not

**Comment by cjstevens78** [comment]
@willguv I had a look at the pre process stuff and think it would be better if @Adnan-cds has a look at it because theres function names in there specifically referencing localgov theme and I dont know enough about it to know if its going to break it renaming them.

**Comment by Adnan-cds** [comment]
> if its going to break it renaming them.

Hi Chris,
I can confirm that you can rename and move the preprocess functions from localgov_theme to localgov_skeleton.

In localgov_theme_preprocess_page(), you will have to rename the reference to the "localgov_theme/fontawesome" asset library.  This library is defined in the localgov_theme.libraries.yml file.  To move the definition of this library, please **cut** and paste the relevant parts into the localgov_skeleton.libraries.yml file.  I am linking to the relevant part in [Drupal's documentation](https://www.drupal.org/docs/creating-custom-modules/adding-stylesheets-css-and-javascript-js-to-a-drupal-module#library).

**Comment by willguv** [comment]
@cjstevens78 we created the theme, it can be selected, stripped out unnecessary code (see list provided by Rob above)

@cjstevens78 please merge the pull request
