### ISSUE TITLE
[2d Adnan, 3d Chris] Move the Croydon/ Brighton homepage over

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#107]

**Comment by willguv** [comment]
- [ ] Move the Brighton homepage
- [ ] Move the Campaign block
- [ ] Move the Email and Social Media subscription block
- [ ] Styling for all
- [ ] Visual checks by Chris and Dave

SEPTEMBER
- [ ] Move the News block
- [ ] (Maybe) move the Big Bang Announcement, or combine with Alerts

**Comment by andybroomfield** [comment]
Tracking issue for Big Bang annoucement if it gets integrated with alert banner will be localgovdrupal/localgov_alert_banner#76

**Comment by Adnan-cds** [comment]
> Tracking issue for Big Bang annoucement if it gets integrated with alert banner will be localgovdrupal/localgov_alert_banner#76

Thanks Andy.  Yeah, I will try to resolve localgovdrupal/localgov_alert_banner#76 while porting Big bang announcement.

FAO @andybroomfield

**Comment by Adnan-cds** [comment]
Current status:
- I have extracted the Drupal config files for the BHCC Homepage content type into a separate module: https://github.com/localgovdrupal/localgov_homepage/tree/feature/existing-config-files.  Seems to work :)
- It doesn't have any theme template files, so looks horrible.  That's next.
- I will have to move the Paragraph related config files into the localgov_paragraphs module.

While working on this, I noticed that the localgov_campaigns_paragraphs module [depends on the localgov_core module](https://github.com/localgovdrupal/localgov_campaigns/blob/1b4de732dd8584376169f6e4e90e205ae2c0174a/modules/localgov_campaigns_paragraphs/localgov_campaigns_paragraphs.info.yml#L11).  Not sure if that's needed.

Also noticed that the localgov_paragraphs module depends on the [localgov_core:localgov_media](https://github.com/localgovdrupal/localgov_paragraphs/blob/199cbef8ef86ab6934fbb707f57387369bdcc6af/localgov_paragraphs.info.yml#L26) module, but its [composer.json](https://github.com/localgovdrupal/localgov_paragraphs/blob/master/composer.json) doesn't know that :(

I will later raise tickets for the above two issues.

FAO @willguv @stephen-cox

**Comment by willguv** [comment]
This is done, and the functionality needs to be tested

@willguv will write a separate card for this
