### ISSUE TITLE
Test Directories functionality - BREAK INTO CARDS

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#110]
Hi @ekes I've done some basic functional testing of directories - see below for everything I've found so far. Doesn't seem like anything major.

@cjstevens78 is about to add the theme to these pages, so I'll do more testing after you and he are done - thanks for your continued help!

Copying @finnlewis

**Comment by willguv** [comment]
Add channel > Left enabled facets blank

Error message
Warning: array_diff(): Argument #2 is not an array in Drupal\Core\Entity\Plugin\Validation\Constraint\ValidReferenceConstraintValidator->validate() (line 134 of core/lib/Drupal/Core/Entity/Plugin/Validation/Constraint/ValidReferenceConstraintValidator.php).
Drupal\Core\Entity\Plugin\Validation\Constraint\ValidReferenceConstraintValidator->validate(Object, Object) (Line: 196)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateConstraints(Object, '0000000038b3fec500000000119e6953', Array) (Line: 148)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode(Object) (Line: 158)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode(Object, Array, 1) (Line: 100)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validate(Object, NULL, NULL) (Line: 90)
Drupal\Core\TypedData\Validation\RecursiveValidator->validate(Object) (Line: 132)
Drupal\Core\TypedData\TypedData->validate() (Line: 489)
Drupal\Core\Entity\ContentEntityBase->validate() (Line: 192)
Drupal\Core\Entity\ContentEntityForm->validateForm(Array, Object)
call_user_func_array(Array, Array) (Line: 82)
Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object) (Line: 273)
Drupal\Core\Form\FormValidator->doValidateForm(Array, Object, 'node_localgov_directory_form') (Line: 118)
Drupal\Core\Form\FormValidator->validateForm('node_localgov_directory_form', Array, Object) (Line: 589)
Drupal\Core\Form\FormBuilder->processForm('node_localgov_directory_form', Array, Object) (Line: 321)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 91)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
Enabled Facets field is required.

**Comment by willguv** [comment]
On saving https://localgovdrupal.agile.coop/schools/find-school/primary-infant-and-junior-schools for the first time

Warning: array_diff(): Argument #2 is not an array in Drupal\Core\Entity\Plugin\Validation\Constraint\ValidReferenceConstraintValidator->validate() (line 134 of core/lib/Drupal/Core/Entity/Plugin/Validation/Constraint/ValidReferenceConstraintValidator.php).
Drupal\Core\Entity\Plugin\Validation\Constraint\ValidReferenceConstraintValidator->validate(Object, Object) (Line: 196)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateConstraints(Object, '00000000524507b6000000007b74e014', Array) (Line: 148)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode(Object) (Line: 158)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode(Object, Array, 1) (Line: 100)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validate(Object, NULL, NULL) (Line: 90)
Drupal\Core\TypedData\Validation\RecursiveValidator->validate(Object) (Line: 132)
Drupal\Core\TypedData\TypedData->validate() (Line: 489)
Drupal\Core\Entity\ContentEntityBase->validate() (Line: 192)
Drupal\Core\Entity\ContentEntityForm->validateForm(Array, Object)
call_user_func_array(Array, Array) (Line: 82)
Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object) (Line: 273)
Drupal\Core\Form\FormValidator->doValidateForm(Array, Object, 'node_localgov_directory_form') (Line: 118)
Drupal\Core\Form\FormValidator->validateForm('node_localgov_directory_form', Array, Object) (Line: 589)
Drupal\Core\Form\FormBuilder->processForm('node_localgov_directory_form', Array, Object) (Line: 321)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 91)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by willguv** [comment]
On https://localgovdrupal.agile.coop/node/52/edit

Wouldn't accept "http://www.aerodromeprimary.co.uk/" as the url of enquiries website
<img width="727" alt="Screenshot 2020-09-07 at 19 25 08" src="https://user-images.githubusercontent.com/708140/92411586-5f762280-f140-11ea-9968-5b4f40bd3eb2.png">

**Comment by willguv** [comment]
On https://localgovdrupal.agile.coop/schools/find-school, the text under "Primary, infant and junior schools" should just be the summary, nothing else

**Comment by willguv** [comment]
When changing the parent of a directory channel (and so its breadcrumbs and url), you have to manually edit/ save every directory entry beneath it for their breadcrumbs and url to change

Would be good if this change could be scripted in some way - nice to have

**Comment by willguv** [comment]
On directory channel, page and venue, summary fields should ideally be open be default. Shouldn't have to click "Show summary" as can be easily missed

**Comment by willguv** [comment]
Seems like the facets are OR not AND

https://localgovdrupal.agile.coop/schools/find-school/primary-infant-and-junior-schools?f%5B0%5D=localgov_directories_facets%3A8&f%5B1%5D=localgov_directories_facets%3A9&f%5B2%5D=localgov_directories_facets%3A15

I prefer this - check with everyone else

Compare with https://lbc-app-w-corpwebsite-p.azurewebsites.net/schools-and-education/schools/find-school-near-you/primary-infant-and-junior-schools?search=&facet_type_of_school%5B138%5D=138&facet_type_of_school%5B134%5D=134&facet_type_of_school%5B108%5D=108

**Comment by willguv** [comment]
Just tried adding https://localgovdrupal.agile.coop/schools/find-school/primary-infant-and-junior-schools/aerodrome-primary-academy to two directories - works a treat

Hi @ekes I've done some basic functional testing of directories and here's what I've found so far

Doesn't seem like anything major

@cjstevens78 is about to add the styling to this page, so I'll do more testing after you and he are done - thanks for your continued help

Copying @finnlewis

**Comment by finnlewis** [comment]
Hi @willguv 

Just reviewing issues and wonder if this one can be closed? If we can break these our into individual issues, I think that would be best to be able to resolve them separately.

Many thanks,

Finn
