### ISSUE TITLE
Content migration discussion

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#117]
Both Croydon and Brighton need to migrate to LGD

Croydon will move all content to a fresh install, and aims to complete by 5 Oct. See sprint dates at https://trello.com/b/kSUmqoR3/new-website-dev

Brighton is investigating options, either using modules with its existing codebase or moving content to a fresh install

We need to look at the Croydon migration work Ekes has started, and Andy has tested, to answer any questions and estimate effort

**Comment by finnlewis** [comment]
This has been discussed, closing.
