### ISSUE TITLE
Supplier conversations

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#120]
- Any barriers/ concerns about joining
- Identify suppliers (Agile Collective, Oliver's Intranet suppliers - Panlogic -, Code Enigma, Finn has a suggestion, GraphicAlliance, Westminster's devs?)
- Let John know about suitable agency contacts
- prep a short intro to share with agencies

**Comment by andybroomfield** [comment]
@willguv Maybe Miggle, Not sure if they are still active but they did build original BHCC so may be worth getting pespective?
