### ISSUE TITLE
BHCC demo theme - create a quick example theme for BHCC migration demo

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#122]
This is initially just for demo purposes internally and may not be the ultimate theme architecture.

**Comment by andybroomfield** [comment]
https://github.com/localgovdrupal/localgov_theme_bhcc

![screencapture-localgov-lndo-site-8000-adult-health-and-social-care-2020-09-16-23_31_20](https://user-images.githubusercontent.com/1467480/93489471-79adbe80-f8ff-11ea-8992-9fb5a440a2fb.png)
