### ISSUE TITLE
Rename croydon_migration to localgov_legacy_migration and make public.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#127]

**Comment by stephen-cox** [comment]
Pull request that adds the renamed module to the LocalGov profile is here: https://github.com/localgovdrupal/localgov/pull/130

**Comment by andybroomfield** [comment]
@stephen-cox Do we need to add to the distribution as this is really a seperatly installed module to help migrate code? When I've been testing migration I've used the localgov project but asked it to clear the VCS folders so I'm starting as a new project, and that may be the same here? Or is this just for simplicity?

**Comment by stephen-cox** [comment]
As mentioned at stand up, this is partly laziness as it doesn't have to be installed separately while working on it and partly because it doesn't seem to do any harm. We can always remove it later, but happy to have to install it manually if people prefer.
