### ISSUE TITLE
Test template

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov#131]
As [discussed already](https://github.com/localgovdrupal/localgov_paragraphs/pull/6#pullrequestreview-483852944), we are considering adding an [Organization-wide Github actions test template](https://docs.github.com/en/actions/configuring-and-managing-workflows/sharing-workflow-templates-within-your-organization).  This will be inherited by all new projects saving us from manually copy-pasting the Test workflow file in each project.

FAO @stephen-cox @finnlewis

**Comment by finnlewis** [comment]
This is now in place: https://github.com/localgovdrupal/.github

Thanks @Adnan-cds !
