### ISSUE TITLE
Markup for social media icons in the Subscribe panel Paragraph

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov#132]
As [mentioned](https://github.com/localgovdrupal/localgov/issues/107#issuecomment-678140917) by @cjstevens78, we need custom markup for the Social media icon field used in the Subscribe panel paragraph.

This should go into the [localgovdrupal/localgov_paragraphs](https://github.com/localgovdrupal/localgov_paragraphs) repository.

**Comment by andybroomfield** [comment]
Do we still need to do this? @Adnan-cds

**Comment by Adnan-cds** [comment]
The [labelled icon paragraph template](https://github.com/localgovdrupal/localgov_paragraphs/blob/2.x/modules/localgov_homepage_paragraphs/templates/paragraph--localgov-labelled-icon.html.twig) fulfills this.  So this can be closed.
