### ISSUE TITLE
Add "Raw HTML" text format

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov#134]
The "Raw HTML" text format should allow unrestricted entry of HTML markup in formatted text areas.  This text format should be restricted to site admins only.  At the moment, the [Design system pages in the Croydon site](https://new.croydon.gov.uk/design-and-content-guidelines) makes heavy use of this text format.

**Comment by finnlewis** [comment]
When you say "should be restricted to site admins", do you mean role "admin" or similar? We don't currently have one in the default install. We added one for Lambeth. 

As to whether we should include a Raw HTML as default, I'm not sure we should encourage it in the default install.

What does it get used for at Croydon?

**Comment by Adnan-cds** [comment]
> do you mean role "admin" or similar?

That's right.

> We don't currently have one in the default install. 

Sorry, I wasn't aware of that.  If we can't have an Administrator role then this ticket can be dropped.

> What does it get used for at Croydon?

Some of Design Dave's [Design system pages](https://new.croydon.gov.uk/design-and-content-guidelines) use CSS and Javascript as part of the page content even before these get implemented in the theme.  The markup can also have properties not whitelisted yet.  An unrestricted text format helps here.  That has been the major use case so far.

**Comment by andybroomfield** [comment]
FWIW we have a unrestricted html format on BHCC, but its use is now discouraged and apart from some historical pages where we need to do special embeds (which we are replacing with shortcodes) and some highly specialised markup. If it was to go in then should be very restricted.

**Comment by finnlewis** [comment]
Thanks for the explanation @Adnan-cds 

Personally, I think this is quite a specific need for Croydon Council based on the design system pages that you have. On Lambeth, for example, we are going down the Storybook route of a separate pattern library / style guide not content managed in Drupal. 

I don't really see this as a justification for including a Raw HTML in LocalGov Drupal at the moment. 
In my experience these unfiltered input formats get rapidly abused to put in all manner of iframes, scripts, broken HTML etc. 
So while it should be possible for each council to add such input formats, I don't think we should encourage it as best practice. Happy to discuss futher. 

I wonder what other opinions there might be @bhccwebmaster @ekes @stephen-cox @willguv ?

On the roles front, I do think we should add an 'Admin' or 'Administrator' role, which is perhaps a seperate but related concern.

**Comment by stephen-cox** [comment]
The problem with having text formats that are only usable by admins is that it's not possible for other users to edit the content which can cause problems, so it's not a good idea to have this generally available. If this is only really required for a single content type then I expect we can find a better solution for this.

**Comment by Adnan-cds** [comment]
Closing as there is no appetite for it at the moment.
