### ISSUE TITLE
Allowed memory size of 1610612736 bytes exhausted when installing with composer

### ISSUE THREAD

**Issue by tanc** [localgovdrupal/localgov#135]
I was hitting the composer set memory limit of 1.5G when trying to run `composer create-project --stability dev localgovdrupal/localgov-project  MYPROJECT`

Setting no limit allowed it to complete:

```
COMPOSER_MEMORY_LIMIT=-1 composer create-project --stability dev localgovdrupal/localgov-project MYPROJECT
```

**Comment by stephen-cox** [comment]
Were you running the Composer command inside Lando? I find this is a common issue when running Composer in Lando and so always run composer outside of Lando.

In any case we should update the [docs](https://github.com/localgovdrupal/localgov#installing-localgovdrupal) for this.

**Comment by tanc** [comment]
It was outside Lando, following the docs. Lando doesn't exists when you run the `composer create-project` command

**Comment by stephen-cox** [comment]
That's possibly a misconfiguration with PHP on your local computer then. On Ubuntu I have `memory_limit = -1` in my `/etc/php/7.4/cli/php.ini` file.

**Comment by tanc** [comment]
I guess it could be although I had left `php.ini` at default. Composer automatically changes it to 1.5G as explained here: https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors

I think we can't assume that people with have altered their `memory_limit` to be unlimited so in my opinion it would make sense to specify it in the docs.

**Comment by stephen-cox** [comment]
My `php.ini` has not been modified from the install and I thought this was the default memory setting for command line PHP usage, but feel free to raise a pull request for any documentation changes :smiley:

**Comment by tanc** [comment]
I guess it depends on your distro. Arch comes with a default memory_limit of 128Mb which it pulls from php.ini, checked with `php -i | grep memory_limit`. I'll update the docs and issue a pull request

**Comment by tanc** [comment]
Added #137
