### ISSUE TITLE
Add EU Cookie Compliance module

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#142]
Issue to discuss adding the https://www.drupal.org/project/eu_cookie_compliance module.

This follows discussion on https://github.com/localgovdrupal/localgov/issues/25#issuecomment-702153081

@Adnan-cds suggested it, so I'm guessing it is used on Croydon Council's website.

I have no objections, but I do know that at least one council assessed it and found it lacking, so decided to roll their own.

What about the BHCC site @andybroomfield.

Any other comments @stephen-cox @ekes

If there's no objections, let's get a PR in for it.

**Comment by ekes** [comment]
This is going to need some thought I assume. The intention would be as with everything else to ship best practice. But I don't think we've, or will, actually ship any analytics modules? So what we're shipping is best practice - only required functionality cookies - no consent required. 

We know that people will be adding tracking, but don't know which, and to add a GDPR opt-outs you need to which. I guess you we could assume Google and add code with the EU Cookie Compliance module - but it wouldn't make sense to offer opt-outs for things that might not be there.

Sorry. Morning brain-dump. Maybe I'll have something more constructive later.

**Comment by andybroomfield** [comment]
We have the standard EU Cookie compliance set up with `hide-alert-banner-token` whitelisted (everything else should get blocked until aggreed, our cookie policy is [here](https://www.brighton-hove.gov.uk/about-website/how-we-use-cookies), Google Analytics and Hotjar are the services we use). We've talked before about having specific options, and something like the [Gov.uk cookies page ](https://www.gov.uk/help/cookies) would be helpful, though it would be up to individual councils to add their services to each category.

**Comment by stephen-cox** [comment]
Just a thought, but is this something that should be spun into it's module that includes Google Tag Manager and any other analytics / tracking sort of stuff? If Croydon and BHCC have similar requirements then they could use this. Other councils would then have the option of a default setup or to roll their own.

**Comment by Adnan-cds** [comment]
> and something like the Gov.uk cookies page would be helpful,

Hi Andy,
We have a custom module that makes the EU cookie compliance popup's content available as a **block**.  We use this block in the [Croydon site's Cookie settings page](https://new.croydon.gov.uk/cookies).  This module isn't perfect, but if there's enough demand for it, this custom module can be polished and added as an optional module to the LocalGov family of modules.

FAO @andybroomfield @willguv @finnlewis

**Comment by finnlewis** [comment]
We should return to this... the modules have moved on in the last year or two!

**Comment by budda** [comment]
Having a documented cookie banner option that ticks all the compliance boxes with minimum effort would be a nice to have as a fallback for, maybe smaller, councils which just want to have something on their site.

**Comment by keelanfh** [comment]
We now have https://github.com/localgovdrupal/localgov_eu_cookie_compliance
