### ISSUE TITLE
LocalGov Drupal Admin UX

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#148]
A number of us are keen to make sure the admin user expeirence is as good as possible in LocalGov Drupal.

Lambeth is launching the first section of content next week and we're keen to make sure content designers have the best start. 

To this end, we've created a localgov_claro repository to start investigating how a sub-theme of Claro might help.

We're also looking at elbow_room and other contrib to assist in tidying up the node/add node/edit forms. 

Any thoughts or suggestions ? 

@andybroomfield @Adnan-cds @stephen-cox @cjstevens78 @ekes @paulpopus @willguv

**Comment by andybroomfield** [comment]
Mentioned before however highly recommend [Tasty Backend](https://www.drupal.org/project/tasty_backend) or at least its approach to seperating out how the admin toolbar and manage content views are arranged.

Could do with looking at how we handle the manage content screen and review que, whether that starts with the BHCC existing views, or something much cleaner.

**Comment by willguv** [comment]
I think @Adnan-cds used Elbow Room and some custom code to remember a content designer's preferences when hiding or showing the sidebar. Hide it, and it stays hidden until the designer decides to show it again. We'll likely add that back in to the Croydon version of the site, and it's a good candidate for being included in LGD.

It's also worth a review/ tidy up of all the tab labels in each content format as there's inconsistencies across some formats, and some could be more clear. The kind of fields a tab contains should be obvious before a content designer clicks on them.

The Croydon content designers will start adding dummy content from next week, so there's an opportunity to work across a few of the councils on this

**Comment by finnlewis** [comment]
Since the original post, Gin Theme (https://www.drupal.org/project/gin) has become a favourite admin theme in the Drupal community. 

_A radically new UI layout paired with goodies like a Darkmode will give your Drupal's Admin interface a facelift. The Gin theme also includes things which are currently out of scope for Claro and/or some customisations we're experimenting with for the future. Built on the foundation of Claro from one of the lead designers of Claro & Drupal Design System._

Maybe we can try this on LocalGov Drupal with a branch and some testing? 

@paulpopus might you be interested in trialing this?

**Comment by paulpopus** [comment]
Yep, I think I'll try it with Lambeth and a fresh install of LocalGov and get back with a PR.

**Comment by paulpopus** [comment]
I'm back with a report and some screenshots, I'll start with my tests on Lambeth.

First off you can customise the toolbar so you can keep the classic Drupal toolbar if you need it 
![Screenshot from 2021-03-03 11-27-34](https://user-images.githubusercontent.com/35137243/109802057-362ddf00-7c17-11eb-900a-05e7d040a933.png)
There is a BETA dark mode too and you can change the highlight colours, though it might not be on a per-user basis.

Screenshot of the editing page, you can close the sidebar menus, as
![Screenshot from 2021-03-03 11-28-55](https://user-images.githubusercontent.com/35137243/109803775-5b235180-7c19-11eb-914e-d28ef0bb4f42.png)

There was an issue with the [office_hours](https://www.drupal.org/project/office_hours/issues/2949644) module which did sort of break, though it is an issue with the module and not the theme.
![Screenshot from 2021-03-03 11-30-42](https://user-images.githubusercontent.com/35137243/109819049-8ca51880-7c2b-11eb-9256-7183ed424e8f.png)

On LocalGov specifically from a fresh install I haven't found any issues and the interface looks really great.
![Screenshot from 2021-03-03 12-25-17](https://user-images.githubusercontent.com/35137243/109823152-94ff5280-7c2f-11eb-919b-d65fff7889f2.png)

@finnlewis and whoever else is interested, if you think ^ is fine I can go ahead and open a PR to get the Gin theme into localgov and some documentation on configuring it.

**Comment by willguv** [comment]
Thanks for taking a look @paulpopus 

It looks a lot cleaner, so that's a big plus. I've looked at the Gin page on Drupal and can't see anything specific about accessibility - may have just missed it.

Is this a lot more accessible than Claro and the default admin theme?

**Comment by paulpopus** [comment]
@willguv It's not more accessible. It's based on Claro so it takes a lot of what Claro does and makes the general UI better and more modern. From my testing it does pass accessibility tests and the fact that it's based on Claro most likely means it won't be _worse_.

Claro _is_ more accessible than the default admin theme though.

I've also just noticed it has some extra modules:
https://www.drupal.org/project/gin_toolbar
https://www.drupal.org/project/gin_login

Of course they're entirely optional but worth looking at.

**Comment by willguv** [comment]
Thanks @paulpopus. Are you or Finn coming to the product group tomorrow? (1pm) 

We've got a few mins to talk about our plans for Gin, and showing this work would be a big step forward

**Comment by finnlewis** [comment]
Hi @willguv 
I'll be coming along, but I will have to leave for another meeting at 2pm. 
Hopefully @paulpopus can make it too.
Let's share what we know about Gin theme so far to keep people in the loop.
Cheers,
Finn

**Comment by paulpopus** [comment]
Sorry I couldn't make the meeting.

Did any action points rise out of it? @willguv @finnlewis

**Comment by finnlewis** [comment]
Waltham Forest are already using Gin on their dev site. 

We'll get a branch set up and deployed to the dev site to get Gin, Gin Login, Gin Toolbar up on the dev site. 

This was discussed again on the Project Group meeting today., people are keen to test.

**Comment by finnlewis** [comment]
The Gin theme was included with https://github.com/localgovdrupal/localgov/pull/240

But it is not yet enabled and set as the default admin theme on a fresh install.

I think it should be!

**Comment by willguv** [comment]
@finnlewis yes agree - shall we make this a part of the next sprint?
