### ISSUE TITLE
Speedup test runs

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov#151]
As discussed already, I have so far tried two changes to [speed up](https://github.com/localgovdrupal/localgov_paragraphs/runs/1096904645?check_suite_focus=true) the test run:
- Wrap invocation of PHPUnit with [brianium/paratest](https://packagist.org/packages/brianium/paratest)
- Use an SQLite database instead of MySQL.

#### localgovdrupal/localgov_project
```
$ composer create-project --stability dev localgovdrupal/localgov-project
$ pushd localgov-project
$ composer require --dev brianium/paratest:^4.0.0
```

#### localgovdrupal/drupal-container
```
$ sed --in-place '30 s#./bin/phpunit --testdox#./bin/paratest --processes=4 --verbose=1#' run-tests.sh  # 4 parallel test runs.
$ sed --in-place '13 s#mysql://database:database@database/database#sqlite://sites/default/files/.ht.sqlite#' docker-compose.yml  # Use Sqlite instead of MySQL.
$ sed --in-place '20,+12 d' docker-compose.yml  # Remove reference to MySQL container.
```

### Other
Keeping Drupal in a memory mapped file like */dev/shm/html* instead of *./html* also speeds up the test runs to some extent, but this forces updating all test scripts which is not worth it IMHO, so I am skipping this part.

FAO @finnlewis @paulpopus @stephen-cox @andybroomfield

**Comment by finnlewis** [comment]
Thanks @Adnan-cds !

@paulpopus are you able to take a look at this?

**Comment by paulpopus** [comment]
Project PR: https://github.com/localgovdrupal/localgov_project/pull/25
Container PR: https://github.com/localgovdrupal/drupal-container/pull/6

**Comment by Adnan-cds** [comment]
Sorry, I forgot to mention the Cons of [brianium/paratest](https://packagist.org/packages/brianium/paratest) last night :(  The test output from ```./bin/paratest --verbose=1``` is not as good as ```./bin/phpunit --testdox```.  This has been [raised](https://github.com/paratestphp/paratest/issues/396) with the paratest project as a feature request but has not been implemented yet :(

FAO @finnlewis @paulpopus @stephen-cox

**Comment by paulpopus** [comment]
Thanks for helping out with this @Adnan-cds 

The tests on the container in the PR can now run but they fail with 
```
Failed to run installer database tasks: Failed to connect to your database server. 
```
I assume it's related to sqlite. I didn't manage to get the tests running locally to debug it.

https://github.com/localgovdrupal/drupal-container/pull/6/checks?check_run_id=1320414835

**Comment by Adnan-cds** [comment]
> I assume it's related to sqlite. I didn't manage to get the tests running locally to debug it.

Sorry Paul, I forgot that to use sqlite, php needs the sqlite3 extension which the Docker container used for test runs don't have.  You can add it to the [Dockerfile](https://github.com/localgovdrupal/drupal-container/blob/ad1a3aa4f87580ca6eb84c449fff14e4cca646af/Dockerfile#L27) as a **separate** pull request.  Package name is **php-sqlite3**.  But Steve will then have to upload it to Docker hub.  This complicates things.  As a first attempt, lets skip SQLite for now and just invoke paratest.  This means the only change needed for localgovdrupal/drupal-container is:
```
$ sed --in-place '30 s#./bin/phpunit --testdox#./bin/paratest --processes=4 --verbose=1#' run-tests.sh  # 4 parallel test runs.
```

**Comment by Adnan-cds** [comment]
Hi Paul,
Many thanks for updating the pull request.  I can see what's causing the [test failure](https://github.com/localgovdrupal/drupal-container/runs/1320533742?check_suite_focus=true#step:5:140).  I will try to add a fix.

**Comment by Adnan-cds** [comment]
When I last tried paratest, I had the right value for SIMPLETEST_BASE_URL in phpunit.xml.dist.  PHPUnit can pick such values from environment variables.  But when phpunit is invoked through paratest, it is not seeing the environment variables.  This is a [known issue](https://github.com/paratestphp/paratest/issues/103) and there is a work around which involves updating the value of SIMPLETEST_BASE_URL in the phpunit.xml.dist file to say "http://drupal" instead of the current "http://localgov.lndo.site".  I will update the pull request later which should save your further trouble.

**Comment by Adnan-cds** [comment]
I have implemented the above mentioned change and raised another [pull request](https://github.com/localgovdrupal/drupal-container/pull/8).

**Comment by Adnan-cds** [comment]
Perhaps we can close this? @finnlewis

**Comment by finnlewis** [comment]
I think we can!
