### ISSUE TITLE
Replace localgov_campaigns with renamed localgov_subsites

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#156]
This is related to https://github.com/localgovdrupal/localgov_campaigns/issues/71

LocalGov Subsites (https://github.com/localgovdrupal/localgov_subsites) is an evolution of LocalGov Campaigns (https://github.com/localgovdrupal/localgov_campaigns).

To fully make this change in the distribution, we will proably need to implement a migration for users that have already got content in localgov_campaigns.

**Comment by finnlewis** [comment]
Hi @gosia-mlynarczyk  - just drawing your attention to this to discuss. 

I am also wondering about other developers or councils that need to be fully aware of the shift from localgov_campaigns to localgov_subsites.

I've been contacted by Hammersmith & Fulham Council, and hopinh to talk to Wesminster and Zoocha this afternoon.

@willguv do you know who else might need to know?

**Comment by andybroomfield** [comment]
My guess is that this is done, so can the issue close now @finnlewis @willguv ?

**Comment by willguv** [comment]
@andybroomfield @finnlewis this work is done. So we still need to deprecate the legacy code?

**Comment by finnlewis** [comment]
Yes indeed. I've added a large heading to the readme https://github.com/localgovdrupal/localgov_campaigns 

I've done some of the things suggested here: 

https://medium.com/maintainer-io/how-to-deprecate-a-repository-on-github-8f0ceb9155e

Do we need to anything else?

**Comment by willguv** [comment]
Looks good to me @andybroomfield. Thank you
