### ISSUE TITLE
Create module for localgov_components

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#16]
A empty module to house paragr

We're starting with localgov_components for the core paragrpahs that are needed for base content types. 

Future dependencies on other paragraphs for campaings for example, might be called localgov_campaigns_components

**Comment by finnlewis** [comment]
I'll make a start on this.

**Comment by finnlewis** [comment]
@stephen-cox 

After some quick research into other distributions, I decided localgov_paragraphs is a better name than localgov_comonents, as it describes better what it is in the Drupal world.

Hope that makes sense.

**Comment by stephen-cox** [comment]
Done. Cleaning up.
