### ISSUE TITLE
Google Chrome 87 renders fieldset with grey artefacts

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#161]
This is a known issue on Drupal.org 

See https://www.drupal.org/project/drupal/issues/3183425

![image](https://user-images.githubusercontent.com/326588/100098792-70d4ee00-2e56-11eb-8e99-0ff4b3aae164.png)

**Comment by andybroomfield** [comment]
[Chrome fixed the bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1150803) and Drupal fixed the styles in Drupal 9 so I'm going to close this for now. Please reopen if there are more comments.
