### ISSUE TITLE
Tests fail to build if the pull request if from a forked repo

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#162]
Creating a fork of a repo then a pull request from the fork seems to prevent the test script checking out the correct branch. 

I think this is due to 

``` composer --working-dir=html require ${{ github.repository }}:"dev-${GIT_BRANCH} as 1.0.x-dev"```

https://github.com/localgovdrupal/.github/blob/master/workflow-templates/localgov-drupal-ci.yml#L38

If we can change this to check out the branch from the source repository, that might allow it to build.

If not, we might not be able to run tests against pull requests from repositories that have been forked.

**Comment by Adnan-cds** [comment]
Thanks Finn, I will have a look.

**Comment by Adnan-cds** [comment]
This can be closed, right? @finnlewis @tebb

**Comment by finnlewis** [comment]
Yes! Thanks @Adnan-cds

**Comment by tebb** [comment]
This is fixed in the worflow template by this:

https://github.com/localgovdrupal/.github/pull/7

which has been tested by @paulpopus but not merged.
