### ISSUE TITLE
localgov profile doesn't enable the localgov_workflows submodule

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov#165]
The localgov profile currently [does not enable](https://github.com/localgovdrupal/localgov/blob/f3756ce8c792030a3fa2f14dd56ff0edc6e37198/localgov.info.yml#L7) the localgov_workflows submodule of the localgov_core module.  This means users with the **Content designer** role (machine name: localgov_editor) cannot publish pages.  This came to light when one of our editors asked a simple question: How do I publish this page?!!@#

FAO @finnlewis @willguv

**Comment by andybroomfield** [comment]
I think theres a wider discussion on what we enable in the profile by default. At the moment first install only enables services, and thats it. Should the profile enable everything? Or should there be a seperate localgov_full / kickstart profile?
See also #160 for a minimal profile.

**Comment by tebb** [comment]
Hi Andy/Adnan  @finnlewis 

I've been talking Matt Fletcher @mattrfletcher through migrating from Windows+WSL to Ubuntu/Zoom/Docker/Lando/Git etc this week and was planning on doing this issue with him tomorrow. No worries if it is/becomes redundant -  It's good to practice contribution on something simple and get familiarity with the tools.

Seems it's just adding this after line 43 in localgov/localgov.info.yml

  - localgov_core:localgov_workflows

Testing: We're both going to work through Oliver Davies' Test Driven PHP Development video, but I'm not optimistic that it'll cover testing install profiles :)

**Comment by Adnan-cds** [comment]
Thanks a lot Tebb.  I hope Matt gets his setup working soon.

As you can see above from Andy's reply, we are still not fully sure if we want this change.  But #150 is about a similar issue and we are in full agreement that we want it.  I have just tagged #150 as *good first issue*.  Would you mind looking into that instead?

FAO @tebb @mattrfletcher @finnlewis

**Comment by tebb** [comment]
Thanks Adnan, sounds good.  We'll do #150 instead.

Yes, I think Matt will soon see the light and be a Linux convert :)  @mattrfletcher

**Comment by andybroomfield** [comment]
Did this issue get resolved and can it be closed now?

**Comment by Adnan-cds** [comment]
> Did this issue get resolved and can it be closed now?

Nah, it has not been resolved.

**Comment by finnlewis** [comment]
It looks like the permission to publish content is granted by the 'administer content' permission.

There is a module to add a more granular permission https://www.drupal.org/project/publishcontent 

So @andybroomfield @Adnan-cds @willguv @tom-steel 

Questions: 

1. Should we give the content designer role the 'administer content' permission by default? 

2. Do you think the localgov_workflows module should be enabled by default?

It looks to me like it just enables the basic workflow. 

https://github.com/localgovdrupal/localgov_core/tree/2.x/modules/localgov_workflows

But this also extends permissions for the content designer to be able to change the workflow states. 

(This is a timely issue, as we're discussing workflows on Friday as we kick-off a working group to take this forwards. )

**Comment by willguv** [comment]
@finnlewis it feels like we shouldn’t allow content designers to alter workflow states, but I’d like to understand a bit better all the moving parts here first. 

Do we need to resolve this issue now, or can it be rolled into the working group discussions?

**Comment by mccrodp** [comment]
Hey folks. This is tagged [good first issue](https://github.com/localgovdrupal/localgov/labels/good%20first%20issue), but following the MT call earlier, I got the impression there's a move toward Recipes instead of Profiles. Does that change the significance or relevance of this old ticket, or can it be closed or otherwise revised?

**Comment by andybroomfield** [comment]
It might be closed, We should check that on enabling localgov_workflows the permissions are assigned. As it's now a seperate module, if it inlcudes hook_localgov_roles_default then it should

**Comment by andybroomfield** [comment]
Yes it does https://github.com/localgovdrupal/localgov_workflows/blob/f667b03fc6ab1bfb3f1cb571402fa254b1e8b6b5/localgov_workflows.module#L59-L98

**Comment by mccrodp** [comment]
Cool, thanks @andybroomfield. I take it this can be closed then. cc @Adnan-cds @willguv
