### ISSUE TITLE
Default date format

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov#166]
The default date formats (e.g. Default long date, Default medium date, Default short date) are set to Drupal's default which is based on the mm/dd/yyyy format.  Should we consider updating these to dd/mm/yyyy or leave these as they are in case LocalGov spreads beyond borders?

FAO @finnlewis @willguv

**Comment by andybroomfield** [comment]
Following is example of what BHCC has, which may be a good starting point.

Date Format|Example|PHP Date
-- | -- | --
BHCC Long Date | Tuesday 15 December 2020 - 11:40am | l j F Y - g:ia
BHCC Long Date - no time | Tuesday 15 December 2020 | l j F Y
BHCC Short Date - No time | 15/12/2020 | d/m/Y
BHCC Time | 11:40am | g:ia

**Comment by finnlewis** [comment]
@andybroomfield 's seem like sensible defaults. Shall we go with those @Adnan-cds ?

**Comment by Adnan-cds** [comment]
The BHCC formats are perfect of course.  Question is, should we create new date formats with "localgov_" prefix or update Drupal's default ones (e.g. core.date_format.long) which are used by Content listing Views and others.

**Comment by finnlewis** [comment]
Probably just update the defaults.
