### ISSUE TITLE
Tests failing on Github due to default PHP8

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#167]
> `- brianium/paratest 4.0.0 requires php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.`
see https://github.com/localgovdrupal/localgov_alert_banner/pull/102/checks?check_run_id=1578464643

**Comment by andybroomfield** [comment]
Attempted fix with https://github.com/localgovdrupal/.github/pull/4 but it does not appear to work.

**Comment by andybroomfield** [comment]
Changing the set php version to 7.2 worked.
https://github.com/localgovdrupal/localgov_alert_banner/pull/102/checks?check_run_id=1595966884

It breaks if the installed PHP version and the docker PHP version are different, as different dependencies will be installed. 
I thought Docker was meant to handle all of this? But thats not something I have experince with.
Either way if we are moving to PHP 7.4 (we should!) then we need to make sure docker is set to install and run using 7.4. Else we need to set the PHP version to use 7.2 when installing dependencies in composer (or find out how to do git clone and composer install inside the docker container).

FAO @Adnan-cds @ekes

**Comment by Adnan-cds** [comment]
> I thought Docker was meant to handle all of this?

At the moment, we are doing [composer create-project](https://github.com/localgovdrupal/.github/blob/f330dec6a3403bf708b2d64afaee431a08105ae7/workflow-templates/localgov-drupal-ci.yml#L27) within the Github build VM and then using [Docker to run](https://github.com/localgovdrupal/.github/blob/f330dec6a3403bf708b2d64afaee431a08105ae7/workflow-templates/localgov-drupal-ci.yml#L49) the tests.  It is possible to carry out the entire sequence within the Docker container although it will take some extra effort to implement.

> Either way if we are moving to PHP 7.4 (we should!) 

Yeah, that's where we are [kind of stuck](https://github.com/localgovdrupal/localgov_project/pull/35) at the moment :(

**Comment by finnlewis** [comment]
I think this is resolved, closing.
