### ISSUE TITLE
PHP 7.4 causes tests to fail wtih "Trying to access array offset on value of type null"

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#169]
This is coming from https://github.com/localgovdrupal/localgov_directories/issues/67

**Comment by Adnan-cds** [comment]
Now that this is fixed, we need a new release.  Tests in other repos will [keep failing](https://github.com/localgovdrupal/drupal-container/runs/1651463776?check_suite_focus=true#step:4:872) until this release is out.

**Comment by andybroomfield** [comment]
Did this get fixed and release and can this issue close now?

**Comment by Adnan-cds** [comment]
> Did this get fixed and release and can this issue close now?

This is sorted.  Closing...
