### ISSUE TITLE
Add localgov_news to packagist / distro

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#177]
Currently can't install news via composer require localgovdrupal/localgov_news.
Would be good to get this on packagist soon?

**Comment by Adnan-cds** [comment]
> Would be good to get this on packagist soon?

That's [done](https://packagist.org/packages/localgovdrupal/localgov_news/).  I have added @andybroomfield @ekes @finnlewis and @stephen-cox as maintainers.  Couldn't add Dan as packagist doesn't recognize *danchamp* as a username.

Dan's what's your packagist username please? @danchamp

**Comment by danchamp** [comment]
> Dan's what's your packagist username please? @danchamp

@Adnan-cds Thanks for this. I didn't have an account, but do now - danchamp

**Comment by Adnan-cds** [comment]
> but do now - danchamp

Wonderful.  I have just added you as a maintainer of the [localgov_news package](https://packagist.org/packages/localgovdrupal/localgov_news).  Not that there's much to do at there :)
