### ISSUE TITLE
Discovery: How does the default theme print?

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#183]
This was raised by Melanie at a product group session. Why do council sites contain leaflets that staff print out and hand to residents? Why aren't pages formatted for clear printing

Let's print out some pages and plan in changes

**Comment by andybroomfield** [comment]
Example
![Service page | Drush Site-Install](https://user-images.githubusercontent.com/1467480/111696840-aef28500-882c-11eb-94dd-bd540acc7c7c.png)
[Service page | Drush Site-Install.pdf](https://github.com/localgovdrupal/localgov/files/6167172/Service.page.Drush.Site-Install.pdf)

**Comment by danchamp** [comment]
@willguv It makes me happy to see this here, it should be picked up as part of the theme/front-end work.

We did some work on this for the London Councils beta that might be a useful starting point, I can write up a draft spec for comment if that would help:

[London Councils responds to Shelter’s new report on the housing emergency | London Councils.pdf](https://github.com/localgovdrupal/localgov/files/6577142/London.Councils.responds.to.Shelter.s.new.report.on.the.housing.emergency.London.Councils.pdf)

**Comment by willguv** [comment]
@danchamp yes some guidance would be great - we can make sure the new theme covers all the bases as we go

**Comment by willguv** [comment]
I'll add this to the localgov_base board

**Comment by willguv** [comment]
I’ll add this to the Cumbria’s Trello @andybroomfield and we’ll try it on base/ our child theme

**Comment by andybroomfield** [comment]
Ok @willguv I'll reopen it as it is still a live issue.

**Comment by keelanfh** [comment]
@msayoung doesn't necessarily come under WCAG compliance, but it's something we're interested in as well

**Comment by markconroy** [comment]
I'm not sure the a11y label is right on this issue. Happy for us to keep the issue open if we think there's work needed on it, but I don't think it's an accessibility issue.

**Comment by keelanfh** [comment]
I think I just tagged as accessibility because when we looked at the print styling for Essex, some of the text didn't have good contrast with the background. If we were looking seriously at print styling, it would seem reasonable to apply the WCAG standards for colour contrast to it.

I don't know if there would be other similar examples where we'd apply elements of the WCAG standard in print, perhaps not.

Not a WCAG compliance thing anyway, so I'm happy if we remove the label.

**Comment by andybroomfield** [comment]
Could we close this now as it's a discovery issue and then raise an issue on localgov_base for a print stylesheet?

**Comment by willguv** [comment]
Thanks @andybroomfield 

Closed in favour of [Print stylesheet](https://github.com/localgovdrupal/localgov_base/issues/425)

**Comment by keelanfh** [comment]
Actually closing :)
