### ISSUE TITLE
Discovery: Content lifecycle

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#184]
From the Product Group 18 March

Three tools that LGD doesn't currently provide for content designers: 

### Preview

The ability to send someone a link to preview the content before it is published. (Andy mentioned using: https://www.drupal.org/project/node_authlink) 

Reece Marsland
https://www.drupal.org/project/preview_link
using on WCC + RBKC for the same thing

### Review

How to allow for a date for review / reviewed and who can review and approve

Andy Broomfield
https://www.drupal.org/project/user_expire

### Scheduled publishing

The ability to schedule publishing/ unpublishing at a given time. (For example: https://www.drupal.org/project/scheduler ) 
John: This would be good for alerts. We know a system is going down for a period of time - schedule the alert. 
Andy
https://www.drupal.org/project/event_scheduler_publish

Ideally this would be easy to apply to single pages, and whole sections. Eg publish a whole guide and the landing pages linking to it

### Demo

Oxfordshire County Council have tackled a lot of this work

**Comment by andybroomfield** [comment]
[Scheduler](https://www.drupal.org/project/scheduler) only works with nodes though, so scheduling other content type (eg. Alert banners will need a patch for it). [See this issue](https://www.drupal.org/project/scheduler/issues/2096585).

Maybe Alert banners should get their [own out the box scheduler support](https://github.com/localgovdrupal/localgov_alert_banner/issues/115)?
