### ISSUE TITLE
How is it different

### ISSUE THREAD

**Issue by ugintl** [localgovdrupal/localgov#185]
How is it different than localgov_project? Do I need lando as well in addition to composer?

**Comment by j4-m** [comment]
Hi @ugintl `localgov_project` is a serves as a 'composer template', to be used with the `create-project` [command](https://getcomposer.org/doc/03-cli.md#create-project). This project is the actual Drupal installation profile and is required by `localgov_project`. You can use this project independently of `localgov_project` but in most cases you'll want to follow the [installation instructions](https://localgovdrupal.org/getting-started/) documents on localgovdrupal.org

**Comment by markconroy** [comment]
I think this issue looks like it can be closed now?

**Comment by andybroomfield** [comment]
Yes, I'll close this.
