### ISSUE TITLE
Test and release the field rename branches

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#188]
This ticket is to hang a branch off to test the various branches of the field rename work. 

https://github.com/localgovdrupal/localgov_core/tree/fix/35-rename-fields
https://github.com/localgovdrupal/localgov_theme/tree/fix/152-renamed-fields 
https://github.com/localgovdrupal/localgov_page_components/tree/fix/8-field-rename 
https://github.com/localgovdrupal/localgov_services/tree/fix/75-rename-fields

**Comment by andybroomfield** [comment]
done
