### ISSUE TITLE
Create module for localgov_standard_page

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#19]
To be discussed, but we think the standard page could be the starting point for a basic install.

Services can then build ontop of the standard_page. 

In our meeting last week the discussion suggested that no council would ever want an install wihtout services, so separating standard page content type made no sense.

One argument for keeping standard page separate is for use on microsites . A basic install might not want to install services, nbut still want a standard page content type.

To be discussed...

**Comment by ekes** [comment]
The imported `localgov_services_page` exists in `localgovdrupal/localgov_services'.

It has a hard dependency on the localgov_services_sublanding and localgov_services_landing by virtue of having two entity reference fields pointing to them. Code for these fields is now in `localgov_services_navigation`. There is an issue about how to integrate other content types not in Services componenet that also link into 'Services' (these content types have entity reference to sublanding and landing just as Page does -- and also equally get entity referenced to by services landing) localgovdrupal/localgov_services#6

Should there be a particularly neat solution to uncoupling the reference fields then the localgov_services_page could equally just become localgov_standard_page, and this content type opt-in to being referenced, and be able to reference, services if the module is enabled. At the moment it looks like it might be a bit more involved (adding fields and registering an interest in config) at which point keeping a dedicated services page makes sense.

**Comment by finnlewis** [comment]
Following your comment @ekes we discussed the services dependency architecture more yesterday.  I think this ticket is now redundant, as the standard page is within the services modules. Is that right?

**Comment by stephen-cox** [comment]
This has become localgov_services_page.
