### ISSUE TITLE
Major version upgrade testing

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#191]
Thunder test upgrades automatically. 

It would be good for us to do this on the D9 upgrade.

**Comment by ekes** [comment]
https://github.com/thunder/thunder-distribution/blob/6.1.x/.github/workflows/test.yml#L145

Above uses the `name: Use Thunder 3.4 lockfile` then installs the site; switches to 3.5 `composer require thunder/thunder-distribution:^3.5.0 phpunit/phpunit:^7 --no-update` and updates and runs the tests.

I'd say we could do similar and comprehensive by write tests for localgovdrupal/localgov_demo. Then write a workflow that installs the site with the demo enablled at the version prior to upgrade. Switch, and update. Then run the tests. This would check the other module tests, but also the data integrity. 

Then in the future if anyone wants to makes sure some content is stable and upgrades, make some demo content, and a test for it and get it into localgov_demo.

**Comment by andybroomfield** [comment]
Close as a D9 ticket, are we doing this for D10?
