### ISSUE TITLE
Tagging Policy - 1.0.0

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov#194]
So after conversations in the Tech group and meets. Following https://github.com/localgovdrupal/localgov/issues/139#issuecomment-827711077 In preparation to tagging a new version of the distro requiring and installing Drupal 9.

Decision: When code is accepted as _used_ _in_ _production_, even when the project itself is in 'beta', and the modules in development, we will use straight SemVer so production sites can manage their updates correctly. Modules then maintain _their_ major.minor versions independently as appropriate depending on changes made to them.

So policy: No change. 
Practice: tag 1.0.0 versions of modules.

_Originally posted by @ekes in https://github.com/localgovdrupal/localgov/issues/139#issuecomment-827711077_

- [x] #198 Finalize agreed policy
- [x] #199 Publish 
- [x] #200 Module-by-module tagging

**Comment by stephen-cox** [comment]
Done - sprint 2
