### ISSUE TITLE
Write CI pipeline for automating the db-dump import / upgrade test

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#196]
From #181 

- [ ] Write pipeline for automating the db-dump import / upgrade test
- [ ] Captruing database, storing db, working out how to import it, docker, Github CI etc. (Estimate: 8)

## Acceptance tests

 - t.b.c.

**Comment by stephen-cox** [comment]
Drupal core comes with a [script](https://git.drupalcode.org/project/drupal/-/blob/8.9.x/core/scripts/dump-database-d8-mysql.php) for capturing database dumps for use in tests. The basic workflow is to install Drupal and then capture the database. This can be then referenced in a test that inherits from [UpdatePathTestBase](https://api.drupal.org/api/drupal/core!tests!Drupal!FunctionalTests!Update!UpdatePathTestBase.php/class/UpdatePathTestBase/8.9.x).

Thunder's test for this is fairly basic: https://git.drupalcode.org/project/thunder/-/blob/6.1.x/tests/src/Functional/Thunder2UpdateTest.php#L51

One question I have is where to store the database. A basic install with no extra modules enabled and no content is a 228 Kb Gzip file. The standard place to store this sort of thing would be a `tests/fixtures` directory, but storing compressed SQL dumps in Git seems kinda wrong. Thunder stores the DB dumps in AWS and has a downloader for them.

As the DB dump is fairly small I'm tempted to store a DB in the LocalGov profile Git repo for now. 

@finnlewis @ekes @Adnan-cds @andybroomfield  Any thoughts on any of this?

**Comment by Adnan-cds** [comment]
> As the DB dump is fairly small I'm tempted to store a DB in the LocalGov profile Git repo for now.

Fine with me :)

**Comment by stephen-cox** [comment]
To create a DB dump for testing I've done the following in Lando

```bash
# Run Drush site install
lando drush si localgov --yes
# Enable modules
# Search API DB indexing causes issues with table names so skipping Directories and Events for now.
lando drush en localgov_demo --yes
# Set DB schema so there's an update to run.
# This won't be needed when using a D8 dump on the D9 codebase
lando drush sqlq "update key_value set value = 's:4:\"8900\";'  where name = 'system';"
# Dump database
lando ssh -c "cd web && php core/scripts/dump-database-d8-mysql.php | gzip > profiles/contrib/localgov/tests/fixtures/localgov-1.0.0.php.gz"
# Run update test
lando phpunit --filter=testUpdate
```

Pull request using this approach can be found here #209

**Comment by andybroomfield** [comment]
> As the DB dump is fairly small I'm tempted to store a DB in the LocalGov profile Git repo for now.

As long as it does not contain any personal or council information that should be ok.

**Comment by stephen-cox** [comment]
Tests for the PR for this are failing in Github CI, but not on my local, but I think it's worth waiting for all the default content updates to be merged before finishing this off (https://github.com/localgovdrupal/localgov_demo/issues/24, https://github.com/localgovdrupal/localgov_demo/pull/31)

**Comment by finnlewis** [comment]
Just merged the changes on localgov_demo into master and created a pull request to release ahead of a 1.0.1 tag: 
https://github.com/localgovdrupal/localgov_demo/pull/32
