### ISSUE TITLE
Update modules / fix tests for anything that breaks as part of a D8 > D9 upgrade.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#197]
From #181 

Fixing all the modules for Drupal 9. (Estimate: 13)
Reviewing all deprecated code (if we continue to test deprecated code in D0).
Estimating at least an hour or two per module.
Might be quickest to do this on a vanilla D9 install.

**Comment by finnlewis** [comment]
Deprecated code questions: do we still want to be checking for deprecations when we are on Drupal 9?

@markconroy @Adnan-cds @andybroomfield @ekes any thoughts:?

**Comment by finnlewis** [comment]
This will come after the tagging / release

**Comment by Adnan-cds** [comment]
> do we still want to be checking for deprecations when we are on Drupal 9?

I would say yes.  I am assuming this is not going to take a significant amount of time.

**Comment by stephen-cox** [comment]
I'm also inclined to keep the automated check for code deprecations, but this will mean there will be changes to every module to support Drupal 9 and modules will need to be updated as things are deprecated with Drupal 9 release. There will be more work maintaining modules, offset by an easier upgrade path to Drupal 10 later on.

**Comment by stephen-cox** [comment]
We now have PRs for all repos that need updating for Drupal D9.

To test them all together each repo now has a `d9` branch with all the fixes and dependencies in. Just checkout the `d9` branch in the [profile](https://github.com/localgovdrupal/localgov_project/tree/d9) and run `composer update`

**Comment by finnlewis** [comment]
This not quite done then @stephen-cox ?
