### ISSUE TITLE
Document policy for Release Notes (was: Publish and share the policy with the wider community)

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#199]

**Comment by finnlewis** [comment]
Still need to update this with the different 1.x 2.x branches and the release process

**Comment by finnlewis** [comment]
I've updated https://github.com/localgovdrupal/localgov/wiki/Versioning with a section about Drupal 8 and Drupal 9

Is that OK @ekes ?

**Comment by ekes** [comment]
I'll bump this one as I think it's good, but we now have a format for the release notes that should probably be added to that.

**Comment by stephen-cox** [comment]
Done - sprint 2
