### ISSUE TITLE
Paragraphs / components tidy up which paragraphs are available to services and subsites

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#213]
On services pages, it is possible to add components, reusable paragraphs.

On a default install, about **36 paragraph types** are available here. 

Originally I think this was meant to be a small set of re-usable components like contact details, coming from Croydon and Brighton's sites. 

@Adnan-cds @tom-steel @andybroomfield can you confirm what components were intended to be available on a service page? 

@msayoung and I are trying to finalise a range of demo content and aiming to have examples of paragrpahs where possible.

CC @ekes @stephen-cox

**Comment by Adnan-cds** [comment]
> can you confirm what components were intended to be available on a service page?

I am not aware of any such Paragraph list.  But Tom may know better.  Copying @tom-steel

**Comment by andybroomfield** [comment]
It's not a BHCC thing, I think it is Croydon.
So we need to decide to keep (if used).

**Comment by finnlewis** [comment]
At present, when creating a new component, all paragraphs are available.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/326588/117542969-b2c3ac00-b012-11eb-91f4-eab51190159c.png">

We should clarify what the suggested best practice content management / information architecture is here. We originally suggested that service pages should be text focussed and not have the ability to insert images and other rich media be default. So restricting the paragraph components here would make sense, out of the box at least. 

People can always change this later if they really want to go wild.

The lcaogov_theme also does yet not support most of the paragaphs that come with localgov_paragraphs.

**Comment by andybroomfield** [comment]
https://github.com/localgovdrupal/localgov_services/issues/46

**Comment by andybroomfield** [comment]
Still looks like a live issue.

**Comment by andybroomfield** [comment]
Possible duplicate at localgovdrupal/localgov_paragraphs#254 which has more current discussion.
This also talks about subsides, but generally that should contain almost all paragraphs except for functional ones.
I suggest separate issue there if need be.
