### ISSUE TITLE
Create a localgov_basetheme base theme

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#22]
The Croydon theme is probably the best starting point for this. 

Initially propose to copy the Croydon theme as a starting point.

Develop this into a base theme that works for the LocalGov distribution, with a starterkit folder to help generate a child theme.

Options for compiling scss will need to be explored.

**Comment by stephen-cox** [comment]
There is a base theme: https://github.com/localgovdrupal/localgov_theme
