### ISSUE TITLE
Theory of change: Decide on activities > roadmap

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#220]
@finnlewis  and @willguv to make a start on :

- [ ] map activities from the TOC int the resource plan
- [ ] map activities from the TOC into the sprint board

**Comment by willguv** [comment]
Project arc taking shape at https://docs.google.com/spreadsheets/d/1DWt5NM9ahP0OaOixPvj_TPdH6RSc0mRzY8bn8HLUrSU/edit?usp=sharing

**Comment by stephen-cox** [comment]
Done - sprint 3
