### ISSUE TITLE
Decide on strategy for shop window website

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#221]

**Comment by finnlewis** [comment]
@willguv and I just had a conversation about this.

We propose:

## Option 1 - (Proposed)

1. To use the https://localgovdrupal.org/ site for promotional shop window content for the time being.
2. To move all the docs into a section 
3. To have a more general top level menu structure / IA speaking to the new councils / new people. 
4. We will move this content to a more all singing all dancing site towards the end of the project.

Will generated notes on the proposed information architecture here https://docs.google.com/document/d/1RELazk4vEJVk6ITXaF5fNpTOv4sXavsbP5gi47Aq5Jk/edit#

## Option 2 - (Alternative)

The other option is to spin up a new Vuepress site (or similar) following the same approach, separating the content for shop window promotional audiences from the documentation. This will allow the existing documentation to stay as.

What do others think?

@markconroy @msayoung @richard-s-rowley @ekes @stephen-cox @danchamp @andybroomfield @Adnan-cds @tom-steel

**Comment by willguv** [comment]
Thanks @finnlewis. To add, there's a couple of reasons why I don't think we ought to jump to an all singing and dancing site now:

- It's a distraction from our current goals (moving to Drupal 9, refactoring the default theme, establishing the project arc, starting working groups for specific product features)

- Our research hasn't started yet. We ought to speak to some decision makers, product managers, content designers before considering what a promo site should do

**Comment by finnlewis** [comment]
No other thoughts so far, so let's assume we are going with option 1.

**Comment by MichaelDCR** [comment]
think this can be closed?

**Comment by finnlewis** [comment]
Yes, good call @MichaelDCR !
