### ISSUE TITLE
Documentation for the services content types.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#224]
In sprint planning., we discussed the highest priority documentation for content designers is the services content types. 

@benhillsjones has some good stuff on th Croydon design system which we could use for starter?

Tasks

- [ ] Content designer
- [ ] Technical
- [ ] Background

**Comment by msayoung** [comment]
Started on PR: https://github.com/localgovdrupal/docs/pull/48

**Comment by willguv** [comment]
I commented on https://github.com/localgovdrupal/docs/pull/48

**Comment by stephen-cox** [comment]
Done - sprint 5
