### ISSUE TITLE
Working groups - identify the working groups needed for the beta phase

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#232]
Now that we have a beta phase project in flight, with 11 councils and growing, the need to divide the work into smaller groups is increasingly important. 

We will define what a working group is , how they work separately. 

Once that is done, we need to prioritise which working groups we need. 

@willguv and I spent some time reviewing the the immediate needs and identified:

1. Targeted alert banners
2. Content publishing workflow
3. Microsites

This issue is to explore this a little more and confirm our priorities.

**Comment by willguv** [comment]
Thanks @finnlewis we also suggested Forms and Subsites as areas worthy of working groups - councils have expressed a need, and also supports the savings case we made during Alpha
