### ISSUE TITLE
Drupal 9 upgrade documentation

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov#235]
Documentation on D8 to D9 upgrade here: https://github.com/localgovdrupal/localgov/wiki/Upgrading-from-Drupal-8-to-9

**Comment by stephen-cox** [comment]
@ekes @finn @willguv I have added some documentation on how to upgrade a LocalGov site from D8 to D9 here: https://github.com/localgovdrupal/localgov/wiki/Upgrading-from-Drupal-8-to-9

Please let me know if it looks okay to you. If so it can be passed to councils that might actually do an upgrade for further review.

**Comment by stephen-cox** [comment]
@danchamp Passing to for feedback on the D9 upgrade docs

**Comment by danchamp** [comment]
@stephen-cox I've just completed upgrading a local London Councils install from D8 to D9 following this guide. No serious issues, site is now running on D9 and operating as expected. We've got a single contrib module that isn't D9 ready that I need to sort, then we'll be ready to upgrade the beta site for real.

Non-LGD issues I came across:

- One contrib module that has no D9 version available (found with Upgrade Status)
- A custom LC module that didn't have a core_version_requirement key in its info.yml (found with Upgrade Status)
- A reference to `path.alias_manager` in our custom theme - [changed](https://www.drupal.org/node/3092086) to `path_alias.manager` for D9

This was the only snag I hit with composer update after following the guide:

```  Problem 1
    - Installation request for localgovdrupal/localgov 2.x-dev -> satisfiable by localgovdrupal/localgov[2.x-dev].
    - localgovdrupal/localgov 2.x-dev requires localgovdrupal/localgov_events ~2.0.0 -> satisfiable by localgovdrupal/localgov_events[2.0.0] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Installation request for localgovdrupal/localgov_events ^1.0@alpha -> satisfiable by localgovdrupal/localgov_events[1.0.0, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-alpha3].
    - Can only install one of: drupal/date_recur_modular[3.x-dev, 2.x-dev].
    - Can only install one of: drupal/date_recur_modular[3.0.0-rc1, 2.x-dev].
    - Can only install one of: drupal/date_recur_modular[3.0.0, 2.x-dev].
    - Conclusion: install drupal/date_recur_modular 2.x-dev
    - Installation request for drupal/date_recur_modular ^3.0 -> satisfiable by drupal/date_recur_modular[3.x-dev, 3.0.0-rc1, 3.0.0].
```

So my composer.json had a requirement for localgovdrupal/localgov_events ^1.0@alpha - presumably running composer update before doing anything else would have resolved this?

**Comment by stephen-cox** [comment]
Thanks for reviewing @danchamp.

You don't need a reference to locagov_events in your main composer.json file as this is already included in the profiles composer.json. If the main file includes a reference to 1.0 and the profile to 2.0 then you're going to hit this problem. Removing the reference from the main one should fix it.

Do you think the documentation should be updated for this?

**Comment by danchamp** [comment]
@stephen-cox Looking back at the commit history I think we uninstalled events for some reason, then added it back with composer, which is why it had a separate entry in composer.json.

So no, I don't think there's any need to update documentation, it was just an edge case and easily fixed.
