### ISSUE TITLE
LocalGov 2.0.0 release

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov#236]
Once we have all the LocalGov 2.x stuff working we should do a 2.0.0 release so people who start with Drupal 9 get stable tags rather than just 2.x-dev changes.

**Comment by stephen-cox** [comment]
Need to release 2.0.0 of:


- [x] localgovdrupal/localgov_core
- [x] localgovdrupal/localgov_directories
- [x] localgovdrupal/localgov_events
- [x] localgovdrupal/localgov_guides
- [x] localgovdrupal/localgov_paragraphs
- [x] localgovdrupal/localgov_services
- [x] localgovdrupal/localgov_step_by_step
- [x] localgovdrupal/localgov_subsites
- [x] localgovdrupal/localgov
- [x] localgovdrupal/localgov_project

**Comment by finnlewis** [comment]
Just to note, for most of these, there is not a release-2.x branch yet. 
So we'll be creating the release-2.x branch and tagging at 2.0.0. 
No pull requests needed.

**Comment by finnlewis** [comment]
https://github.com/localgovdrupal/localgov_guides/releases/tag/2.0.0

**Comment by finnlewis** [comment]
https://github.com/localgovdrupal/localgov_paragraphs/releases/tag/2.0.0

**Comment by finnlewis** [comment]
https://github.com/localgovdrupal/localgov_services/releases/tag/2.0.0

**Comment by finnlewis** [comment]
https://github.com/localgovdrupal/localgov_subsites/releases/tag/2.0.0

**Comment by finnlewis** [comment]
https://github.com/localgovdrupal/localgov_events/releases/tag/2.0.0

**Comment by finnlewis** [comment]
https://github.com/localgovdrupal/localgov_core/releases/tag/2.0.0
