### ISSUE TITLE
Update documentation for 2.0.0 release

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov#245]
Now we have a 2.0.0 release the profiles documentation is out of date: https://github.com/localgovdrupal/localgov/blob/2.x/README.md

**Comment by finnlewis** [comment]
Note: perhaps add docs about Docker desktop and how to use without.

**Comment by finnlewis** [comment]
@j4-m this is on my list of things to look at. Did you make any suggested changes to the main README already?

**Comment by finnlewis** [comment]
Yo yo @stephen-cox - just started a PR with some minor changes to the README, on this branch: https://github.com/localgovdrupal/localgov/tree/feature/245-update-readme

Removing the `--stability dev` from the composer command, is that right? 

https://github.com/localgovdrupal/localgov/pull/391/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R35

Happy to hear your thoughts on what else we might want to improve at this juncture.
