### ISSUE TITLE
Research: finalise survey and publish

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#251]
Draft survey available here; https://docs.google.com/forms/d/1InLOQIoPfTLzE5glvEvCYwsDb2nntM05VewsutX8H9E/edit

**Comment by msayoung** [comment]
I've done as much as I can right now. https://docs.google.com/forms/d/e/1FAIpQLSdPtKci39u_KFdsms7dlVPjnpF7DBF5Rs04Kihj2PAKOJWmXQ/formResponse

I believe we still need 

- [ ] details of the Prize Draw (including when the survey will run to) @willguv 
- [ ] an estimate of how long it will take, added to the intro 
- [ ] a final check 

@AlexandraClark83 @willguv @finnlewis

**Comment by willguv** [comment]
Still waiting to hear from Cumbria so will buy two £50 John Lewis vouchers at my risk. One voucher for this survey, and the other one for future survey? @msayoung 

Leave open for next sprint? Shall we finalise everything on Weds?

**Comment by msayoung** [comment]
@willguv we could be non-specific about the amount for now. 
do you have someone in mind to be a guinea pig to fill it out? Could you pass it to them today? If not, I could ask Neil. 
It would be good to have it ready to send out for next sprint.

**Comment by willguv** [comment]
@msayoung I was going to ask Neil as well, so do you want to ask him (trying to stay off phone today!)

**Comment by msayoung** [comment]
I'm happy to, but I don't have his new email address. Can you DM it to me?

**Comment by finnlewis** [comment]
I'll test it this evening and time myself.

**Comment by finnlewis** [comment]
Neil is also on Twitter - I'm sure he wouldn't mind a Dm there.

**Comment by finnlewis** [comment]
I tested this last night, tweaked the phrasing of a couple of questions and changed the wording on the final question to specifcally ask if people are up for a follow up interview, following conversation with @AlexandraClark83 on Slack. 

I'm happy with the survey as it stands. 

How about you @AlexandraClark83  @msayoung @willguv ?

**Comment by AlexandraClark83** [comment]
Hi Finn,

I have a couple of minor things that I’d like to change, but happy to discuss on the call if that was the plan?

One of the outstanding ones from our last conversation is the consistency around the wording of "Current website” "Current System” and "Web publishing platform” I don’t know which one is best, but let’s stick to one.

Speak in a bit.

Thanks,
Alex

-------

Alexandra Clark,
Founder & Consultant

Telltale Research
www.telltaleresearch.com<http://www.telltaleresearch.com>

Mobile: +44(0)7900665543
LinkedIn<https://www.linkedin.com/in/alexandra-clark-34685b4/> | Twitter<https://twitter.com/telltaleACRC> | Instagram<https://www.instagram.com/telltaleresearch/>

Subscribe to our newsletter<http://eepurl.com/hfSF9D> to keep up to date with our latest research and Telltale Stories video<https://www.youtube.com/channel/UCqcXmPogXDvhEPxE5CxIiMg> & podcast<https://open.spotify.com/show/5I9TKkgiaYfpx67p2fhyOx> -interviews with pioneers across business, culture & the environment

***@***.******@***.***

On 8 Jun 2021, at 07:28, Finn Lewis ***@***.******@***.***>> wrote:



I tested this last night, tweaked the phrasing of a couple of questions and changed the wording on the final question to specifcally ask if people are up for a follow up interview, following conversation with @AlexandraClark83<https://github.com/AlexandraClark83> on Slack.

I'm happy with the survey as it stands.

How about you @AlexandraClark83<https://github.com/AlexandraClark83> @msayoung<https://github.com/msayoung> @willguv<https://github.com/willguv> ?

**Comment by willguv** [comment]
@msayoung @AlexandraClark83 I've tightened up the intro a bit, and added our new email address (hello@localgovdrupal.org)

Reading the rest now. Really like it

**Comment by willguv** [comment]
I'm changing all mentions of "system" to "publishing platform"

Think using "website" and "publishing platform" together in the same survey is OK, but we can discuss at review

**Comment by AlexandraClark83** [comment]
Great, thanks. I’ve changed the last question slightly and corrected a typo.

On page 6. We have "Would your council consider using LocalGov Drupal to build its public facing website?” After that we could add in an open ended “Please tell us why they would or wouldn’t”?  At the moment we only ask why they wouldn’t, but we cold potentially learn something by asking why they would.

Thanks,
Alex

-------

Alexandra Clark,
Founder & Consultant

Telltale Research
www.telltaleresearch.com<http://www.telltaleresearch.com>

Mobile: +44(0)7900665543
LinkedIn<https://www.linkedin.com/in/alexandra-clark-34685b4/> | Twitter<https://twitter.com/telltaleACRC> | Instagram<https://www.instagram.com/telltaleresearch/>

Subscribe to our newsletter<http://eepurl.com/hfSF9D> to keep up to date with our latest research and Telltale Stories video<https://www.youtube.com/channel/UCqcXmPogXDvhEPxE5CxIiMg> & podcast<https://open.spotify.com/show/5I9TKkgiaYfpx67p2fhyOx> -interviews with pioneers across business, culture & the environment

***@***.******@***.***

On 8 Jun 2021, at 10:16, Will Callaghan ***@***.******@***.***>> wrote:



@msayoung<https://github.com/msayoung> @AlexandraClark83<https://github.com/AlexandraClark83> I've tightened up the intro a bit, and added our new email address ***@***.******@***.***>)

Reading the rest now. Really like it

**Comment by AlexandraClark83** [comment]
Great, thanks. Yes, it might just cause some confusion if it is not clear what the difference is.

-------

Alexandra Clark,
Founder & Consultant

Telltale Research
www.telltaleresearch.com<http://www.telltaleresearch.com>

Mobile: +44(0)7900665543
LinkedIn<https://www.linkedin.com/in/alexandra-clark-34685b4/> | Twitter<https://twitter.com/telltaleACRC> | Instagram<https://www.instagram.com/telltaleresearch/>

Subscribe to our newsletter<http://eepurl.com/hfSF9D> to keep up to date with our latest research and Telltale Stories video<https://www.youtube.com/channel/UCqcXmPogXDvhEPxE5CxIiMg> & podcast<https://open.spotify.com/show/5I9TKkgiaYfpx67p2fhyOx> -interviews with pioneers across business, culture & the environment

***@***.******@***.***

On 8 Jun 2021, at 10:22, Will Callaghan ***@***.******@***.***>> wrote:



I'm changing all mentions of "system" to "publishing platform"

Think using "website" and "publishing platform" together in the same survey is OK, but we can discuss at review

**Comment by willguv** [comment]
Can we run through the first couple of questions in section 4 as not sure if they quite work - thanks

We could put the following questions together in their own section as they relate a council that's going to upgrade. And say to people they can skip it if they're not upgrading

- Do you plan to rebuild or significantly redevelop your current website in the near future? 
- If so, what is the main driver for the upgrade?
- If you are planning to rebuild, what web publishing platform are you considering?
- Approximately, how much do you expect your next redevelopment to cost?
- Is there anything else you'd like to add?

And maybe put these in a different section that's about upgrades in general

- How important are each of the following criteria when assessing a web publishing platform? 
- Are there any other criteria that are important?
- What features are most important to you?
- What would deter you from adopting a web publishing platform?
- How many years do you expect a council website to last?

**Comment by willguv** [comment]
On 

Would your council consider using LocalGov Drupal to build its public facing website?	
What would prevent you / your organisation from adopting LocalGov Drupal?

What do you answer if you're already using it?

**Comment by willguv** [comment]
@AlexandraClark83 @msayoung other than the points above which we can go through at 5pm, everything else is great!

**Comment by finnlewis** [comment]
This is done, I think! :)
