### ISSUE TITLE
Testing with MySQL vs SQLite

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#253]
This issue is to discuss moving from SQLite to MySQL for the Gihub CI testing.

We moved to SQLite for speed, but this is now causing problems with tests.

**Comment by finnlewis** [comment]
@stephen-cox 

What is involved in moving to MySQL for running tests? 

I'm happy to give it a go if you point me in the right direction.

(CC @Adnan-cds @ekes @andybroomfield )

**Comment by stephen-cox** [comment]
To test using MySQL you can add a MySQL / MariaDB service to the [docker-compose.yml](https://github.com/localgovdrupal/drupal-container/blob/php7.4/docker-compose.yml) file in the Drupal container.

You'll also need to update the `sed` command that [sets the database connection details](https://github.com/localgovdrupal/drupal-container/blob/1ec26db9f9ff4dc6380a6a46a9d402dd925f0587/run-tests.sh#L31).

**Comment by stephen-cox** [comment]
@Adnan-cds @finnlewis I have tun a test of the different methods of running Github actions. 

The timings were:
 - Paratest and SQLite: 14m 1s
 - Paratest and MariaDB: 15m 10s
 - PHPUnit and SLQite: 28m 56s
 - PHPUnit and MariaDB: 29m 38s 

You can see the test run here: https://github.com/localgovdrupal/drupal-container/runs/3746410992?check_suite_focus=true

Using MariaDB and Paratest is only a minute or two slower than using SQLite and Paratest, so I don't think that moving to testing with MariaDB is going to make a noticeable difference and will unblock https://github.com/localgovdrupal/localgov_demo/pull/33.

Unless I hear any objections I will push ahead with this.

**Comment by finnlewis** [comment]
Wow, thanks @stephen-cox , looks good to me, let's do this!
