### ISSUE TITLE
DNS changes

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#254]
I own localgovdrupal.org, and previously pointed nameservers to following:

dns1.p06.nsone.net	
dns2.p06.nsone.net	
dns3.p06.nsone.net	
dns4.p06.nsone.net

(I may have done this at Pauls' request to point to the docs site)

## Subdomains

We need to solve this mystery in order to create subdomains for the demo and testing environments

## Email

I'm setting up hello@localgovdrupal.org (and other email addresses as required) and need to add the following somewhere

TXT name
@‎ (or skip if not supported by provider)

TXT value
MS=ms72758116

TTL
‎3600‎ (or your provider default)

**Comment by willguv** [comment]
Hi @stephen-cox here's what I know on the DNS front

**Comment by stephen-cox** [comment]
Those name servers looks to be managed by https://ns1.com/, while the domain seems to be registered with https://www.assetict.com/. Do you have a login for either of these DNS control panels?

If you have access the NS1 then we can just set new DNS records. If you have a login for Asset ICT then we'll need to change the nameservers away from NS1 and add all the required DNS records.

**Comment by willguv** [comment]
@stephen-cox I've never heard of ns1.com - think it's something that was done for this project

I can access Asset ICT. Can you let me know what you'd like as the nameservers and I'll get this done

Thanks

**Comment by stephen-cox** [comment]
Can you set the nameservers to use the default ones provided by Asset ICT?

If so it's easiest to use them. If not then we could use the nameservers Agile Collective use. These are managed by Webarch and configured entirely through git. Alternatively we could transfer the domain to a provider who has a nice web interface and DNS servers. I like Gandi for this: https://www.gandi.net/

**Comment by willguv** [comment]
I can revert to the Asset ICT defaults, no problem

Do I need to add an entry to maintain the docs site at its current localgovdrupal.org address?

**Comment by stephen-cox** [comment]
The localgovdrupal.org site is using Netlify and from this (https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/#configure-an-apex-domain) it looks to me like you need to add the following DNS record

A record: localgovdrupal.org. => 75.2.60.5

For demo and testing sites please add the following:

CNAME record: demo.localgovdrupal.org. => localgovdrupal.agile.coop
CNAME record: test.localgovdrupal.org. => localgovdrupal.agile.coop

The demo site can then become something we can show off and the test site something we're happy to reinstall every now again.

**Comment by willguv** [comment]
@stephen-cox thanks, I'll get this done

**Comment by willguv** [comment]
Hi @stephen-cox these are all added now. I’m getting Apache default pages for test and demo

**Comment by stephen-cox** [comment]
Hi @willguv 

We now have a demo site which is currently running LocaGov 2.0.0 at: https://demo.localgovdrupal.org/ and a testing site for the bleeding edge and sprint reviews at: https://test.localgovdrupal.org/

**Comment by willguv** [comment]
Great! Thank you, will close this
