### ISSUE TITLE
Editable services menu

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#257]
In Croydon and Lambeth, clicking on "Services" in the header opens a mega menu with services listed

This area is fully editable by a content designer

- Links can be created, edited and deleted
- Links can be reordered as needed

We need to confirm what the distribution offers. If nothing, we should decided on an MVP for a future sprint.

**Comment by msayoung** [comment]
There is one in the demo module, don't think it is in the default install.

**Comment by msayoung** [comment]
It is in the install profile.
