### ISSUE TITLE
Documentation structure: improve the structure of the docs site

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#265]

**Comment by msayoung** [comment]
For now, given there are other conversations about the rest of the site, I propose we just replace the current section called Config with a section called Features. 

Each feature will have a section:
1. Introduction
2. Content designer docs (based on Croydon's) https://lbc-cdn-corpwebsite-p2.azureedge.net/design-and-content-guidelines/patterns/content-types/directories
3. Technical docs (based on https://www.drupal.org/docs/develop/documenting-your-project/readme-template )
4. Background

More detail of each section here: https://docs.google.com/document/d/1rA--FEte_Qc8SGMKul3JXNRgKEXfCpSmxKLCIHb0odc/edit# 


Any thoughts? 
@finnlewis @ekes @danchamp @willguv 

FYI: Joeri has been doing some great work documenting the Technical bit of the [Alert banners](https://docs.google.com/document/d/13qDsA1N_upqCG_g8cQUa0UvMKe1-NVSAahxWFjDSMIA/edit)

**Comment by danchamp** [comment]
@msayoung This looks really good to me, very happy to proceed with this structure.

**Comment by finnlewis** [comment]
Looks good to me too @msayoung !

If we're covering some things in Readme files, we can just cross linked where needed. If some bits might want to be duplicated, I don't see being a huge problem.

**Comment by willguv** [comment]
@msayoung makes perfect sense, thank you!

**Comment by msayoung** [comment]
I've moved things around and put in some content to demo - you can see https://deploy-preview-50--trusting-noyce-aebebc.netlify.app/features/ 

The section previously known as Config, now lives in General : https://deploy-preview-50--trusting-noyce-aebebc.netlify.app/features/general/ 

I've added in @jpoesen 's technical  documentation on alert banners https://deploy-preview-50--trusting-noyce-aebebc.netlify.app/features/alert-banner/technical.html 

and the content I stole from Croydon about Services for Content Designers: https://deploy-preview-50--trusting-noyce-aebebc.netlify.app/features/services/content-design.html

My only concern is how much there is to do, but generally are we happy with this? 

PR here https://github.com/localgovdrupal/docs/pull/50

**Comment by danchamp** [comment]
> My only concern is how much there is to do, but generally are we happy with this?

Very happy with this, nice work @msayoung!

Lots to do, this *should* be largely a one-time effort to get it populated, with updates being light thereafter? I'd be happy to be assigned a content type to work through.

**Comment by stephen-cox** [comment]
Done - sprint 4
