### ISSUE TITLE
[NOT DOING] Short url for survey

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#268]
I'm giving lots of presentations at the moment (like the Digital Leaders CLG chat this Friday) and it would be really handy to have a short/ easy to remember url for surveys

The current survey is at https://forms.gle/guPKxbKt9QkcLXrM6

Could we set up localgovdrupal.org/survey and repoint it?

**Comment by stephen-cox** [comment]
Done - sprint 4
