### ISSUE TITLE
Git branch naming conventions - baseline guidance.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#269]
We've not written down our git branch naming conventions yet, but they have been emerging. 

So here's a starter on the Wiki: https://github.com/localgovdrupal/localgov/wiki/Git-branch-naming-conventions

Happy to have further discussion and amend.

Any comments @andybroomfield @Adnan-cds @cjstevens78 @markconroy @msayoung @stephen-cox @ekes @danchamp ? 

Here's the chat from Slack: 

> 
> Finn (Agile Collective)  4:21 PM
> @ekes @Dan Champion (London Councils) I've noticed we've got branch names like feature/2.x/30-default-documentation now - including the major version branch in the feature branch name. Do we have this convention written down anywhere yet? If not, I'm just creating a wiki page.
> 
> ekes  4:37 PM
> Not documented I just started doing it when I had two branches for the same feature; and have just continued since.
> 
> Stephen Cox (Agile)  4:39 PM
> I have been adding -1.x or -2.x to the end of branches - probably makes sense to standardise this a little (edited) 
> 
> Finn (Agile Collective)  4:40 PM
> Indeed - I think this pattern looks to have been working for @Dan Champion (London Councils) and @ekes:
> https://github.com/localgovdrupal/localgov_core/tree/feature/1.x/85-linkit-email-matcher
> 4:40
> https://github.com/localgovdrupal/localgov_core/tree/feature/2.x/30-default-documentation
> 4:40
> Makes it quite quick to read
> 4:41
> You happy to go with that @Stephen Cox (Agile)?
> 
> Stephen Cox (Agile)  4:42 PM
> Something doesn't look right to me with that - but I'm sure I can some to terms with it :wink:
> 
> Finn (Agile Collective)  4:42 PM
> I have also see /fix/ and /hotfix/ prefixes....
> 4:42
> Maybe @Andy Broomfield (BHCC) are you a fan of /fix/73-a-fix-for-something
> 4:43
> and if so, what suggests a /feature and what /fix or (does this stem from GitFlow?)
> 
> Stephen Cox (Agile)  4:45 PM
> As long as we can understand what's on a branch then I don't see a serious issue with how they're named. The thing that bugs me more is all the old and stale branches hanging around. It would be good to have some shared understanding of when to delete a branch (edited) 
> 
> Finn (Agile Collective)  4:50 PM
> When it is merged, delete it for sure right? But what about when it is not? Are you thinking of a cut-off for stale branch pruning @Stephen Cox (Agile)?
> 
> 
> 4 replies
> Last reply today at 5:00 PMView thread
> 
> Finn (Agile Collective)  4:51 PM
> How's this for starters @Dan Champion (London Councils) @ekes @Stephen Cox (Agile) @Andy Broomfield (BHCC) @Maria (Agile Collective) @Mark Conroy (Annertech) ? https://github.com/localgovdrupal/localgov/wiki/Git-branch-naming-conventions
> 
> ekes  5:00 PM
> If people are happy with that format. I'd note the branch name doesn't start with a / though.
> 
> Andy Broomfield (BHCC)  5:20 PM
> @Finn (Agile Collective) BHCC uses fix/ and feature/ however thats with single codebase. I think we're going to now need to move to something that includes 1.x and 2.x to indicate target. Is using multiple slashes a problem (eg. fix/1.x/99-fix-problem) so maybe fix/1.x--99-fix-problem?
> 
> 4 replies
> Last reply today at 5:24 PMView thread
> 
> Andy Broomfield (BHCC)  5:22 PM
> Or to complicate things more, make the target part of the fix/feature prefix eg. fix-1.x/99-fix-problem
> 5:22
> Making the target base prominent (know where to test this against)
> 
> Finn (Agile Collective)  5:24 PM
> under what circumstances do you use /fix rather than /feature @Andy Broomfield (BHCC) and why?
> 
> Andy Broomfield (BHCC)  5:33 PM
> @Finn (Agile Collective) fix/ means pure bug fix (something is broken) feature/ means building new functionality (which might incorporate a bugfix).
> 5:34
> Really these things are subjective, however if you can say substantially this is about fixing something that is broken, using fix/ just communicates that.
> 
> Finn (Agile Collective)  5:35 PM
> sounds perfectly reasonable @Andy Broomfield (BHCC) :slightly_smiling_face:
>

**Comment by danchamp** [comment]
@finnlewis An agreed standard would be good. I've no preference for the actual format so long as it's easy to parse as  @stephen-cox said.

I've used both fix and feature as prefixes, agreeing with the definition from @andybroomfield above.

I'd be happy with the proposal on the wiki.

**Comment by markconroy** [comment]
I agree with Dan's thoughts. Happy to go with this.
