### ISSUE TITLE
Use core_version_requirement key for modules

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#27]
Just testing the unit test functionality documented in #26.
Came accross this error: `"core_version_requirement" property is missing in the info.yml file`

Not fatal, though as Drupal 9 is near, best to start by using that for all future modules.
See:
https://www.drupal.org/node/3070687
eg. Replace `core: 8.x` with `core_version_requirement: ^8.8 || ^9`

**Comment by finnlewis** [comment]
Hey @andybroomfield 

Thanks for that. I've updated both  info.yml files that were reported by phpcs, it should now report nothing! 

Seems to work fine now. 

Cheers,

Finn

**Comment by Adnan-cds** [comment]
Should we close this now?

FAO @finnlewis @andybroomfield

**Comment by andybroomfield** [comment]
@Adnan-cds Assume yes if all modules use core_version_requirement property now.
