### ISSUE TITLE
Research : confirm developer interviews target list

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#275]

**Comment by willguv** [comment]
@finnlewis please give us your view on the following names. We've suggested 5 interviewees for each of the existing user groups (devs, content designers, product managers)

- Adnan Muhammad
- Andy Broomfield
- Paula Almerich (Front end at Zoocha/ Westminster)
- Dan Champion
- Justine Pocock

**Comment by willguv** [comment]
@finnlewis please let me know if you’re happy with this list above. I’ll then check everyone is OK to be interviewed

**Comment by finnlewis** [comment]
If we're limiting it initially to 5 interviews, does it make sense to interview Adnan and Andy rather than other newbies? Don't get me wrong, I'd love to hear Andy and Adnan's deeper thoughts and feelings on the project. However, they are both developers who instigated the project and have taken part in lots of retros, rather than developers who have joined the project with a new council. I think we want to focus on the later in terms of understanding the ups and downs of onboarding, comms, documentation, etc. (disclaimer: I've not actually read the questions yet). 

But I also don't want to be the person that stops us interviewing Andy and Adnan! Maybe can we do 5 interviews plus Adnan and Andy? 7 total? That would then perhaps be less of a bias towards core team developers. 

Thoughts @willguv ?

**Comment by finnlewis** [comment]
If so, maybe 
 - someone from Waltham Forest, 
 - someone from Microserve, 
 - maybe Tanc (from Agile Collective) who came in blind on the Lambeth project?

**Comment by willguv** [comment]
Thanks for thoughts Finn. I was thinking a mix of established and new people for this set of interviews, but will raise at the working group on Monday - see what Alex and @msayoung reckon

**Comment by finnlewis** [comment]
Just chatted through this with @willguv - we're reaching out to a few others and will finalise at the meeting this afternoon.

**Comment by willguv** [comment]
We agreed in the Research working group:

Justine
Paula
Andy
Jack
[one more recently joined - let's think about who this might be]

I'm intro-ing them to @msayoung as I write this
