### ISSUE TITLE
Research: questions for phase 2

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#276]
Start preparing questions for the phase 2 interview questions.

**Comment by finnlewis** [comment]
Here are some questions: 

https://docs.google.com/document/d/1U5rHy30Sl_5qDFzk7KhSGfzBqsuBOb6jKRGLNjd3j9I/edit

**Comment by finnlewis** [comment]
Hi @msayoung and @AlexandraClark83 - this one is assigned to me. 
I've read throught the questions linked to above and it all sounds good to me. 
Is there anything specific you would like me to read more critically and help to improve? 
Cheers,
Finn

**Comment by msayoung** [comment]
Thanks @finnlewis 
We've all reviewed and are happy with it for now. marking done
