### ISSUE TITLE
Update blocks across all modules to use localgov_base theme

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov#288]
Before we can enable the new localgov_base theme during a site install we need to ensure that all blocks will be positioned correctly be default.

**Comment by markconroy** [comment]
All blocks will be in the same regions, so we just need to update the theme they apply to from `localgov_theme` to `localgov_base`.

The only exception is the "Tabs" block, which should be moved to the new "Tabs" region.

**Comment by finnlewis** [comment]
I see, so we will need to go through all the block config in each project and either change the placement or add another config/optional for blocks depending on the localgov_base theme

**Comment by stephen-cox** [comment]
Done - sprint 8
