### ISSUE TITLE
Get localgov-core on packagist

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#3]

**Comment by stephen-cox** [comment]
Adding repos to packagist is very easy - the main issue is ensuring the composer.json file is okay and the name is correct. All modules and packages should be named like `localgovdrupal/localgov_something_or_other`.

It's just a matter of creating an account and submitting the package. Linking your account with Github ensures that changes are automatically submitted to Packagist.

https://packagist.org/explore/?query=localgovdrupal

**Comment by stephen-cox** [comment]
All seems to be working. Closing
