### ISSUE TITLE
Slide deck for 3rd anniversary of Local Digital Declaration

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#304]
Deck here
https://docs.google.com/presentation/d/1nROFdznn8Xz3-apDMdqRl_53y0Bx_UxY2QrltmLJTq8/edit?usp=sharing

Invite here
https://www.eventbrite.co.uk/e/celebrating-three-years-of-the-local-digital-declaration-tickets-161901841767

**Comment by stephen-cox** [comment]
Done - sprint 6
