### ISSUE TITLE
Discovery - content design onboarding meeting with Haringey

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#307]
- [ ] Schedule meeting with Ben, Tim, Haringey colleagues
- [ ] Ben to produce a script for the session, and run through
- [ ] Answer Haringey content design questions
- [ ] Record the session
- [ ] Collect learnings from the session to inform onboarding materials

**Comment by finnlewis** [comment]
Woops! I closed it by accident, sorry @willguv

**Comment by stephen-cox** [comment]
Done - sprint 7
