### ISSUE TITLE
LocalGov Base theme - set as default theme in profile.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#317]
On a default install, the default theme should be localgov_base theme.

- [x] Do non-beta release (https://github.com/localgovdrupal/localgov_base/issues/119)
- [x] Update block settings for other modules (potentially tedious - with a load of PRs)
- [x] Set localgov_base as the default theme in the install profile.

**Comment by stephen-cox** [comment]
There's an issue with the theme (localgovdrupal/localgov_base#122) and a proposed fix for it (localgovdrupal/localgov_base#123) that needs to be resolved before the new Base theme can be set as default.

**Comment by stephen-cox** [comment]
Installing a new site with the new theme enabled by default displays an empty error status message on all pages apart from the search results page. This is because the header search field is marked as required: https://github.com/localgovdrupal/localgov_search/issues/6
