### ISSUE TITLE
LocalGov News - finalise addition to default install

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#318]
Mark mentioned that the way the facets is placed in localgov_news is different from others. Need to check this.

@danchamp anything else we need to think about?

**Comment by finnlewis** [comment]
@danchamp just jumping on this one.

@ekes is looking at this https://github.com/localgovdrupal/localgov_news/pull/43/checks?check_run_id=3566303459 

Once we've got that merged, we can add the localgov_news project to the default install.

**Comment by ekes** [comment]
https://github.com/localgovdrupal/localgov/commit/16e3c0ccf999e4bbc485129db339c1865b050ebd
