### ISSUE TITLE
Arrange a workshop about legal entity for the future of LocalGov Drupal.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#319]
Issue to remind us to set up and run a workshop to confirm our preferred legal entity for the future governance and sustainability of the LocalGov Drupal project and community.

**Comment by finnlewis** [comment]
@aaronhirtenstein has booked Mark Simmonds to join our steering group meeting on Monday 13th September from 12:00 - 13.30.

I've updated the invitation and will try to encourage all the council people on the steering group to be present. 

CC @willguv

**Comment by finnlewis** [comment]
@aaronhirtenstein I wonder if there are any questions that we might want to share ahead of the session to allow people to mull them over before we meet.

**Comment by aaronhirtenstein** [comment]
Yep I can share the Miro board that Mark has created and preface that with some questions / things to consider.

**Comment by stephen-cox** [comment]
Done - sprint 8
