### ISSUE TITLE
LocalGov Paragraphs - module to hold paragraph components

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#32]
To include: 

- configuration for base level paragraph types
- contact card
- big bang announcement
- text
- image
- quote

There are still conversations to be had about whether paragraphs are used outside of campaigns.  We'll need to confirm other paragraph types required within LocalGove Core.

**Comment by stephen-cox** [comment]
Paragraphs items and the number used on the Croydon site:
```
mysql> select count(id), type from paragraphs_item group by type;
+-----------+--------------------------------+
| count(id) | type                           |
+-----------+--------------------------------+
|         8 | advanced_links                 |
|        10 | box_link                       |
|         8 | box_link_page_builder_         |
|        15 | call_out_box                   |
|        13 | call_out_box_page_builder_     |
|         7 | campaign_navigation            |
|         1 | contact                        |
|        14 | fact_box                       |
|         8 | fact_boxes_page_builder_       |
|        18 | homepage_ia_blocks             |
|        29 | homepage_icons                 |
|         6 | image_page_builder_            |
|         3 | link_and_summary               |
|         2 | link_and_summary_page_builder_ |
|         4 | newsroom_teasers               |
|         1 | pagebuilder_text               |
|         2 | quote                          |
|         2 | quote_box_page_builder_        |
|         4 | text                           |
|        65 | text_and_image_50_50_          |
|        45 | text_field_page_builder_       |
|        33 | topic_list_builder             |
|         1 | video_page_builder_            |
+-----------+--------------------------------+
```

**Comment by stephen-cox** [comment]
The only paragraphs types currently used for service pages (page, landing and sub landing) are:
- advanced_links
- contact
- pagebuilder_text
- topic_list_builder
Starting with these, but we can add more later. Also looking at adding the re-useable paragraphs as page components functionality as used by Pages.

**Comment by ekes** [comment]
> topic_list_builder

Wants to live in services.

**Comment by finnlewis** [comment]
From discussion today, the following paragraphs should live in the services module: 

 - topic_list_builder

It will not be relevant to other content types.

**Comment by stephen-cox** [comment]
Pull request for this localgovdrupal/localgov_paragraphs/pull/1

**Comment by stephen-cox** [comment]
I was wondering about adding the page component (re-usable paragraphs) functionality to this, but there's a separate module in the Croydon codebase `gull_page_components` for this.
Probably makes sense to port the module separately. In any case, it can be handled in it's own issue.

**Comment by stephen-cox** [comment]
Passing to @finnlewis  to review the pull request

**Comment by stephen-cox** [comment]
Closed at sprint 1 review.
