### ISSUE TITLE
Research / Comms: generate a list of content designers and developers within the LocalGov Drupal community

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#326]
Generate a list of council digital team members (content designers and devs etc) so that we can invite them to get involved

**Comment by finnlewis** [comment]
@TJHDCR do you think we should add this to Clinchpad or Mailchimp or just a spreadsheet?

**Comment by MichaelDCR** [comment]
@finnlewis - in a spreadsheet, we can then import the contacts to Mailchimp if and when needed

**Comment by ghost** [comment]
@finnlewis / @MichaelDCR - they should all be on mailchimp re the internal email list - but as they can unsubscribe from this we also need to hold elsewhere also. spreadsheet prob best as clinch pad won't let you filter contacts by job role.

**Comment by finnlewis** [comment]
Pushing this forward to next sprint and passing to @willguv

**Comment by willguv** [comment]
I've created a short form as I think it's the easiest way to circulate to councils and receive the data in a useful format

What do you think?

https://docs.google.com/forms/d/e/1FAIpQLSdcg72kdSmGtssrf78-MELpHUiEEb24WnhrZE284z9vOU7pgw/formResponse

@AlexandraClark83 @TJHDCR  @MichaelDCR @finnlewis

**Comment by finnlewis** [comment]
@willguv I don't seem to have permission to see the form.

**Comment by willguv** [comment]
@finnlewis should be fixed now

**Comment by stephen-cox** [comment]
Done - sprint 9
