### ISSUE TITLE
Research / Comms: testimonials - confirm the list of testimonials that we can use on the website.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#327]

**Comment by finnlewis** [comment]
In sprint review, @MichaelDCR and @TJHDCR don't have any testimonials that we are able to put names to yet.

We are able to use testimonials anonymously.

We think there are still some requests in flight that might come back with approval to put names to.

Meanwhile, @willguv will reach out to some contacts for attributable testimonials.

**Comment by finnlewis** [comment]
@AlexandraClark83 joined and shared that we do have 4 testimonials with names at the back of the report. See: 

https://docs.google.com/document/d/14FLolvVhZr2hUqavj_O2SXAIYSbMbgQD17pfnNnqeQM/edit#heading=h.pri4n9c9k2cu

**Comment by stephen-cox** [comment]
Done - sprint 8
