### ISSUE TITLE
Shop Window Website: create the initial site, staging / production sites etc

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#329]

**Comment by finnlewis** [comment]
@msayoung - I think you are working on this...

**Comment by stephen-cox** [comment]
@willguv For the initial shop window shop window site I will need some DNS records configured.

Can you please add:

CNAME record: production.localgovdrupal.org => localgovdrupal.agile.coop.
CNAME record: stage.localgovdrupal.org => localgovdrupal.agile.coop.

**Comment by willguv** [comment]
@stephen-cox DNS records should now be in place - sorry I missed this

**Comment by stephen-cox** [comment]
Done - sprint 8
