### ISSUE TITLE
LocalGov - Service pages (landing, sub-landing, info page)

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#33]
We would like to agree on naming conventions of content types, and fields.

Originally the three pages were called: 

BHCC | Croydon
Service Hub | Service Landing Page
Subhub | Service Sub Page
Service info | Standard Page

Suggested names for these: 

Label | machine_name

- Landing Page | service_landing_page
- Sub Landing Page | service_sub_landing_page
- Page | service_page

@will will do a quick straw poll to see if these naming conventions make sense with other councils. 

Assumptions: 
- we will keep the existing field names.
- replace any reference to bhcc or croydon
- remove redundent fields (tobe confirmed if any paragraphs duplicate fields in parent content type, currently Croydon are not using too many paragraphs)
- keep all fields that make sense as structured data
- if fields are to be removed, discuss and confirm with BHCC and Croydon.

Questions: 
 - need to investigate how to allow other pages to reference services pages and confirm intended architecture of other content types to have dependent configuration
 - review the architecture of child pages and parent pages on service sub page, this might want to be refactored. 
 - check with BHCC comms team and Tom about admin UX of existing and potential changes
 - Will mentioned the idea of new admin UX to be able to select child pages from a list of potential pages from within a given topic. @todo: break this discussion out to a different issue.

**Comment by will** [comment]
Idk who to ask to do the poll but I think the new names seem fine just go for it!

**Comment by finnlewis** [comment]
Thanks @will - I did't mean to 'at' you! 

(Note to self: check github usernames of people working in the sprint)

**Comment by finnlewis** [comment]
@awalbhc will check with comms at BHCC, otherwise all happy with naming.

**Comment by awalbhc** [comment]
BHCC comms are happy with this naming convention and other proposed changes to the Add Content menu structure (grouping by feature, using a Landing Page/Page naming convention).

**Comment by stephen-cox** [comment]
Closed in sprint 1 review.
