### ISSUE TITLE
Entity Reference: unpublished items

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov#334]
Editors can't reference unpublished nodes; when creating content it is a common requirement to create both overview and linked pages while unpublished.

Modules certainly affected:
 * LocalGov Services (landing page)
 * LocalGov Guides (overview)
 * LocalGov Step-By-Step (overview)

There is the additional factor that this ideally should also work for content in workflow, ie an editor can add content that's not yet approved. Lets restrict this to the current active revision (ie. what entity reference field references).

Fix suggested in guides localgovdrupal/localgov_guides#71 uses the patch from core issue https://www.drupal.org/project/drupal/issues/2845144
This works at least on the permissions to see unpublished content, if not workflow.

Suggested To Do:

 - [ ] Agree the core patch fixes at least part of the problem now, and assuming it never gets merged won't have any long term complications;
 - [ ] Test patch against all three modules, especially checking:
   - How referenced unpublished content is displayed to users that can see it;
   - How referenced unpublished content is (not) displayed to users that can't see it;
   - Which users can reference unpublished content;
   - What happens to users editing content they can't reference.

- [ ] write tests for other modules
- [ ] document odd behaviour where known

The patch won't fix all the issues, but they should be documented; and follow-up issue as appropriate (particularly for workflow?)

Related issues:
 *  localgovdrupal/localgov_services#71
 * localgovdrupal/localgov_step_by_step#24
 * localgovdrupal/localgov_guides#44
 * localgovdrupal/localgov_guides#27
 * localgovdrupal/localgov_guides#36
 * localgovdrupal/localgov_guides#40
 * localgovdrupal/localgov_guides#71

**Comment by Adnan-cds** [comment]
Thanks for creating such a comprehensive issue Ekes :)
