### ISSUE TITLE
Shop Window Website: Page Section content (layout) area error

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/localgov#348]
this may be me attempting to do things before they are ready - if so just close this

Am unable to choose a layout with more than 1 column:
- using the Page Builder
- I select 'add a Page Section' and get the menu to select from 4 options
- if I choose anything other than 'Flexible' layout it just spins and I need to refresh / leave page

(the image icon for Page Section is broken, which may be completely unrelated)

**Comment by msayoung** [comment]
I fixed that thing. 
:)
