### ISSUE TITLE
LocalGov - Base Theme

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#35]
Create base theme for front end presentation.

Assumptions:

 - start with a Croydon theme and genericise for LocaGov Drupal

@todo: discuss this with Chris before doing significant work on the base theme.

**Comment by stephen-cox** [comment]
There's a repo containing the Croydon theme as of Adnams last copy of their git repo: https://github.com/localgovdrupal/localgov_theme

To extract the theme from the repo I simply ran `git filter-repo --subdirectory-filter web/themes/custom/croydon --force`

Some initial tasks to do around this:
- [ ] Add Lando tooling - https://github.com/localgovdrupal/localgov_project/issues/9
- [ ] Rename files and functions from croydon to localgov_theme
- [ ] Enable theme on install - https://github.com/localgovdrupal/localgov/issues/45

Then we need to add something on site install to say it's a LocalGovDrupal site themed accordingly.

**Comment by stephen-cox** [comment]
Do we want to commit compiled assets? https://github.com/localgovdrupal/localgov_theme/issues/5

**Comment by stephen-cox** [comment]
Pull request for enabling base theme with the site install: https://github.com/localgovdrupal/localgov/pull/46

The header and footer are very Croydon specific, but I think this is everything without starting to make major changes to templates and SASS.

**Comment by stephen-cox** [comment]
Closed at sprint 1 review.
