### ISSUE TITLE
Document which branches we are supporting

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#355]
We are focussing on the Drupal 9 branches, which in some case is the 2.x branches.

Drupal 8 end of life is November. https://www.drupal.org/psa-2021-2021-06-29

It is a fair amount of work to back port work that might not be needed.

- [x] Document this in the README files in localgov profile.
- [ ] Document this in the README files in other relevent projects.

**Comment by andybroomfield** [comment]
Bump.
