### ISSUE TITLE
LocalGov Admin UX for topics on service sub landing pages 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#36]
Will and Tom raised the discussion in sprint planning as to how the child page admin UX works and would ike to do some research into the user needs and the user stories around this.

This issue is a stub to take this discussion forward.

**Comment by finnlewis** [comment]
See https://trello.com/c/hhhxpqJS/184-topics-discussion for discussion points.

**Comment by finnlewis** [comment]
Topics are currently used for different things.

1. to automate the display of related links: 

If a page is created, it can be tagged with a topic.  
If taggeed with a topic, it will display related links of other pages taged with the same topic.
Currently the option exists to 'Replace automatic related content' with manually curated links.

2. Add a link to "more" related content on Service Sub Page/ Sub hub pages

There is also a desire to automate the suggestion of related content to content managers as they create a child services page. 

From the Trello ticket: 

> Croydon and Brighton are using the site in different ways
> 
> Croydon doesn't use topic tagging at all, and we think it confuses people
> 
> Brighton uses topic tagging, but it sounds like some aspects (eg automated weighting of related links based on common topic tags) aren't that useful and they override them
> 
> We think there's a few candidates for work, which we can discuss on Monday:
> 
> review which content formats can be topic tagged. It feels like lower level pages should have this capability (eg Page, Campaign Page, Campaign Landing Pages) but pages at the start of a journey shouldn't (Service Landing Page, Service Sub Landing Page). Tagging the wrong pages can lead to circular journeys
> 
> review of the UX on the "child pages" tab on Service Sub Page/ Sub hub eh https://lbc-app-w-corpwebsite-p.azurewebsites.net/node/243/edit. Right now topic tagging and manual adding aren't clear. Also this page was never properly finished
> 
> review of the UX on "related content" tab on Standard Page eg https://lbc-app-w-corpwebsite-p.azurewebsites.net/node/786/edit. This is unclear for the same reason as the Sub Page
> 
> global setting(s) for topic tagging or manual adding, which would make Sub Pages/ Standard Pages default to one mode or another
> 
> If this is a lot of extra work, or takes us off at a tangent from the code sharing project, we should consider not doing it. Let's discuss on Mon

**Comment by finnlewis** [comment]
@todo come back to this an confirm specification.

**Comment by ekes** [comment]
[reminder: advanced links - paragraph type mentioned]

**Comment by finnlewis** [comment]
@ekes suggests the following: 

When editing an service landing page: 
 - the admin sees a list of content that links to this page, which this page does not yet link to
 - the admin can drag one of this link onto the 'common tasks' or 'child pages' sections, to auto poopulate one of the available fields. (noting complexity of the different between common tasks and child pages)
 - the admin can then re-order these links as normal
 - the suggested links block will need to follow the admin down the page on longer pages.... 
 - this might need different versions depending on the screen width 9assume just wider screen for now)
