### ISSUE TITLE
Business planning: survey existing councils for membership fees

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#361]
@willguv to talk Dave Briggs to solicit help talking to councils in the current cohort to confirm if the membership fee for LocalGov Drupal is a goer.

**Comment by willguv** [comment]
We're saying...

- there's not likely going to be grant funding beyond the next CLG bid (12 months max) so we need to find ways to pay for supporting the community, onboarding, some technical development of the platform
- there's a voluntary donation that councils pay between £1-10k depending on population and budget (CCIN model)
- money supports future development and onboarding of councils (pay it forward)
- councils keep all code they have now
- benefits might include training, case studies, representation on the steering group
- what's general thoughts, what benefits would encourage to pay?

**Comment by andybroomfield** [comment]
> councils keep all code they have now

Just to add here, project is open source, and unless there are plans to restirct that, simply wanting to use to code  including updates shouldn't come with a paywall.

**Comment by willguv** [comment]
No plans to change the licensing arrangements, or put up a paywall. We're going to research councils' views on a voluntary scheme that orgs can contribute to if they can afford it.

**Comment by finnlewis** [comment]
@andybroomfield we are only exploring optional membership fees as a route to generating revenue for the core team and sustainability of the project.

Just to confirm, I too am of the opinion that the distribution is and always should be free and open source under the GPL2 (or greater) licence. 

Membership of the future organisation should be optional and include potential benefits as well as supporting the future of the distribution but should not be a condition of using the code or contributing to the community in other ways.

There may be other ways to generate revenue, if anyone has any good ideas, let's share and discuss.

**Comment by msayoung** [comment]
I think can be closed now.
