### ISSUE TITLE
Version requirements for localgov profile's dependencies are too strict

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov#365]
Hello,
I was trying to update the localgov_alert_banner module in a fresh localgov test site but it wouldn't budge.  Turned out even though the latest version for localgov_alert_banner is 1.2.0, the localgov profile's version [requirement demands](https://github.com/localgovdrupal/localgov/blob/4d6720cf7d068d193e32550e31e6913a08a31a05/composer.json#L22) ```~1.1.0``` which I feel is too strict.  The same is true for the other dependencies of the localgov profile. ```~1.1.0``` is equivalent to ```1.1.x >= 1.1.0``` whereas we may need something like ```1.x.x >= 1.1.0``` which ```^1.1.0``` can satisfy easily.  So I am wondering if we should replace all the tildes with carets in the localgov profile's composer.json file.

@finnlewis @danchamp @andybroomfield @stephen-cox @ekes @MattOz-CDS

**Comment by stephen-cox** [comment]
With the release of Alert Banner 1.2.0 we should have also updated the 1.x and 2.x version of the profile.

Pinning minor versions in the profile was done so that changes that needed planning (such as the field rename) were done consciously and not accidentally, but I do feel this is too strict and we should be pinning major versions, so I support this change.

**Comment by finnlewis** [comment]
I agree, let's replace the tildes with carets!

It also follows what other distributions do, like 

- https://github.com/thunder/thunder-distribution/blob/6.2.x/composer.json
- https://git.drupalcode.org/project/lightning/-/blob/8.x-3.x/composer.json

I'll create a branch and a pull request.

**Comment by andybroomfield** [comment]
From @ekes on the PR #366 
> My tendency would be to leave it, so you have to make explicit the feature releases (and any dependency changes) in releases of localgov.

Is there a reason we changed as it used to be that profile would always pull in latest releases?
There is an argument that having stablilty in the profile is benificial and new features get a minor version release of profile to upgrade to them.
(Its mute in BHCC as we don't use the profile, were looking at integrating modules directly).

**Comment by finnlewis** [comment]
While we discuss this.... I've created a smaller pull request to just mump the localgov_alert_banner version

https://github.com/localgovdrupal/localgov/pull/368
