### ISSUE TITLE
Service pages (sub issue): Code organisation

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov#37]
Parent: #33 

Current thinking about how to organise (and move) code:-

Create a localgovdrupal/services repository which will contain localgov_services_core, localgov_services_pages, localgov_services_landingpage modules.
The implication of this is that composer require is just localgovdrupal/services version. Dependencies, and versions, increase together for all the modules that are just separated for keeping things readable.

Code from the present modules:-
 * bhcc_service_hub
 * bhcc_service_info
 * bhcc_sub_hub
Will be filtered and make the repo. This can then be refactored, but maintain history. Other modules could be added later, but that can be more work avoiding potential conflicts, so easier in the beginning.

Configuration, cleaned of as many dependencies as possible, is then added into the appropriate submodules, starting with the localgov_services_pages (or is that _page) which is already started.

**Comment by stephen-cox** [comment]
If we're splitting services into separate modules, I would suggest the repo is a localgovdrupal/localgov_services module - which would be the localgov_services_core module - and then submodules for localgov_services_page, localgov_services_landing_page and localgov_service_sub_landing_page.

But, if all these modules are dependent on each other then maybe they don't need to be separate modules?

**Comment by ekes** [comment]
Naming wise it makes sense even the repo is localgov_ prefixed if it will move from localgovdrupal/ on github to drupal/ as a repo on drupal.org

> But, if all these modules are dependent on each other then maybe they don't need to be separate modules?

I'm assuming it might be possible to install the page on its own, as the upward (landing/sub references) would be pluggable. But these would only be plugable because we want to make those fields available to other content types outside the services section if the services module is enabled. So it's almost just a theoretical possibility, and really if you want another sort of 'page' it should probably be one made for the purpose of standing alone.

There is also Service status | service_update_page content type which as yet doesn't exist a a module to move over. I've not checked its dependencies.

Certainly the navigational landing pages don't make any sense outside of dependency on each other.

So I think they'll all depend on each other as a ecosystem. The only reason to make them (sub)-modules would be to keep config/install for each content type in compartments, and any particular code specific to these. The rest of the code (and composer dependencies to other modules) sit up with core module.

So I'm not wedded to separating them in the repo. Although there are some separate contrib modules in the croydon site there isn't one per content type.

**Comment by andybroomfield** [comment]
Above sounds ok to me @ekes.
One thing I would suggest is that the BHCC codebase has the historical history (if we want to preserve the full commit history). Whereas the Croydon code base as I understand comes from a fork based on a distribution that a previous Miggle developer created for Croydon, so may not contain the full code commit history. If Croydon code is not diverged regarding services in this regard preserving the full history would be preferable, else I would go with Croydon code base if its closer to what the finished versions would be like.

**Comment by andybroomfield** [comment]
> There is also Service status | service_update_page content type which as yet doesn't exist a a module to move over. I've not checked its dependencies.

@ekes This is related to services, though is may also be changing its purpose. It originally posts updates about a service under the service landing page in a view. But its also being repurposed into a service status page (eg. Powers this page on Croydon https://new.croydon.gov.uk/service-status) and BHCC has this in UAT. 
Historically not widley used in BHCC though recently gaining more use re. Covid. My feeling is that its more of an extras module.

**Comment by ekes** [comment]
> @ekes This is related to services, though is may also be changing its purpose. It originally posts updates about a service under the service landing page in a view. But its also being repurposed into a service status page

Thanks, so need to keep an eye out for that as another of the modules that's possibly _optionally_ linking into services I'm guessing then.

**Comment by ekes** [comment]
The diff's for the history attached (what github doesn't accept .diff attachments :roll_eyes:)
[bhcc_service_info.brighton-croydon.txt](https://github.com/localgovdrupal/localgov/files/4628140/bhcc_service_info.brighton-croydon.txt)
[bhcc_sub_hub.brighton-croydon.txt](https://github.com/localgovdrupal/localgov/files/4628141/bhcc_sub_hub.brighton-croydon.txt)

Only two things I think to note here:
 * There's a difference of allowed tags. Which is a nice reminder that we probably want to be opinionated about that for the distribution install (my opinion is that we might not have Brighton's opinion) but it absolutely should be overwritable and it should _stay_ that way with any further updates. Also some of these are hardcoded a render array I think, need to check.
 * The bulk of other differences are about Topics that has all been opened up, but it looks like the Brighton code might just be hardened a bit.

**Comment by ekes** [comment]
> There's a difference of allowed tags. Which is a nice reminder that we probably want to be opinionated about that for the distribution install (my opinion is that we might not have Brighton's opinion) but it absolutely should be overwritable and it should stay that way with any further updates. Also some of these are hardcoded a render array I think, need to check.

One of these is in the getter created for getPageDescription(). Configured in the theme, the overrides there can allow appropriate tag filtering. 

TODO make a note that this is a function of this getter when people recreate the theme.

**Comment by ekes** [comment]
I think there are separate issues for the now created - or to be created modules - for this issue. @finnlewis close this one?
