### ISSUE TITLE
Review config import / update hooks for new configuration items

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#376]
@ekes has discovered the right way do this, so we need to review modules to make sure we are doing this correctly.

@ekes could you update this please?

**Comment by andybroomfield** [comment]
Bump

**Comment by ekes** [comment]
This https://github.com/localgovdrupal/localgov_directories/issues/275 so we need to update the call to limit the configuration that gets updated and also update the documentation https://github.com/localgovdrupal/localgov/wiki/Developers:-Modul%5Bar%5De-structure#conditional-content

**Comment by ekes** [comment]
```
localgov_guides/localgov_guides.module:    \Drupal::service('config.installer')->installOptionalConfig();
localgov_step_by_step/localgov_step_by_step.module:    \Drupal::service('config.installer')->installOptionalConfig();
localgov_directories/localgov_directories.module:    \Drupal::service('config.installer')->installOptionalConfig(NULL, [
localgov_directories/src/ConfigurationHelper.php:      $this->configInstaller->installOptionalConfig(NULL, [
localgov_events/localgov_events.module:    \Drupal::service('config.installer')->installOptionalConfig();
```
So after directories, it's guides, step_by_step and events. And then making sure optional configuration (particularly media) wasn't relying on it getting rescanned when particular modules are installed... probably easiest by checking all the dependencies in the media optional and seeing if we need to add a installOptionalConfig explicitly stating them to some other module.

**Comment by ekes** [comment]
So now media installs its own optional config https://github.com/localgovdrupal/localgov_core/pull/173/files
Directories has been updated https://github.com/localgovdrupal/localgov_directories/pull/278/files

Outstanding modules: Guides, Step By Step, and Events should specify their dependencies as directories when installing optional config. Hopefully the media update will ensure its configuration is installed.
