### ISSUE TITLE
Tests failing with Lando

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#38]
Trying to run phpunit tests with `lando phpunit` with default lando configuration and get AlreadyInstalledException.

Have tried Lando rebuild and still same issue.

Also trying solutiuons in [this Drupal.org issue](https://www.drupal.org/project/drupal/issues/2771811) to see if resolution, but making note here in case its project specific.

Terminal output, this is with the included phpunit.xml.dist.
Output 
````
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Testing 
Drupal\Tests\localgov\Functional\LocalGovProfile
 ✘ Local gov drupal profile
   │
   │ Drupal\Core\Installer\Exception\AlreadyInstalledException: <ul>
   │ <li>To start over, you must empty your existing database and copy <em>default.settings.php</em> over <em>settings.php</em>.</li>
   │ <li>To upgrade an existing installation, proceed to the <a href="/update.php">update script</a>.</li>
   │ <li>View your <a href="https://appserver">existing site</a>.</li>
   │ </ul>
   │ 
   │ /app/web/core/includes/install.core.inc:529
   │ /app/web/core/includes/install.core.inc:114
   │ /app/web/core/lib/Drupal/Core/Test/FunctionalTestSetupTrait.php:296
   │ /app/web/core/tests/Drupal/Tests/BrowserTestBase.php:569
   │ /app/web/core/tests/Drupal/Tests/BrowserTestBase.php:402
   │ 

Time: 30.85 seconds, Memory: 6.00 MB


ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
````

**Comment by andybroomfield** [comment]
I'm able to run tests outside lando environment (with a custom phpunit.xml).
Strangley this reports the test to make sure /admin page can't be accessed by anon users fails.
````
Time: 1.25 minutes, Memory: 6.00 MB

There was 1 error:

1) Drupal\Tests\localgov\Functional\LocalGovProfileTest::testLocalGovDrupalProfile
Behat\Mink\Exception\ExpectationException: Current response status code is 200, but 403 expected.

/Users/Andy/Sites/localgovdrupal/vendor/behat/mink/src/WebAssert.php:768
/Users/Andy/Sites/localgovdrupal/vendor/behat/mink/src/WebAssert.php:130
/Users/Andy/Sites/localgovdrupal/web/core/tests/Drupal/FunctionalTests/AssertLegacyTrait.php:211
/Users/Andy/Sites/localgovdrupal/web/profiles/contrib/localgov/tests/src/Functional/LocalGovProfileTest.php:40

ERRORS!
Tests: 1, Assertions: 4, Errors: 1.
````

**Comment by finnlewis** [comment]
Hi @andybroomfield 

Thanks for the detailed report. I'm just re-installing from scartch to see if I can replicate your issue. 

You're on Mac OSX, right? Not that it should matter with Lando.

Cheers,

Finn

**Comment by andybroomfield** [comment]
@finnlewis Yes MacOS 10.14, Lando 3.0.1.
This is from a vanilla build using `composer create-project localgovdrupal/localgov-project MY_PROJECT --stability dev --no-cache`

**Comment by finnlewis** [comment]
@andybroomfield 

I get the same as you. 

I'll check the same on my Ubuntu machine just out of interest and then try to see why this is failing in this way.

Many thanks,

Finn

**Comment by andybroomfield** [comment]
Following this [comment on drupal.org](https://www.drupal.org/project/drupal/issues/2771811#comment-13607303) I'm able to get tests working by logging into Lando container via lando ssh and exporting the simple_DB variable `export SIMPLETEST_DB='sqlite://localhost/tmp/db.sqlite'` allows the tests to run.

**Comment by andybroomfield** [comment]
Found a clue: https://github.com/lando/lando/pull/1092/files#diff-cc0c55fd4c3545a45953e0994f4a1a56R269
Added PR with fix that resolves this.
