### ISSUE TITLE
Search api updates are failing (due to a patch?)

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#396]
After doing composer update and trying to run updates with `lando drush updb -y` I get
> Fatal error: Cannot redeclare search_api_update_8107() (previously declared in /app/web/modules/contrib/search_api/search_api.install:341) in /app/web/modules/contrib/search_api/search_api.install on line 409

There is a duplicated search_api_update_8107() function, but it is not included in the vanillia 1.21 package which I downloaded from drupal.org.
The function does not appear anywhere in the vanilla search API module so I assume this is coming from a patch which needs to be updated.

````php
/**
 * Update Search API views to use the correct query type.
 *
 * In some cases, Views creates Search API views with the default "views_query"
 * query type instead of "search_api_query".
 */
function search_api_update_8107() {
  $config_factory = \Drupal::configFactory();
  $changed = [];

  foreach ($config_factory->listAll('views.view.') as $view_config_name) {
    $view = $config_factory->getEditable($view_config_name);
    if (substr($view->get('base_table'), 0, 17) == 'search_api_index_') {
      $displays = $view->get('display');

      $updated = FALSE;
      foreach ($displays as $id => $display) {
        if (($display['display_options']['query']['type'] ?? '') === 'views_query') {
          $displays[$id]['display_options']['query']['type'] = 'search_api_query';
          $updated = TRUE;
        }
      }

      if ($updated) {
        $view->set('display', $displays);
        // Mark the resulting configuration as trusted data. This avoids issues
        // with future schema changes.
        $view->save(TRUE);
        $changed[] = $view->get('id');
      }
    }
  }

  if (!empty($changed)) {
    $vars = ['@ids' => implode(', ', array_unique($changed))];
    return t('The following views have been updated to use the "search_api_query" query type instead of "views_query": @ids.', $vars);
  }

  return NULL;
}
````

**Comment by ekes** [comment]
Oh! We've got a patch that includes an update_X hook :-( `<kicks self>`

This is going to be 'fun'.

I guess we need to drop the update index by one, for anyone we're sure has run the patch hook? Then maybe it can be changed into a named post-update, that would be safer. That or in a custom module with something to take account of the code getting merged. Otherwise this will happen again I'd guess.

**Comment by andybroomfield** [comment]
Thanks for looking @ekes do you know which module is including the patch and is it a patch from drupal.org?

**Comment by andybroomfield** [comment]
I found it in localgov profile, and it is this patch https://www.drupal.org/project/search_api/issues/3196990

**Comment by ekes** [comment]
There was a new release of Search API - literally just in the last hours - which will include 
https://git.drupalcode.org/project/search_api/-/blob/8.x-1.x/search_api.install#L339

There's a patch on Search API in the composer.json https://github.com/localgovdrupal/localgov/blob/4da86448d21a4be7b3b5aba7f346b9f985345a46/composer.json#L65 for https://www.drupal.org/project/search_api/issues/3196990 which hasn't made the cut for the new release.

**Comment by ekes** [comment]
I think something like:
 - as the new release of search_api will leave the schema version at 8109 there could be a update hook in localgov to check schema at 8107 resetting it to 8016 (maybe check search_api version); but how to run before upgrade?
 - remove that update patch for now
 - then add patch back, but as a post-update hook - if it's not safe to run over existing updated config it can be made to be so

**Comment by finnlewis** [comment]
Just discussing this on a call with @andybroomfield 

@ekes I think the original motivation for this patch was to fix the tests which were failing due to mismatched schema, is that right?

Either way, it would be good to see what we can do to fix this sooner rather than later.

**Comment by finnlewis** [comment]
Could we pin search_api at a given version in the profile's composer.json ?

**Comment by finnlewis** [comment]
Andy is just trying this on https://github.com/localgovdrupal/localgov/pull/397

**Comment by ekes** [comment]
Think I have a solution to this - based on writing a custom update hook for ourselves, that's safe for the two updates. I'll look at it when I get home at the end of the week if not before.

**Comment by ekes** [comment]
So that took longer than I thought https://www.drupal.org/project/search_api/issues/3196990#comment-14290662 for the search_api patch, with https://github.com/localgovdrupal/localgov/commit/1db9e6fe2b49a476295fb7988b70a66a98451c00 to apply it and the missed search_api update.
