### ISSUE TITLE
Shared fields: (Beta) Banner

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov#40]
field_beta_banner is a tickbox on Services content types. At first brush I can't find this actually being used. Is it?

(Independently there is also an image field_banner and field_banner_colour on other non-Service content types)

**Comment by ekes** [comment]
@willcallaghan @andybroomfield OK If I just ping you into all of these?

**Comment by willcallaghan** [comment]
Yep please do

**Comment by andybroomfield** [comment]
Belive this is for controlling the beta banner on service pages, presumably when the site was first deployed. No longer used so can be removed. (and if a beta banner is required, make it a global block and control with context?)
The other banner fields are related to html doc and campaigns (think full bleed header images) so would be required for those content types only.

**Comment by andybroomfield** [comment]
I've never seen this is localgov, if anyone needs a better banner, I assume thats custom block they can build themselves.
