### ISSUE TITLE
Login form errors not showing

### ISSUE THREAD

**Issue by em-cd** [localgovdrupal/localgov#410]
Hello 👋 

I'm trying out Drupal and LocalGov Drupal for the first time and I've noticed that when I try to log in with an incorrect username or password, there's no error message to tell me what's gone wrong on the login screen. This is happening on a fresh local installation and also on a fresh install deployed on AWS. On a fresh install of plain Drupal the error messages are showing correctly.

I'm not familiar with either Drupal or LocalGov Drupal so I'm not sure where to look for the problem. Hopefully this is the right place to flag this issue - apologies if not!

**Comment by stephen-cox** [comment]
Hi @em-cd 

Thanks for reporting this.

There's a known bug with the theme which means system messages are not being displayed https://github.com/localgovdrupal/localgov_base/issues/154, which I suspect is why you're not seeing a login error message.

Development on this has slowed a little over the last month, but hopefully we / I can find some time to look at this soon.

**Comment by stephen-cox** [comment]
@em-cd This should have been fixed with the latest release of the base theme (https://github.com/localgovdrupal/localgov_base/releases/tag/1.2.3) - thanks to @markconroy for the fix.

Can you confirm this is fixed if you update the base theme to the latest version?

**Comment by markconroy** [comment]
Yes, this is fixed. I tested it while fixing the other issue.

**Comment by em-cd** [comment]
Thanks @stephen-cox and @markconroy, can confirm that's fixed it for us too! 🙏
