### ISSUE TITLE
List of sites built with LocalGov

### ISSUE THREAD

**Issue by thibaudcolas** [localgovdrupal/localgov#418]
I hope this is the right place to ask for this – let me know if not.

I’ve just learned about LocalGov and am looking for examples of sites built with it. I have a rough idea of which councils are using it currently, but haven’t been able to find any open-source sites to confirm. Are there examples out there of open-source sites using LocalGov? If so it would be nice to add a list to the documentation so we can see what those projects look like in practice.

I’ve attempted to find this info by using GitHub’s code search pointing at composer.json files: https://cs.github.com/?q=localgovdrupal+language%3AJSON. No luck there but I might be doing this wrong.

Edit: providing a bit more info on where I looked in case it helps:

- [List of UK councils involved with LocalGov](https://localgovdrupal.org/)
- [List of UK councils that are on GitHub](https://government.github.com/community/#governments-uk-councils)

**Comment by finnlewis** [comment]
Hi @thibaudcolas ! Great question and sorry that no-one got back to you sooner! 

We've had a bit of a break but are now getting back into building a microsites system for UK councils.

We do know of a number of councils who have launched sites on LocalGov Drupal, which include : 

- https://www.croydon.gov.uk/
- https://www.brighton-hove.gov.uk/
- https://www.westminster.gov.uk/
- https://new.cumbria.gov.uk/births-deaths-marriages-and-ceremonies
- https://www.walthamforest.gov.uk/

But there are more...

**Comment by thibaudcolas** [comment]
Thank you @finnlewis 🤘  I’ll close this now and take a look at those sites, would be nice if there were open source examples but I understand this might be asking too much.
