### ISSUE TITLE
Shared: workflow

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov#42]
There are just two workflows: editorial and news.

Assume there will be default workflows in a localgov_workflow module? @finnlewis 

I also assume the workflows for lots of content types are much the same? @bhccwebmaster @willcallaghan Looking at croydon lots of content types have workflow and they all seem to be 'editorial'.

First dependencies here are services sublanding and services page (not landing page interestingly). I know there was some discovery to do about where workflows weren't working @andybroomfield ? 

But to begin with the two that exist into a standalone module?

**Comment by andybroomfield** [comment]
The general idea is that workflows are for non comms team members to submit content for approval. So in general this should be service info pages.
Workflows are used for directories and news, though its a seperate workflow. Ideally it would be nice to have a single workflow and review que for editors to work with.
Not sure why sub landing pages have them, though it might be becuase sometimes once comms team member will put togerther the sub hub (what we are now calling a sub landing page) together and have another comms team member approve it. @awalbhc might be able to shed more light.

Croydon have also been adding workflow to guides and campaigns, BHCC has yet to intergrate this.

Is there a way for determing workflow if it is there and ignoring it otherwise?

**Comment by awalbhc** [comment]
Feels like this is one for Sprint 2 so we can get our comms team involved. This is what we know and could be the starting point for some user stories:

- The basic workflow for Pages works for most cases
- There will be a need to share entire sections of the site that are in draft - including Landing Pages and Sub Landing Pages - to select anonymous users by sharing a link. Users should be able to navigate around a section. I'm not sure if this is possible at the moment, I think they need to share individual links to each page.
- There is confusion around unpublishing pages - the current workflow generates a new draft but leaves the last revision published. There will be need to take pages down. I'm aware that there is an "Archive" step but it's not clear what this does. This could become an "Unpublish" step that takes all revisions down.
- The Workflows haven't been applied consistently across content types. We will need to map out which content types require which workflow.
- Will every organisation have the same user roles? In BHCC only our digital comms team can edit Service pages. The wider comms team can add News. Certain services can add Directory entries and Events. Will this be the same everywhere? We might need some generic User Roles and Workflows that councils can configure themselves.

**Comment by andybroomfield** [comment]
Workflow in BHCC.

There are two workflows, though they mirror each other, just applied to different content types as News has different permissions on who can approve. The main workflow is editorial.

There are four states:
- Draft (This will create a new revision that is unpublished, if a revision is already published this revision is left published)
- Review (This will appear into a review queue which is a admin view listing pages that are ready to be published)
- Published (The revision is published and visible)
- Archive (The published revision is unpublished)

The currently configured transitions are:

Label | From | To | Roles
-- | -- | -- | --
Create New Draft | Draft, Published | Draft | Authors, Comms Editors
Submit for review | Draft, Published, Archived, Review | Review | Authors, Comms Editors
Approve | Review | Published | Comms Editors
Reject | Review | Draft | Comms Editors
Publish | Draft, Published | Published | Comms Editors
Archive | Draft, Published | Archived | Comms Editors
Restore to Draft | Archived | Draft | Comms Editors
Restore | Archived | Published | Comms Editors

This is achieved through a single drop down at the bottom of the page that allows the page state to be set to each of the applicable states that are available.

At present (to aide in content transition) Comms editors can publish articles directly. Normally pages would have to be moved from draft to review and then published.

There is some confusion with editors in that by moving to draft, the last published page is left up and there didn't appear to be a simple way to unpublish a page. This is actually accomplished by archiving it, though this may be the wrong word as whilst sometimes its used to remove a page, there are times when pages need to be unpublished temporally (eg. a webform service going offline for maintenance, so info with access links need to be hidden).

When a page is added to review, those with the appropriate access to /admin/content/review can see a list of content (which they have permission to edit) that has been marked for review of which they can approve. A separate permission was defined, Access the Review queue page.

<img width="1389" alt="Screenshot 2020-06-12 at 12 07 32 am" src="https://user-images.githubusercontent.com/1467480/84447918-3af1d380-ac41-11ea-90aa-5f9e7ecaa05c.png">

**Comment by willguv** [comment]
Thanks @andybroomfield this will be really useful for Friday's story refinement session - much appreciated!

**Comment by willguv** [comment]
Discussed with London Councils, Bracknell and previously Westminster - they're OK implementing this as it stands

Kensington & Chelsea had an extra step:

- Authors write
- Submit to Comms Editors for 2i
- Comms editors send back to Authors for publishing

**Comment by finnlewis** [comment]
Note: roles are being introdued with this workflow. The workflow above suggests: 

- Author
- Comms editor

The role 'Content designer' is perhaps prefered to 'Comms editor' these days.

So let's assume initial default roles: 

- Author
- Content designer
