### ISSUE TITLE
Remove Github CI tests running against Drupal 8

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov#422]
To update:

  * https://github.com/localgovdrupal/localgov_alert_banner/blob/1.x/.github/workflows/test.yml
  * https://github.com/localgovdrupal/localgov_page_components/blob/1.x/.github/workflows/test.yml
  * https://github.com/localgovdrupal/localgov_skeleton/blob/1.x/.github/workflows/test.yml
  * https://github.com/localgovdrupal/localgov_theme/blob/1.x/.github/workflows/test.yml
  * https://github.com/localgovdrupal/localgov_topics/blob/1.x/.github/workflows/test.yml

**Comment by finnlewis** [comment]
@stephen-cox shall we evolve this issue to cover only running tests on the modules code and testing on different PHP version?

https://github.com/localgovdrupal/localgov/issues/423
https://github.com/localgovdrupal/localgov/issues/424

**Comment by stephen-cox** [comment]
This will be fixed with #423

**Comment by andybroomfield** [comment]
I believe this is done
