### ISSUE TITLE
Only run Github CI tests on that modules code - not on all modules

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov#423]

**Comment by finnlewis** [comment]
Just noting this again at Merge Monday. 

Not any time this week, but hoping to make this soon. 

This has complications and will involve reworking the test file: 

https://github.com/localgovdrupal/localgov/blob/2.x/.github/workflows/test.yml

**Comment by finnlewis** [comment]
@Adnan-cds and I were just discussing this and would like to get this moving soon. We think we'll have time to look at this in a couple of weeks.

**Comment by stephen-cox** [comment]
Now we have this working in Alert Banner we should genericise it and roll it out to all repos

**Comment by finnlewis** [comment]
Assigning this one to you @stephen-cox - want to give it an estimated number of story points?

**Comment by stephen-cox** [comment]
I've written a PHP app that updates the GitHub workflows from a template, creating PRs for the changes: https://github.com/localgovdrupal/github_workflow_manager

There are now 24 PRs for this:

* https://github.com/localgovdrupal/localgov_project/pull/76
* https://github.com/localgovdrupal/localgov/pull/439
* https://github.com/localgovdrupal/localgov_alert_banner/pull/208
* https://github.com/localgovdrupal/localgov_base/pull/193
* https://github.com/localgovdrupal/localgov_core/pull/132
* https://github.com/localgovdrupal/localgov_demo/pull/78
* https://github.com/localgovdrupal/localgov_directories/pull/187
* https://github.com/localgovdrupal/localgov_geo/pull/54
* https://github.com/localgovdrupal/localgov_events/pull/79
* https://github.com/localgovdrupal/localgov_guides/pull/86
* https://github.com/localgovdrupal/localgov_menu_link_group/pull/18
* https://github.com/localgovdrupal/localgov_news/pull/59
* https://github.com/localgovdrupal/localgov_topics/pull/18
* https://github.com/localgovdrupal/localgov_openreferral/pull/34
* https://github.com/localgovdrupal/localgov_paragraphs/pull/48
* https://github.com/localgovdrupal/localgov_search/pull/19
* https://github.com/localgovdrupal/localgov_services/pull/159
* https://github.com/localgovdrupal/localgov_page_components/pull/27
* https://github.com/localgovdrupal/localgov_step_by_step/pull/58
* https://github.com/localgovdrupal/localgov_subsites/pull/82
* https://github.com/localgovdrupal/localgov_scarfolk/pull/12
* https://github.com/localgovdrupal/localgov_theme/pull/215
* https://github.com/localgovdrupal/localgov_skeleton/pull/24
* https://github.com/localgovdrupal/localgov_workflows/pull/37
