### ISSUE TITLE
Support PHP 8.*

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov#424]
We should support PHP 8. I'm reasonably sure LocalGov Drupal will run with PHP 8.0. but tests currently run against PHP 7.4.

At a minimum we need to update the tests to run against 8.0. Should we then change the main supported PHP version to 8?

**Comment by finnlewis** [comment]
Also see https://github.com/localgovdrupal/localgov_project/issues/65

**Comment by finnlewis** [comment]
I think we probably need to support PHP 7.4 and PHP 8.1 for a bit, but there are already contrib modules that are making releases that only work on PHP8+ (https://www.drupal.org/project/date_recur) 

This is where it would be really good to have a list of live sites, with PHP versions to know our audience a bit better.

**Comment by finnlewis** [comment]
Actually - we should probably follow Drupal's recommendations:

https://www.drupal.org/docs/system-requirements/php-requirements#versions

PHP version | Supported by Drupal | First Drupal release with support | Recommended?
-- | -- | -- | --
7.3 | 9.x | 8.6.4 (note 1 below) | No
7.4 | 9.x | 8.8.3 | No
8.0 | 9.x | 9.1.0 | Yes
8.1 (note 2 below) | 9.x, 10.x | 9.3.0 | Yes

So support but not recommend PHP 7.3 and 7.4

**Comment by finnlewis** [comment]
The suggestion on today's Merge Monday call was to test against PHP 7.4 and 8.1 for most module repositories, but to do a more full test on the localgov profile repo to include 7.4, 8.0, 8.1 and run tests across all the code on a regular daily schedule.

Anything else we need to do on this issue @stephen-cox ?

**Comment by stephen-cox** [comment]
To support PHP 8.1 we need to upgrade phpstan in the localgov_project: https://github.com/localgovdrupal/localgov_project/issues/65#issuecomment-1095145300

Fix some PHP Unit tests:

- https://github.com/localgovdrupal/localgov/issues/437
- https://github.com/localgovdrupal/localgov_openreferral/issues/29

Fix some code deprecation issues that come from the phpstan upgrade:

- https://github.com/localgovdrupal/localgov_alert_banner/issues/198
- https://github.com/localgovdrupal/localgov_core/issues/126
- https://github.com/localgovdrupal/localgov_demo/issues/75
- https://github.com/localgovdrupal/localgov_directories/issues/181
- https://github.com/localgovdrupal/localgov_geo/issues/51
- https://github.com/localgovdrupal/localgov_guides/issues/82
- https://github.com/localgovdrupal/localgov_news/issues/54
- https://github.com/localgovdrupal/localgov_openreferral/issues/30
- https://github.com/localgovdrupal/localgov_services/issues/153
- https://github.com/localgovdrupal/localgov_subsites/issues/79
- https://github.com/localgovdrupal/localgov_workflows/issues/33
- https://github.com/localgovdrupal/localgov_theme/issues/206

**Comment by finnlewis** [comment]
So @stephen-cox I think this one is done, no?
