### ISSUE TITLE
Consider adding Elbow room to distribution

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#426]
[May be in the wrong repo]

Croydon has installed [Elbow room](https://www.drupal.org/project/elbow_room) to allow content designers there to show/ hide the right hand sidebar and provide more space for working

This *may* have included a modification to make the show/ hide persistent across pages

Clicking "hide" hides the sidebar across multiple pages until the user clicks "show" to show it again

##Questions

- is this a common need?
- are there better ways of achieving the same functionality within Gin, or another route? eg https://www.drupal.org/project/gin/issues/3187407
- is Elbow room compatible with the Gin theme and any others that councils may be using?

**Comment by willguv** [comment]
@Adnan-cds are you still using Elbow room on your set up? 

Did you modify it in the way I've described above, or did I imagine that? If so, could you provide details of how you did it?

Many thanks!

**Comment by Adnan-cds** [comment]
Hi Will,
Yes, we still use the Elbow room module.  It has become slightly difficult to install as the [module says](https://git.drupalcode.org/project/elbow_room/-/blob/8.x/elbow_room.info.yml#L3) it is only compatible with Drupal 8 and **not** Drupal 9.  This means we can no longer install it through composer.  There's even a [patch](https://www.drupal.org/project/elbow_room/issues/3140331) to fix this.  But the module seems to be unmaintained, so the patch has not been applied.  For our case, we now commit a patched version of this module into our Git repo.  That's a step backward but I haven't found another way.

We have added some extra Javascript code to persist the open/close state of Elbow room.  This is a single file that we added to a custom module rather than to the Elbow room module.  I am [attaching](https://github.com/localgovdrupal/localgov/files/8335360/elbow_room_alter.es6.js.txt) the file.

**Comment by andybroomfield** [comment]
@Adnan-cds Module page says its looking for a new maintainer, maybe we should take over the module and merge your fix for having it persistent as part of it?

**Comment by willguv** [comment]
@andybroomfield I think that’s worth exploring - does it deliver what we need, and what sort of long term commitment? I imagined LGD becoming active in this respect

Another option was identified within Gin, but not sure how far that’s got

https://www.drupal.org/project/gin/issues/3187407

**Comment by Adnan-cds** [comment]
> we should take over the module and merge your fix for having it persistent as part of it?

Yeah, that's an option.  Would you mind applying for membership :)  I am happy to submit a patch.

> Another option was identified within Gin, but not sure how far that’s got

That's actually very close to acceptance.

We are still using Claro, so Gin having the ability to collapse the sidebar in editing forms won't immediately help us.  But this upcoming feature of Gin is worth a try even now.

**Comment by willguv** [comment]
Thanks @andybroomfield and @Adnan-cds 

@finnlewis can this be added to the next Technical Group for discussion please? It seems we've got a few options here worth discussing

**Comment by finnlewis** [comment]
Just got myself added as maintainer of https://www.drupal.org/project/elbow_room :)

I'll see if we can get a Drupal 9 version released!

**Comment by finnlewis** [comment]
@Adnan-cds I've made a release that supports Drupal 9: https://www.drupal.org/project/elbow_room/releases/8.x-1.1

Fancy starting an issue and branch to submit your proposed improvements?

**Comment by Adnan-cds** [comment]
> Just got myself added as maintainer...

Congratulations :)

> I've made a release that supports Drupal 9

Thanks a lot.  The world can start using this module through composer again.

> Fancy starting an issue and branch to submit your proposed improvements?

Sure.  I will try to raise a patch aiming for the next Merge Monday meeting.

**Comment by willguv** [comment]
Nice work all!!

**Comment by Adnan-cds** [comment]
> Fancy starting an issue and branch to submit your proposed improvements?

Hi Finn, this is [ready for you to review](https://git.drupalcode.org/issue/elbow_room-3274587/-/merge_requests/1) :)

**Comment by msayoung** [comment]
@finnlewis @Adnan-cds - do we still need this issue?
There is a version od Elbow Room incorporated in a new version of Gin.

**Comment by andybroomfield** [comment]
And also a contrib module https://www.drupal.org/project/elbow_room for non gin admin theme.

**Comment by finnlewis** [comment]
In LocalGov Drupal proper, we default to Gin theme for admin, so I don't think we need to add the contrib Elbow Room to the distro personally. 

I reckon we close this, but feel free to re-open if any of you particularly want to get it in.

(@andybroomfield I managed to get added as a maintainer to the contrib module https://www.drupal.org/project/elbow_room to help get @Adnan-cds 's patch released, see above )

**Comment by willguv** [comment]
Hi @finnlewis cheers for updating this

What's the effect of adding Elbow Room to the distro if Gin is enabled?

If we don't add it, presumably a council switching to another theme would easily be able to add Elbow Room themselves? If that's the case, maybe we should flag that they can do this in the docs
