### ISSUE TITLE
Preview links

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#427]
This has already been delivered

A content designer can create a "preview link" which can be sent to a non logged in user eg a councillor

Here's an example:

https://cumbria-dev.codeenigma.net/preview-link/node/47/ad691ff8-6202-46e3-bb8a-156457929f12

You should see a "preview link" tab, and clicking it provides a preview link that can be shared

<img width="1195" alt="Screenshot 2022-03-24 at 12 18 02" src="https://user-images.githubusercontent.com/708140/159916425-76432b49-a8d4-4a65-9d83-7e38e5af6fba.png">

If you don't see the preview link tab, ask your developer about the Preview Link and Responsive Preview modules - these are part of localgov_workflow now.

**Comment by Adnan-cds** [comment]
Hi Will,
I can confirm that the Preview link feature works great in our site and is well used.  The preview_link module gets installed when [localgov_workflows](https://github.com/localgovdrupal/localgov_workflows) is installed.

**Comment by andybroomfield** [comment]
Can we close this or is it needed for documentation?

**Comment by willguv** [comment]
We’ve got everything we need from this. Thanks @andybroomfield
