### ISSUE TITLE
Tests failing due to broken schema in contrib modules

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov#43]
Tests fail once the localgov_paragraphs module is enabled due to broken schema in the Geolocation and Office Hours modules; a SchemaIncompleteException is thrown. There's a patch for Office Hours, but not for Geolocation.

One solution is to add `$strictConfigSchema = FALSE` to the tests to disable schema checking. But this then fails code checks with: "Do not disable strict config schema checking in tests. Instead ensure your module properly declares its schema for configurations." So to use this we will need to remove the following check from our phpcs.xml.dist file: DrupalPractice/Sniffs/Objects/StrictSchemaDisabledSniff.php

**Comment by finnlewis** [comment]
Just confirming the behaviour locally before trying to fix. 

$ lando phpunit
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Testing 
Drupal\Tests\localgov\Functional\LocalGovProfile
 ✘ Local gov drupal profile
   │
   │ Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for core.entity_view_display.paragraph.contact.default with the following errors: core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.mapTypeControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.streetViewControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.zoomControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.scrollwheel missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.draggable missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.style missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.info_auto_display missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.marker_icon_path missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.disableAutoPan missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.fullscreenControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.preferScrollingToZooming missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.disableDoubleClickZoom missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_office_hours.settings.show_closed missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_office_hours.settings.day_format missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_office_hours.settings.time_format missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_office_hours.settings.closed_format missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_office_hours.settings.schema missing schema
   │ 
   │ /app/web/core/lib/Drupal/Core/Config/Development/ConfigSchemaChecker.php:95
   │ /app/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php:111
   │ /app/web/core/lib/Drupal/Core/Config/Config.php:231
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php:284
   │ /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php:457
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php:263
   │ /app/web/core/lib/Drupal/Core/Entity/EntityBase.php:395
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php:613
   │ /app/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:371
   │ /app/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:137
   │ /app/web/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php:75
   │ /app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php:288
   │ /app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php:83
   │ /app/web/core/includes/install.core.inc:1877
   │ /app/web/core/includes/batch.inc:295
   │ /app/web/core/includes/form.inc:947
   │ /app/web/core/includes/install.core.inc:659
   │ /app/web/core/includes/install.core.inc:577
   │ /app/web/core/includes/install.core.inc:117
   │ /app/web/core/lib/Drupal/Core/Test/FunctionalTestSetupTrait.php:296
   │ /app/web/core/tests/Drupal/Tests/BrowserTestBase.php:569
   │ /app/web/core/tests/Drupal/Tests/BrowserTestBase.php:402
   │ 

Drupal\Tests\localgov_paragraphs\Functional\ParagraphsAdministration
 ✔ Paragraphs types
 ✔ Paragraphs creation

Time: 1.17 minutes, Memory: 8.00 MB

Summary of non-successful tests:

Drupal\Tests\localgov\Functional\LocalGovProfile
 ✘ Local gov drupal profile
   │
   │ Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for core.entity_view_display.paragraph.contact.default with the following errors: core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.mapTypeControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.streetViewControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.zoomControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.scrollwheel missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.draggable missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.style missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.info_auto_display missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.marker_icon_path missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.disableAutoPan missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.fullscreenControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.preferScrollingToZooming missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.disableDoubleClickZoom missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_office_hours.settings.show_closed missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_office_hours.settings.day_format missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_office_hours.settings.time_format missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_office_hours.settings.closed_format missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_office_hours.settings.schema missing schema
   │ 
   │ /app/web/core/lib/Drupal/Core/Config/Development/ConfigSchemaChecker.php:95
   │ /app/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php:111
   │ /app/web/core/lib/Drupal/Core/Config/Config.php:231
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php:284
   │ /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php:457
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php:263
   │ /app/web/core/lib/Drupal/Core/Entity/EntityBase.php:395
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php:613
   │ /app/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:371
   │ /app/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:137
   │ /app/web/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php:75
   │ /app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php:288
   │ /app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php:83
   │ /app/web/core/includes/install.core.inc:1877
   │ /app/web/core/includes/batch.inc:295
   │ /app/web/core/includes/form.inc:947
   │ /app/web/core/includes/install.core.inc:659
   │ /app/web/core/includes/install.core.inc:577
   │ /app/web/core/includes/install.core.inc:117
   │ /app/web/core/lib/Drupal/Core/Test/FunctionalTestSetupTrait.php:296
   │ /app/web/core/tests/Drupal/Tests/BrowserTestBase.php:569
   │ /app/web/core/tests/Drupal/Tests/BrowserTestBase.php:402
   │ 

ERRORS!
Tests: 3, Assertions: 43, Errors: 1.

Remaining deprecation notices (3)

  2x: Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was Drupal\field_group\Element\VerticalTabs::preRenderGroup. Support for this callback implementation is deprecated in 8.8.0 and will be removed in Drupal 9.0.0. See https://www.drupal.org/node/2966725
    2x in ParagraphsAdministrationTest::testParagraphsCreation from Drupal\Tests\localgov_paragraphs\Functional

  1x: Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was field_group_form_pre_render. Support for this callback implementation is deprecated in 8.8.0 and will be removed in Drupal 9.0.0. See https://www.drupal.org/node/2966725
    1x in ParagraphsAdministrationTest::testParagraphsCreation from Drupal\Tests\localgov_paragraphs\Functional


```

**Comment by finnlewis** [comment]
After patching office_hours module with 

https://www.drupal.org/files/issues/2019-08-02/3072276-2.patch

from

https://www.drupal.org/project/office_hours/issues/3072276

we get: 

$ lando phpunit
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Testing 
Drupal\Tests\localgov\Functional\LocalGovProfile
 ✘ Local gov drupal profile
   │
   │ Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for core.entity_view_display.paragraph.contact.default with the following errors: core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.mapTypeControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.streetViewControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.zoomControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.scrollwheel missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.draggable missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.style missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.info_auto_display missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.marker_icon_path missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.disableAutoPan missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.fullscreenControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.preferScrollingToZooming missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.disableDoubleClickZoom missing schema
   │ 
   │ /app/web/core/lib/Drupal/Core/Config/Development/ConfigSchemaChecker.php:95
   │ /app/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php:111
   │ /app/web/core/lib/Drupal/Core/Config/Config.php:231
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php:284
   │ /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php:457
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php:263
   │ /app/web/core/lib/Drupal/Core/Entity/EntityBase.php:395
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php:613
   │ /app/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:371
   │ /app/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:137
   │ /app/web/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php:75
   │ /app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php:288
   │ /app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php:83
   │ /app/web/core/includes/install.core.inc:1877
   │ /app/web/core/includes/batch.inc:295
   │ /app/web/core/includes/form.inc:947
   │ /app/web/core/includes/install.core.inc:659
   │ /app/web/core/includes/install.core.inc:577
   │ /app/web/core/includes/install.core.inc:117
   │ /app/web/core/lib/Drupal/Core/Test/FunctionalTestSetupTrait.php:296
   │ /app/web/core/tests/Drupal/Tests/BrowserTestBase.php:569
   │ /app/web/core/tests/Drupal/Tests/BrowserTestBase.php:402
   │ 

Drupal\Tests\localgov_paragraphs\Functional\ParagraphsAdministration
 ✔ Paragraphs types
 ✔ Paragraphs creation

Time: 1.18 minutes, Memory: 8.00 MB

Summary of non-successful tests:

Drupal\Tests\localgov\Functional\LocalGovProfile
 ✘ Local gov drupal profile
   │
   │ Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for core.entity_view_display.paragraph.contact.default with the following errors: core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.mapTypeControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.streetViewControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.zoomControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.scrollwheel missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.draggable missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.style missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.info_auto_display missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.marker_icon_path missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.disableAutoPan missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.fullscreenControl missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.preferScrollingToZooming missing schema, core.entity_view_display.paragraph.contact.default:content.field_para_contact_location.settings.map_provider_settings.disableDoubleClickZoom missing schema
   │ 
   │ /app/web/core/lib/Drupal/Core/Config/Development/ConfigSchemaChecker.php:95
   │ /app/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php:111
   │ /app/web/core/lib/Drupal/Core/Config/Config.php:231
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php:284
   │ /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php:457
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php:263
   │ /app/web/core/lib/Drupal/Core/Entity/EntityBase.php:395
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php:613
   │ /app/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:371
   │ /app/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:137
   │ /app/web/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php:75
   │ /app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php:288
   │ /app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php:83
   │ /app/web/core/includes/install.core.inc:1877
   │ /app/web/core/includes/batch.inc:295
   │ /app/web/core/includes/form.inc:947
   │ /app/web/core/includes/install.core.inc:659
   │ /app/web/core/includes/install.core.inc:577
   │ /app/web/core/includes/install.core.inc:117
   │ /app/web/core/lib/Drupal/Core/Test/FunctionalTestSetupTrait.php:296
   │ /app/web/core/tests/Drupal/Tests/BrowserTestBase.php:569
   │ /app/web/core/tests/Drupal/Tests/BrowserTestBase.php:402
   │ 

ERRORS!
Tests: 3, Assertions: 43, Errors: 1.

Remaining deprecation notices (3)

  2x: Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was Drupal\field_group\Element\VerticalTabs::preRenderGroup. Support for this callback implementation is deprecated in 8.8.0 and will be removed in Drupal 9.0.0. See https://www.drupal.org/node/2966725
    2x in ParagraphsAdministrationTest::testParagraphsCreation from Drupal\Tests\localgov_paragraphs\Functional

  1x: Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was field_group_form_pre_render. Support for this callback implementation is deprecated in 8.8.0 and will be removed in Drupal 9.0.0. See https://www.drupal.org/node/2966725
    1x in ParagraphsAdministrationTest::testParagraphsCreation from Drupal\Tests\localgov_paragraphs\Functional

**Comment by finnlewis** [comment]
@stephen-cox 

I created a patch here https://www.drupal.org/project/geolocation/issues/3138668
https://www.drupal.org/files/issues/2020-05-21/geolocation-google-maps-schema-update-3138668-2.patch

This adds a bunch of schema definitions which gets rid of the error reported above.

I still see the deprecation notices, I guess we can deal with those separately. 

I'll comment the pull request too

**Comment by stephen-cox** [comment]
Deprecation notices are from contrib modules. These should get fixed in due course.

Closed with https://github.com/localgovdrupal/localgov_paragraphs/pull/1
