### ISSUE TITLE
Formally Drop 1.x support now?

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#432]
Last commit to 1.x branch was 4th October 2021, to bump alert banner to 1.2.
I belive the 1.x profile is very out of date and only useful if your starting or suporting a Drupal 8 site.
I saw a few issues that deal with 1.x support requests, which has had some ad-hoc support.
Is 1.x (Drupal 8) still relevant to people?
Noting also Slack disucssion on 3.x (Drupal 10).

**Comment by finnlewis** [comment]
Good shout @andybroomfield !

Shall we use the https://www.drupal.org/project/localgov project page to state the supported release(s) ?

Speaking of which, that needs updating.

**Comment by finnlewis** [comment]
I've added the following text to the Drupal.org project page: 

> ## Supported branches
> 
> We are actively supporting and developing the 2.x branch.
> 
> The 1.x branch is no longer actively supported and not recommended for new sites.
> 
> If you are still using the 1.x branch on your site, please [create an issue on Github](https://github.com/localgovdrupal/localgov/issues) to let us know.

See https://www.drupal.org/project/localgov

I've also pushed up the 2.3.9 release and confirmed that we are explicitly stating that we are supporting the 2.x branches but not the 1.x branch.

**Comment by finnlewis** [comment]
I've also added it to the README.md here: https://github.com/localgovdrupal/localgov/blob/2.x/README.md#supported-branches

**Comment by finnlewis** [comment]
@andybroomfield shall we close this or would you like to discuss in more detail?

**Comment by andybroomfield** [comment]
@finnlewis I assume, unless anyone else wants to raise objections. Shall we just message this on the Slack too?
