### ISSUE TITLE
What's the process for bringing Waltham Forest search and events functionality to the distribution?

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#447]
There's been a lot of interest in Waltham Forest's Solr search work, and our discussions suggest it's recommended to councils but not mandatory

A few councils are also interested in WF's events. If we were to replace our existing events functionality with this (or upgrade it) how we decide to do this, and go about it. Who would do the work?

**Comment by andybroomfield** [comment]
Search, yes I will be looking at Solr so would be good to look at their Solr integration.
Events, will need to look at the divergences to make sure other sites either don't break or there is an upgrade path.
From looking at it, is it just an altered view with no map and some theming to put the filters on top?
Maybe a new issue on Localgov_events? /cc @

**Comment by ekes** [comment]
> Search, yes I will be looking at Solr so would be good to look at their Solr integration.

It would also be good to get a localgov_search_solr (or similar, localgov_directories_solr, depending where the dependencies are) with any of the advised configuration for others using solr as the backend.

**Comment by finnlewis** [comment]
Also noted at https://github.com/localgovdrupal/localgov_search/issues/22

Discussing today in the Tech Group Drop-in - planning set up a meeting and sub working group to get this moving.

**Comment by ekes** [comment]
Followed-up in https://github.com/localgovdrupal/localgov_search/issues/24
