### ISSUE TITLE
Cannot apply drupal/core patches for Drupal 9.4

### ISSUE THREAD

**Issue by tran-bigbluedoor** [localgovdrupal/localgov#449]
**Describe the bug**
When we upgrade to Drupal 9.4, two of the patches failed to apply:
```
"Fix for narrow forms on node/add screens, which is included in 9.2. See https://www.drupal.org/project/drupal/issues/3184667": "https://www.drupal.org/files/issues/2021-04-16/3184667.26.patch"
"Users can't reference unpublished content even when they have access to it. See https://www.drupal.org/project/drupal/issues/2845144": "https://www.drupal.org/files/issues/2021-06-09/2845144_52.patch"
```
**To Reproduce**
1. Execute `composer update`
2. See errors

**Expected behaviour**
Upgrade to Drupal 9.4 without any errors.

**Screenshots**
![Screenshot 2022-06-16 at 14 59 56](https://user-images.githubusercontent.com/102959744/174324356-6267e7bd-39f5-4f1b-82ca-7f614a338bcd.png)
![Screenshot 2022-06-16 at 16 30 29](https://user-images.githubusercontent.com/102959744/174324374-571d6da1-aaaa-4b67-a3a5-f809db5f0cee.png)

**Suggestion fix**
1. Remove patch 'Fix for narrow forms on node/add screens' because it has been integrated into Drupal 9.4: 
https://www.drupal.org/project/drupal/issues/3184667#comment-14383721

2. Replace patch 'https://www.drupal.org/files/issues/2021-06-09/2845144_52.patch' with a new version 'https://www.drupal.org/files/issues/2022-06-17/2845144-67.patch'

**Comment by andybroomfield** [comment]
I think this is done
