### ISSUE TITLE
Schema errors in update test coming from localgov_geo 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#451]
See https://github.com/localgovdrupal/localgov/runs/6938747447?check_suite_focus=true#step:5:30

We're trying to fix some patches which are not applying in https://github.com/localgovdrupal/localgov/pull/450

This looks like it is the Drupal\Tests\localgov\Functional\LocalGovUpdateTest::testUpdate failing on schema issues for localgov_geo.

**Comment by ekes** [comment]
```
Schema key core.entity_view_display.localgov_geo.address.default:content.location.settings.fullscreen_control failed with: missing schema
```
The previous, dead, setting is `settings.fullscreen_control`. It was replaced without upgrade path to `settings.fullscreen` which is the _current_ (new) configuration and is in the schema (correctly?) https://git.drupalcode.org/project/leaflet/-/blob/2.1.x/config/schema/leaflet.schema.yml#L118

So removing _any_ `fullscreen_control` from the existing configuration on upgrade seems reasonable - as we've already flagged that it's not in use anymore on the previous upgrade.

**Comment by ekes** [comment]
Was thinking of something like:

```

/**
 * Update existing geo fields leaflet configuration. 
 */
function localgov_update_8202() {
  if ($geofield_usage = \Drupal::service('entity_field.manager')->getFieldMapByFieldType('geofield')) {
    foreach ($geofield_usage as $entity_type_id => $fields) {
      foreach ($fields as $field_name => $field_map) {
        foreach ($field_map['bundles'] as $bundle) {
          $properties = [
            'targetEntityType' => $entity_type_id,
            'bundle' => $bundle,
          ];
          if ($view_displays = \Drupal::entityTypeManager()->getStorage('entity_view_display')->loadByProperties($properties)) {
            foreach ($view_displays as $view_display) {
              if ($component = $view_display->getComponent($field_name)) {
                unset($component['settings']['fullscreen_control']);
                $view_display->setComponent($field_name, $component)->save();
              }
            }
          }
        }
      }
    }
  }

}
```

But for some reason that seems to be saving config with the same uuid. It should maybe check the widget is leaflet too, not that other's use fullscreen_control setting key.

```
1) Drupal\Tests\localgov\Functional\LocalGovUpdateTest::testUpdate
The update failed with the following message: "Failed: Drupal\Core\Config\ConfigDuplicateUUIDException: Attempt to save a configuration entity 'localgov_geo.address.embed' with UUID '3e73300e-7431-4ba8-9d1b-5ce13fc28412' when this UUID is already used for 'localgov_geo.address.default' in Drupal\Core\Config\Entity\ConfigEntityBase->preSave() (line 304 of /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php)."
```

So I'll stop looking for now.

**Comment by ekes** [comment]
Follow-up error after removing full screen in 915ee3e is caused by https://git.drupalcode.org/project/leaflet/-/commit/4d43a4ab971b3002215af062d2f57ee5f3059165 the weight being removed too.

**Comment by ekes** [comment]
I'm going to make a PR of that and see how it test here. I can't actually see the removed settings.weight in the config in the upgrade!
