### ISSUE TITLE
PHP version support

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov#463]
Actually - we should probably follow Drupal's recommendations:

https://www.drupal.org/docs/system-requirements/php-requirements#versions

PHP version | Supported by Drupal | First Drupal release with support | Recommended?
-- | -- | -- | --
7.3 | 9.x | 8.6.4 (note 1 below) | No
7.4 | 9.x | 8.8.3 | No
8.0 | 9.x | 9.1.0 | Yes
8.1 (note 2 below) | 9.x, 10.x | 9.3.0 | Yes

So support but not recommend PHP 7.3 and 7.4

_Originally posted by @finnlewis in https://github.com/localgovdrupal/localgov/issues/424#issuecomment-1093120221_

**Comment by ekes** [comment]
It's been pointed out https://app.slack.com/client/TSSGD2UD6/CSE44GLSE/thread/CSE44GLSE-1657807863.970039 that we aren't supporting 7.3 

We have some code that's not 7.3 compatible. We're not testing against 7.3 so these things won't be thrown up. There's also at least date_recur that don't support it any more.

7.3 support has been dropped by Drupal 9.4; but 9.3 is only EOL December.

Suggestion: We explicitly don't support 7.3 - defacto case - we might have already decided this but I can't find it documented - we should put it in the composer.json
We always run tests against the lowest supported version of PHP from now and in the future.

**Comment by stephen-cox** [comment]
Adding a PHP restriction into profile's composer.json is a good idea. If the some stuff breaks on PHP 7.3, let's stop LocalGov Drupal being installed with that version, unless there's good case for supporting it; which I can't think of.

**Comment by finnlewis** [comment]
Sounds sensible and reasonable.

**Comment by finnlewis** [comment]
PHP 7.4 is EOL in 4 days (28 Nov 2022).

I think we should probably stop testing on and officially supporting PHP 7.4.

@ekes @stephen-cox @andybroomfield @Adnan-cds thoughts?

**Comment by Adnan-cds** [comment]
Drupal 9.x supports PHP 7.4 although it is not recommended.  Drupal 10.x doesn't support it at all.  Our tests are currently running under [Drupal 9.x](https://github.com/localgovdrupal/.github/blob/78a909d387d1ceaeccc8edc62b7a39569f50f4d4/workflow-templates/test.yml#L22).  I am assuming once there is a stable release of Drupal 10.x, we will switch to 10.x.  That may be a good time to drop references to PHP 7.4 from the test files.

**Comment by finnlewis** [comment]
I guess we just need to articulate this clearly in our docs / readmes.

**Comment by millnut** [comment]
As well as PHP and following Drupal's recommendation should we also be factoring what the recommended Drush version is https://www.drush.org/12.x/install/#drupal-compatibility
