### ISSUE TITLE
Anonymous users can register accounts

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov#468]
In the profile, anonymous users can register accounts 

![image](https://user-images.githubusercontent.com/3852805/189164570-c6921283-c281-444a-ad89-53f7e63fb9fa.png)

Do we want to change this default

**Comment by finnlewis** [comment]
Good call @msayoung ! 

While we might assume that each council would review this before launching a site, it would perhaps be safer to default to default to 'Administrators only'.

**Comment by andybroomfield** [comment]
To fix, on fresh install disable user registration, export config and place the user.settings.yml in the profiles config/install folder.

**Comment by andybroomfield** [comment]
I noticed this when doing some fresh installs, it's still very much a problem and whilst I know there are some thoughts on authenticated traffic, I'm guessing most site installs really only intend logins for people who are editing the site so we should turn this off by default.

**Comment by stephen-cox** [comment]
PR fixing this https://github.com/localgovdrupal/localgov/pull/550
