### ISSUE TITLE
Error when installing LocalGov Subsites module/extension (fresh build)

### ISSUE THREAD

**Issue by rosscullen** [localgovdrupal/localgov#469]
Error on fresh build on dev box using lando. When installing the module/extension for "LocalGov Subsites", getting the following error:

`unable to install LocalGov Subsites due to unmet dependencies: field.field.node.localgov_subsites_overview.localgov_subsites_content (paragraphs.paragraphs_type.localgov_box_links_listing, paragraphs.paragraphs_type.localgov_call_out_box, paragraphs.paragraphs_type.localgov_documents, paragraphs.paragraphs_type.localgov_fact_box, paragraphs.paragraphs_type.localgov_featured_subsite, paragraphs.paragraphs_type.localgov_featured_teasers, paragraphs.paragraphs_type.localgov_key_contacts, paragraphs.paragraphs_type.localgov_key_facts, paragraphs.paragraphs_type.localgov_link_and_summary, paragraphs.paragraphs_type.localgov_media_with_text, paragraphs.paragraphs_type.localgov_quote, paragraphs.paragraphs_type.localgov_table, paragraphs.paragraphs_type.localgov_tabs, paragraphs.paragraphs_type.localgov_video), field.field.node.localgov_subsites_page.localgov_subsites_content (paragraphs.paragraphs_type.localgov_box_links_listing, paragraphs.paragraphs_type.localgov_call_out_box, paragraphs.paragraphs_type.localgov_documents, paragraphs.paragraphs_type.localgov_fact_box, paragraphs.paragraphs_type.localgov_featured_teasers, paragraphs.paragraphs_type.localgov_key_contacts, paragraphs.paragraphs_type.localgov_key_facts, paragraphs.paragraphs_type.localgov_link_and_summary, paragraphs.paragraphs_type.localgov_media_with_text, paragraphs.paragraphs_type.localgov_quote, paragraphs.paragraphs_type.localgov_table, paragraphs.paragraphs_type.localgov_tabs, paragraphs.paragraphs_type.localgov_video)`

Any suggestions greatly appreciated

**Comment by stephen-cox** [comment]
Hi @rosscullen It would appear your install can't find a LocalGov Paragraphs installation. This is a dependency of Subsites and so should have been installed along with everything else when installing LocalGov Drupal.

Did you install LocalGov Drupal and Subsites using Composer? Are you enabling Subsite through the UI or using Drush?

**Comment by rosscullen** [comment]
Thanks for reply @stephen-cox .... after installing composer, docker and Lando on fresh build of Ubuntu, I ran the following commands:
```
composer create-project localgovdrupal/localgov-project MY_PROJECT --no-install 
cd MY_PROJECT
lando start
lando composer install
lando drush si localgov -y
```

I'll try rebuild and see if that helps (and report back). Thanks

**Comment by rosscullen** [comment]
Got a bit further this time. Deleted project folder, rebooted, and started from scratch. 

Enabled the "localgov demo content" module (through the UI) and it began installing its dependencies... now getting the following:

`Unable to install LocalGov Subsites due to unmet dependencies: field.field.node.localgov_subsites_overview.localgov_subsites_content (paragraphs.paragraphs_type.localgov_key_contacts, paragraphs.paragraphs_type.localgov_key_facts, paragraphs.paragraphs_type.localgov_link_and_summary, paragraphs.paragraphs_type.localgov_media_with_text, paragraphs.paragraphs_type.localgov_quote, paragraphs.paragraphs_type.localgov_table, paragraphs.paragraphs_type.localgov_tabs, paragraphs.paragraphs_type.localgov_video)`

I did notice I did get 90 second timeout error on initial enablement, so had to re-do the process. I can try installing through drush tomorrow and see does that make a difference. Tks

**Comment by stephen-cox** [comment]
I think the problem here is enabling LocalGov Demo module through the UI. It enables so much stuff that it is hitting the PHP max execution time. To avoid this you'll either need to increase this or enable the module with Drush using `lando drush en localgov_demo`. If things have already failed you'll likely need to run the site install again as things will be in an inconsistent state.

**Comment by rosscullen** [comment]
Makes sense... Will give that a go... many thanks @stephen-cox 😊

**Comment by rosscullen** [comment]
Thanks @stephen-cox created the instance and installed the module via Drush... all appears working now :-) Many thanks for your help 👍🏻
