### ISSUE TITLE
Policy, Documentation: module, content type, field, view, dislay id ... naming

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov#47]
This is already formed, but not fully documented.

Suggestion at the moment:

 * content type, views, and module, prefix always descriptive name with `localgov_`
 * new, and refactored, fields drop `field_` prefix
 * fields with no shared storage `bundle` _ `descriptive_name`, fields with shared storage `descriptive_name`
 * new, and refactored, view display's get descriptive names (rather than `page_1` etc.)

**Comment by ekes** [comment]
https://github.com/localgovdrupal/localgov/wiki/Naming-conventions

**Comment by andybroomfield** [comment]
All fields are to use `localgov_` so we don't have to do field renaming again.
