### ISSUE TITLE
Patch error on updating localgovdrupal/localgov

### ISSUE THREAD

**Issue by ikit-claw** [localgovdrupal/localgov#476]
composer up localgovdrupal/localgov_base
Removing package drupal/core so that it can be re-installed and re-patched.
  - Removing drupal/core (9.3.22)
Deleting web/core - deleted
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
No patches supplied.
Gathering patches for dependencies. This might take a minute.
  - Installing drupal/core (9.3.22): Extracting archive
  - Applying patches for drupal/core
    https://www.drupal.org/files/issues/2021-01-12/3192365-3.patch (Fix tests running with paratest. See https://www.drupal.org/project/drupal/issues/3192365)
    https://www.drupal.org/files/issues/2022-06-17/2845144-67.patch (Users can't reference unpublished content even when they have access to it. See https://www.drupal.org/project/drupal/issues/2845144)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2022-06-17/2845144-67.patch

It would also be nice to move to core 9.4.x as some modules are marking 9.3.x as not compatible.

**Comment by markconroy** [comment]
Hi @ikit-claw 

This is not an issue with localgov_base. Localgov Base does not attempt to apply any patches. 

I think it's the localgovdrupal/localgov package that is trying to apply that patch. I'll move this issue to there. 

Thanks for reporting.

**Comment by ekes** [comment]
> It would also be nice to move to core 9.4.x as some modules are marking 9.3.x as not compatible.

The composer file with LGD doesn't specify anything other than it should be 9.x.x so you should be able to upgrade core.
And actually you problem might be that that patch applies to 9.4 and not 9.3... we should be supporting 9.3 till it's EOL so probably need to re-roll it for 9.3 :-(

**Comment by stephen-cox** [comment]
The failing patch works for Drupal 9.4 and 9.5. It fails on Drupal 9.3, but this version of Drupal is now unsupported (as of 2 days ago).

LocalGov Drupal certainly works with Drupal 9.4 and 9.5 so I suggest you [upgrade Drupal](https://www.drupal.org/docs/updating-drupal/updating-drupal-core-via-composer#s-update-drupal-core-code) if this is still a problem.
