### ISSUE TITLE
Security policy for LocalGov Drupal.org

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#479]
It was noted in a recent technical group meeting that we should have a clear policy on reporting security issues to LocalGov Drupal.

Drupal.org has a clear policy and process: https://www.drupal.org/docs/develop/issues/issue-procedures-and-etiquette/reporting-a-security-issue
 
We should

- [x] Write a policy. 
- [ ] Create a dedicated email address to report security issues
- [ ] Explore if we can set up a private repository for security issues.

@Adnan-cds @andybroomfield @ekes @stephen-cox any thoughts?

**Comment by finnlewis** [comment]
@msayoung any thouhgts?

**Comment by markconroy** [comment]
This might be easier if we mirrored our code to Drupal.org and piggybacked on how the Drupal project reports security issues. It would also mean our project could have security coverage from the Drupal security team.

**Comment by keelanfh** [comment]
Done in #483
