### ISSUE TITLE
Branch naming conventions - improve consistency

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#489]
Hello lovely people!

I would love to encourage a bit more consistency in our branch naming conventions.

We did write something down once upon a time: https://github.com/localgovdrupal/localgov/wiki/Git-branch-naming-conventions

This suggests branches should: 

- start with a prefix of feature/
- followed by the major version branch we branched from (eg 1.x or 2.x)
- continue with the issue number and a descriptive branch name.

For example: 

feature/2.x/30-default-documentation

I've seen a few new patterns evolving of late: 

https://github.com/localgovdrupal/localgov_scarfolk/tree/feature/1.x/drupal-10-support/22
https://github.com/localgovdrupal/localgov_microsites_group/tree/hotfix/update-github-actions-to-composer-install-later
https://github.com/localgovdrupal/localgov_alert_banner/tree/fix/227-oliveo-alertbanner-body-text
[https://github.com/localgovdrupal/localgov_microsites_group/tree/bug/2.x/256-dashboard-bug](https://github.com/localgovdrupal/localgov_microsites_group/pull/354)
https://github.com/localgovdrupal/localgov_microsites_group/tree/update/group_content_menu_ref

I'm not averse to updating our conventions, but it would great to have more consisteny.

I guess there a few variables here: 

## Prefix

Initially we suggested a single prefix for non dev branches of "feature/", which I think came from the GitFlow conventions.

We are now seeing "bug/", "fix/", "hotfix/", "update/"

What good arguments for different prefixes to branches? 

One reason to have a single branch prefix is autocomplete on the command line. Having to remember if the branch we're working on is a bug, fix, hotfix or feature can be an added step to remember. I can't think of a reason we would want to collect branches by type at the moment. 

Having said that, "fix" is a shorter word than "feature" so maybe it would be more efficient to use a shorter word. 

So do we think we can re-consolidate back to a single branch prefix or are there good reasons to have different prefixes?

## Major version branch

I can see this being useful in repos where we are maintaining multiple dev branches and release branches.  However in most repositories we have just a single dev and release branch, so this can become extra noise. Anyone got any strong opinions on this? I must admit I often forget to add the 2.x major branch version into a branch name when creating a new branch. What implications does this have? 

## continue with the issue number and a descriptive branch name

For me, having the issue number first followed by a descriptive name is really useful and saves me time. 

Typing "git checkout feature/479 [tab]" autocompletes to "git checkout feature/479-security-policy" quickly, so all I need to remember is the number. 

It also acts as a signpost for other developers that the issue is #479 and encourages us to create a new issue for a change if one does not yet exist. 

Any thoughts on that? 

Tagging @stephen-cox @ekes @msayoung @msayoung @Adnan-cds @andybroomfield for starters but welcome comments for anyone in the community.

**Comment by markconroy** [comment]
If we only use `feature` OR `bug` OR something else, we might as well not use this at all. If every branch is going to start with the word, I don't think we need that item.

In that case, branches would follow this pattern: `1.x/fixing-this-cool-thing/issue-number` or some variation

Actually, in terms of ordering things nicely, this might work: `1.x/issue-number/description`

**Comment by msayoung** [comment]
Personally I like using something to describe whether its a feature or bugfix - I don't mind which words we use but agree that we _should_ be consistent. 
I don't see the point if they are _all_ the same prefix.

The issue number is good, and the major version number is also helpful when there are different releases.

**Comment by andybroomfield** [comment]
I wonder how much of this is using auto suggested Github branch naming, eg. When creating a PR in the online editor or clicking create a branch on the issue, which look a lot like the branch names listed above.
Also some branches / PRs will be coming from others outside the organisation so they might not always have the right convention.

**Comment by finnlewis** [comment]
One plus of having feature branches with a prefix, even if only one, is to distinguish them from dev or release branches. 

On this repo we have the following dev and release branches: 

1.x
2.x
3.x
release-1.x
release-2.x

See https://github.com/localgovdrupal/localgov/branches/all

Then, according to our previous policy, we would have 

feature/2.x/123-fix-the-thing
feature/1.x/123-backport-the-thing
feature/3.x/124-shiny-new-thing

etc. 

So at a glance we can know that a given branch is some work in progress from a given dev branch. 

I wonder if it would also help with branch name pattern matching for Github workflows and other devops things ( I guess that could be gotten around with appropriate regex )

I remember reading once and agreeing with the sentiment that:

"It doesn't really matter which branching convention you use, it is just important to have one"

This is a useful comparison of GitFlow, GitHub Flow and GitlabFlow: https://www.flagship.io/git-branching-strategies/

There also seems to be a fair amount of love for categories of branches like bugfix / test / feature - which does sound potentially useful if used consistently. 

https://dev.to/varbsan/a-simplified-convention-for-naming-branches-and-commits-in-git-il4

https://hackernoon.com/git-branch-naming-convention-7-best-practices-to-follow-1c2l33g2

Does anyone have a strong preference for sticking with or changing what we've got written down on https://github.com/localgovdrupal/localgov/wiki/Git-branch-naming-conventions   ?

**Comment by ekes** [comment]
Issue number - yes.
Branch - helpful.

Categorisation the biggest difference seems to be:-
 * Longer term branches that take time (features), need more review before merging;
 * Bug fixes that are irritants that want merging at the regular time together to improve the product;
 * Hot fixes that are issues that need fixing out of normal process and applied asap.

**Comment by finnlewis** [comment]
How about we go with this: 

########################################################

## Git branch naming conventions

It is useful to follow consistent branch naming conventions to help with review and transparency (and autocomplete!).

In general for each repository, we will have one or more permanent development branches, named 1.x / 2.x / 3.x in line with the major versions that are being supported. 

When making changes, we branch off the permanent development branch with a temporary working branch that follows certain naming conventions. 

These temporary branches currently fall into the following categories: 

- feature: longer term branches that take time (features) and need more review before merging
- fix: fixes that are irritants that want merging at the regular time together to improve the product
- hotfix: issues that need fixing out of normal process and released asap

## Feature branches

When working on a feature or substantial changes, we branch off the main branch to create a `feature` branch.

The naming convention for feature branch is:

- start with a prefix of `feature/`
- follow the prefix by the major version branch we branched from (eg 1.x or 2.x) if relevant
- continue with the issue number and a descriptive branch name separated with hyphens.

For example: `feature/2.x/123-nice-new-thing`

## Fix (or bugfix) branches

When working to troubleshoot and fix a bug or problem in the codebase, we branch off the main branch to create a `fix` branch.

The naming convention for fix branch is:

- start with a prefix of `fix/`
- follow the prefix by the major version branch we branched from (eg 1.x or 2.x) if relevant
- continue with the issue number and a descriptive branch name separated with hyphens

For example: `fix/2.x/124-fix-views-listing-paragraph`

## Hotfix branches

For super urgent issue that need fixing out of normal process and released asap, we can prefix the branch with `hotfix`

The naming convention for fix branch is:

- start with a prefix of `hotfix`
- follow the prefix by the major version branch we branched from (eg 1.x or 2.x) if relevant
- continue with the issue number and a descriptive branch name separated with hyphens

For example: `hotfix/2.x/125-fix-composer-install-error`

**Comment by msayoung** [comment]
Looks good @finnlewis

**Comment by markconroy** [comment]
+1 from me.

**Comment by finnlewis** [comment]
Sounds like this is gaining traction...  @ekes @stephen-cox @andybroomfield how's this sounding to you?

**Comment by andybroomfield** [comment]
Thats fine, so it's no longer `2.x/feature/123-name-like-this` but instead `feature/2.x/123-name-like-this`

**Comment by stephen-cox** [comment]
:+1:

**Comment by ekes** [comment]
:+1:

**Comment by finnlewis** [comment]
Thanks everyone! I've updated https://github.com/localgovdrupal/localgov/wiki/Git-branch-naming-conventions 

I'll look at adding a link to that from the docs site.
