### ISSUE TITLE
Change default destination screen after login

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#512]
On login, users are presented with a mostly blank screen with their name on

![Image](https://user-images.githubusercontent.com/708140/227202491-d1eec514-f221-42bc-b46a-5e77aa282f23.png)

Most users are content designers, and the screen they need is /admin/content

![Image](https://user-images.githubusercontent.com/708140/227202530-094b90ff-2746-438e-a64f-37e324209cdf.png)

Let's discuss if making this change disadvantages other types of users

(Separately, does this remove the issue of having two different look and feels for admin, shown in the screenshots above)

**Comment by keelanfh** [comment]
I think the issue of having two different look and feels is still there - if a content designer clicks on any of those links (e.g. "Get Online at Home", they'll be back to the preview of the page (whether that's expected behaviour or not is another matter!) - and there are other ways of ending up back there too).

Nevertheless, I am very much in favour of this. Discoverability of the interface when a new user logs in for the first time is really important (think of how much work GOV.UK Notify did on this), and this really gets in the way.

**Comment by willguv** [comment]
@keelanfh just added #518

**Comment by willguv** [comment]
This has come up a few times now - mentioned to me and identified in Essex's admin usability research

@stephen-cox is there an easy fix here? Thanks

**Comment by stephen-cox** [comment]
The current behavior is the Drupal default, but it should be easy enough to override this and redirect to the content overview page.

We would want to double check the user has permissions to manage content as it's possible to add users without this permission. In this case we could either keep the default redirect or redirect to the homepage instead.

**Comment by ekes** [comment]
Just to point out the usual solution for this is designing the /user/{user} page to include links and lists (of content) that are likely to be what that particular user wants (based on their posts, or their role or even configurable).

**Comment by stephen-cox** [comment]
> Just to point out the usual solution for this is designing the /user/{user} page to include links and lists (of content) that are likely to be what that particular user wants (based on their posts, or their role or even configurable).

That's a good point, and some sites might have already done this, so if we were to add such a redirect we would want it to be configurable so it wasn't enabled for existing sites by default.

**Comment by willguv** [comment]
Thanks @ekes @stephen

My hunch is redirect for now (double checking for permissions), and write another card for later about redesigning the /user page

Let's hold fire and I'll check with Backlog Group

**Comment by willguv** [comment]
@stephen-cox so we're saying:

- for users with the ability to edit or create content (which roles?), the default destination screen should be /admin/content

We can make this change for new councils. Is this an easy change for all councils?

Many thanks

**Comment by stephen-cox** [comment]
To ensure this only works for new installs I think we'll have to create an admin setting where this can be turned on and off. It can then be set as on for new installed but defaults to off if the settings doesn't exist.

We can then add a redirect that checks whether the redirect is enabled and the user has the 'Access the Content overview page' permission and redirect them if they do.

**Comment by willguv** [comment]
@stephen-cox love it, thank you

**Comment by willguv** [comment]
The content group is happy with this change - 25 April

**Comment by andybroomfield** [comment]
Found this is the old BHCC repo
````php
/**
 * Admin form submit handler
 *
 * Redirect to the content overview page if user has permission.
 */
function _bhcc_admin_form_user_login_form_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if (\Drupal::currentUser()->hasPermission('access content overview')) {
    $form_state->setRedirect('view.content.page_1');
  }
}
````

Theres also [Login And Logout Redirect Per Role](https://www.drupal.org/project/login_redirect_per_role)

**Comment by stephen-cox** [comment]
@willguv I've created a simple module that when enabled redirects users to the content overview page when logged in. PR for this at #556.

I've deployed it to the test site https://test.localgovdrupal.org/. Does this do what you wanted here?

I've added a simple settings page (https://test.localgovdrupal.org/admin/config/system/localgov_login_redirect) which allows the redirect to be turned off and changed to somewhere else if desired.

I decided to put this in it's own module as it allows us to easily deploy to new sites, but also easy for sites already using LocalGov Drupal to turn it on.

**Comment by keelanfh** [comment]
This looks great to me after trying on the test site, it just makes so much sense!

**Comment by willguv** [comment]
Seconded! Works perfectly and it's great councils can customise as they wish

Thanks @stephen-cox, let's get this deployed!

**Comment by willguv** [comment]
Hi @stephen-cox is this deployed? Thanks

**Comment by ekes** [comment]
It's in release https://github.com/localgovdrupal/localgov/releases/tag/2.3.18
