### ISSUE TITLE
Make child pages presentation consistent across different content formats

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#515]
Child pages are presented inconsistently across different content formats:

- On service landing and sub-landing pages, they're in a "child pages" tab
- On step by step overview and guide overview, there is no tab and they're called "Step by step pages" and "Guide pages"

There may be other inconsistencies

Let's discuss and refine this card

**Comment by keelanfh** [comment]
Same applies to parent relationships, briefly mentioned in https://github.com/localgovdrupal/localgov/issues/487

Incidentally, we have removed tabs from most content types for a few reasons:
* problems on smaller displays/split screen workflows that some of our content designers use
* planning ahead, the icons in the CKEditor 5 WYSIWYG take up more space, so the space taken up by the tabbed layout reduces the space available and shunts more of the icons into a menu
* it adds an additional menu for content editors to interact with and discover information that might be important

**Comment by andybroomfield** [comment]
I think the child pages in those locations though serve two different purposes.
One is building a section navigation, the other is building explicit parent / child relationships.
So in a sense, its expected to be different, you wouldn't nesecarilly put in an arbitriary page or an external site ina guide or step by step, but you might (and BHCC often does) do this on a sub landing page section.
So in a way, it does make sense to distinguise them for there purposes (Child page being any page, but guide / step by step being explicit what is going here.

That is unless the desire here is to have a unified way of defining page hirechy, in which case artibitury pages should be allowable and that sounds like a big step change in how these content types work.

**Comment by willguv** [comment]
@benhillsjones, Angie, Elizabeth say this isn't really an issue

**Comment by willguv** [comment]
Not considered an issue so closing
