### ISSUE TITLE
Address the two admin look and feels issue - DUPLICATE

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#518]
Content designers are presented with two admin look and feels - it's disorientating for new and long standing users alike

The first is encountered when users log in, on page previews and potentially elsewhere

![Image](https://user-images.githubusercontent.com/708140/227530124-944046cc-0768-46e5-bb03-eb4c960205a3.png)

The second is first seen on /admin/content, then continues on to content editing pages

![Image](https://user-images.githubusercontent.com/708140/227530326-8cc947c1-588b-4232-af44-3430f5fba6ad.png)

We need to:

- discuss whether this is OK (I think it isn't)
- identify everywhere this happens
- estimate the effort to fix

(Thinking: Is this caused by the admin theme choice?)

**Comment by keelanfh** [comment]
Again, some related questions here:

* Do we want editors to be able to edit content in two different ways - inline with the content, and in the admin interface? If so, then we might want to bring some consistency in how toolbars appear. If this isn't something desirable, it becomes more about managing the transition between the two 'modes'.

* There is inconsistency even just solely in the content view. Clicking "Edit" in the top right adds a series of small icons to allow inline editing. Clicking "Edit" in the series of "View, Edit, Delete, ..." brings you into the admin interface. It's really not intuitive that two links with the same text do two different things - and not best practice for accessibility:

> It is also a best practice for links with different purposes and destinations to have different link text. ([SC 2.4.4](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html))

![image](https://user-images.githubusercontent.com/19519457/227548013-b305b217-f4fa-4d4c-a3ab-0c4de9867bbd.png)

* Our content designers have found it confusing that information not visible to end users can appear in the 'preview' of the site. The most obvious example is the content moderation information. Especially for content designers that are used to working in headless CMSs, it's quite disconcerting to see administrative information in the middle of content - again there's a question of whether these things should be possible in two places.

![image](https://user-images.githubusercontent.com/19519457/227543972-ef038ff2-245d-40a5-a1fe-a8ca768df25b.png)

My personal view is that having two different interfaces for editing is unhelpful. It isn't obvious that some tasks are possible to complete in one of the interfaces, and not in the other.

**Comment by keelanfh** [comment]
When dealing with things like this, I often come back to an underlying user need "to view unpublished content as it will appear to a resident".

Things like:
- the inline editor
- any non-public information being visible in the content view
- archived content being visible in the view
- even the toolbars themselves

get in the way of that. 

So even when some of these things have benefit - and may make it easier to fulfil other needs, I tend to lean towards removing them, because there isn't another easy way of meeting that (common, important) need.

**Comment by andybroomfield** [comment]
From how BHCC does this

We enable the contrib [Gin Toolbar module](https://www.drupal.org/project/gin_toolbar) to keep the same toolbar across the site, and we have the secondary toolbar temp disabled (though there are some features we want to look at). We also disabled quickedit so editing is always through edit screens. We moved the tabs to the bottom so they are explicit edit buttons. see below.

<img width="1287" alt="Screenshot 2023-04-04 at 11 10 15 am" src="https://user-images.githubusercontent.com/1467480/229765218-89e356b8-2db5-4f6c-b08c-86fbe05a25f1.png">

Front end.

<img width="1317" alt="Screenshot 2023-04-04 at 11 10 29 am" src="https://user-images.githubusercontent.com/1467480/229765243-0b19bdc2-6e39-45e7-9241-9056f527f887.png">

Admin screen.

You can also enable [gin login module](https://www.drupal.org/project/gin_login) to make it explicit that users are entering admin mode.

The alternative is to use Claro as the admin theme (like microsites) which gives you the same toolbar.
I don't think its feasible to extend localgov_base to be used as an admin theme.

**Comment by willguv** [comment]
@andybroomfield I love these changes - they look a lot better and feels like they can be done quite quickly

Are you coming to the next Backlog group on 12th? It would be great if you could give us a quick demo

Copying @stephen-cox on feasibility of including these changes in core

Thanks both

**Comment by stephen-cox** [comment]
Adding and enabling the Gin Toolbar and Login modules makes sense and is easy to do.

Moving the tabs to the bottom is easy enough to do in the theme.

**Comment by willguv** [comment]
Superseded by #525 and #526, so closing
