### ISSUE TITLE
Elections v3

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#519]
The Local Elections are happening on 4th May 2023 and here's a list of [councils taking part](https://www.electoralcommission.org.uk/i-am-a/voter/local-elections-england-may-2023)

Elections functionality was built by Rohallion ([repo](https://gitlab.com/rohallion-public/localgov_elections_reporting)) and the agency has given us the OK to use it

It was [successfully used](https://www.cumberland.gov.uk/election/cumberland-council-election-5-may-2022) by Cumberland Council last May. Cumberland is an LGD member, and one of the two new unitary councils replacing Cumbria

![Image](https://user-images.githubusercontent.com/708140/227568639-6ae84774-7188-475e-baa9-8464df3a9046.png)

All councils hold elections, so the core ideally needs this. Questions:

- Should we do this now? (13 LGD councils are holding elections - see below)
- Does this functionality meet common needs in part or total? (consider a lightweight product and technical assessment)

**Comment by markconroy** [comment]
This looks like a great idea.

**Comment by willguv** [comment]
@finnlewis @stephen-cox can we get elections installed somewhere so the content group can have a look?

If we do choose to offer this, there's not a lot of time

Local elections are 4 May, and councils will likely need a couple of weeks to install and test

**Comment by willguv** [comment]
[Councils holding elections in May 2023](https://www.electoralcommission.org.uk/i-am-a/voter/local-elections-england-may-2023)

Of these 13 are LocalGov Drupal councils:

Bath and North East Somerset
Blackburn with Darwen
Bracknell Forest
Brighton and Hove
East Hampshire
Elmbridge
Epping Forest
Hart
Milton Keynes
Newcastle
North Kesteven
Redcar and Cleveland
Wirral Woking (covered by Wirral?)

(not all of these sites are live)

**Comment by stephen-cox** [comment]
@willguv I just looked at installing this on test.localgovdrupal.org.

There's an error enabling the module for which I've created a ticket in the issue tracker for the module: https://gitlab.com/rohallion-public/localgov_elections_reporting/-/issues/4

The module has a lot of dependencies and would need to be reviewed by the Technical Governance Group before it could be included in the distribution by default, but this wouldn't stop councils installing it in their sites.

We could certainly move the code into the LocalGov Drupal GitHub organization if desired.

**Comment by willguv** [comment]
Thanks for doing this Stephen. I'll find out from the content group if they want to try this functionality

If we were going to include this in our org, do you think it's comfortable in the next 2-3 weeks or would that be a rush?

**Comment by stephen-cox** [comment]
I don't think there are any issues moving the code as long as Rohallion were happy moving it from their GitLab account into https://github.com/localgovdrupal/. Providing there's agreement this can be done quickly. Probably unlikely to have the code reviewed fully in that time though.

**Comment by willguv** [comment]
Thanks Stephen, feels like we'd be rushing it for May

I can point these councils to Gitlab and see if any are able to use it

**Comment by MatthewWilkes** [comment]
After @willguv shared this, I've taken a bit of a look around to understand how it's used. It looks like a really useful set of functionality to include. I'm sure there are a few backlog items from having trialled this in last year's elections, but there's also some (hopefully) low-effort, high-impact things that I think we'd want to look at while bringing this into core. 

1.  The chart at the top of https://www.cumberland.gov.uk/voting-and-elections/local-election-results is currently showing 0's, while the same chart at https://www.cumberland.gov.uk/election/cumberland-council-election-5-may-2022 is working. 
2. Also on that pair of page, there's a table of results which is missing some styling in the first URL. Perhaps a missing library attachment?
3. On the ward details pages (e.g. https://www.cumberland.gov.uk/election/cumberland-council-election-5-may-2022/aspatria ) there's a black-on-navy heading. There's styling to fix this for `.view-id-election_results` but not for `.view-id-district_results`
4. The search results are a bit excessive, they pull back the election result charts and tables (again, missing styling) for all relevant elections if you search for a ward

There's also a couple of content issues that we should give Cumberland a heads-up on:
1. On https://www.cumberland.gov.uk/voting-and-elections-0/election-results there's a "Council election ward results" link that 404's. 
2. There's a section duplication, with https://www.cumberland.gov.uk/voting-and-elections/local-election-results and https://www.cumberland.gov.uk/voting-and-elections-0/local-election-results. The version with -0 404's on https://www.cumberland.gov.uk/voting-and-elections-0 but https://www.cumberland.gov.uk/voting-and-elections works fine.
3. https://www.cumberland.gov.uk/voting-and-elections/local-election-results/parish-and-town-council-election-results has "THIS NEEDS WORK" in its description, but is the 4th search result for "election"

**Comment by willguv** [comment]
Michael, Newcastle: 

- What about non all out elections?
- Social media integration

Will: Not sure about PR

Ben: Accessibility checking

---
Notes from Michael

From Slack: https://localgovdrupal.slack.com/archives/C03NCARGVHP/p1665674627205639
Gitlab: https://gitlab.com/rohallion-public/localgov_elections_reporting
Videos: https://www.loom.com/share/f72c3aee6c9d42ceb6a97f8e0585b95d

https://www.loom.com/share/0c7945aa67044d8ba4dd0ed73ab36191

**Comment by willguv** [comment]
@stephen-cox could you install this somewhere where it's not going to be overwritten please? I'm planning to start thinking about what's needed for other election types next week all being well

Thanks

**Comment by willguv** [comment]
Please add to product - thanks

**Comment by stephen-cox** [comment]
@willguv This has been deployed to the product site.

**Comment by willguv** [comment]
Hi @dedavidson great to catch up yesterday. Craig said he'll set aside some of your time for improvements so I'll start listing thoughts here to discuss

**Comment by willguv** [comment]
This work is being covered on a separate Trello board

**Comment by aaronhirtenstein** [comment]
Link to Elections Trello: https://trello.com/b/0UpNrJr0/lgd-elections

**Comment by ekes** [comment]
> Link to Elections Trello: https://trello.com/b/0UpNrJr0/lgd-elections

This is a private Trello. I think this is problematic.

**Comment by aaronhirtenstein** [comment]
Yeah I've asked @willguv if we can move things into Github for visibility.

**Comment by willguv** [comment]
Also look at 

https://geoportal.statistics.gov.uk/search?collection=Dataset&q=wards
https://geoportal.statistics.gov.uk/datasets/a2c204fedefe4120ac93f062c647bdcb_0/explore

**Comment by willguv** [comment]
Follow along at https://trello.com/b/0UpNrJr0/lgd-elections

**Comment by markconroy** [comment]
Any chance we could make this a project at localgovdrupal/localgov_elections and use the issues there instead of Trello?

**Comment by willguv** [comment]
We're barely using Trello now - it was a high level view to scope out the work

Very happy to track issues here
