### ISSUE TITLE
Enable Gin login and toolbar for new users

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#525]
Following on from #518, the Backlog Group has agreed that:

- Gin login and toolbar should be enabled by default 
- We should communicate this feature to existing users, so they can enable it if they wish

**Comment by willguv** [comment]
@stephen-cox is this OK to implement?

**Comment by willguv** [comment]
@stephen-cox I've installed both on the demo site as a test - very simple to do and much improved experience

Are you able to do this work soon? Many thanks

**Comment by stephen-cox** [comment]
PR for this here https://github.com/localgovdrupal/localgov/pull/530

**Comment by willguv** [comment]
Cheers @stephen-cox

**Comment by willguv** [comment]
### How to get this

Please ask your dev or supplier to make these changes so they aren’t overwritten by future releases.

If you have a test site where these changes won’t matter, feel free to have a play.

- Log in as usual and click "extend" in the toolbar (if you can't see this ask your dev)

![Image](https://user-images.githubusercontent.com/708140/234221457-865dc5b5-e346-45a6-916d-5c7d2ee718e8.png)

- Search for "gin" (even if it's a bit early in the morning)

![Image](https://user-images.githubusercontent.com/708140/234221574-60fabaf6-d0b1-497c-beb1-f67ba1ce2eae.png)

- Check "Gin Login" and "Gin Toolbar" then click "Install"

- After a few seconds you should see the Gin Toolbar across all content views. If you log out, and go to /user you'll see the new log in screen

**Comment by keelanfh** [comment]
Small thing, but wouldn't this normally be done by a dev so that it can be committed to config and consistent across dev/staging/live environments? Otherwise I think it would be overwritten when you make a new code deployment.

We (as 'content designers' or similar) tend not to make changes like this in the admin interface, but curious to know if other councils do it differently.

**Comment by willguv** [comment]
I guess it depends on team size/ skills. We'd ask a dev to do it across all environments, will be different elsewhere. For now this is a test so pick an environment where it doesn't matter

**Comment by keelanfh** [comment]
Ah okay, fair enough, didn't realise it was a test, thanks.

**Comment by keelanfh** [comment]
Ah okay, fair enough, didn't realise it was a test, thanks.

**Comment by andybroomfield** [comment]
@keelanfh Yes this would be a dev change, as you suggest this needs to be commited to config to prevent being overwritten. The PR that @stephen-cox  made enables this by default for all new users, however as we won't know if others have made their own settings (eg. installing a different admin theme) we havn't updated the config for everyone, so existing councils will need to make this change themselves if they want it.

**Comment by willguv** [comment]
Clarified above. Think there's a general rule on this board - everything's a test unless said otherwise

**Comment by willguv** [comment]
hi @stephen-cox I can't find the issue where Gin login was identified as breaking things, so posting here

Can you let me know when you've had chance to look at this? Many thanks

**Comment by stephen-cox** [comment]
> I can't find the issue where Gin login was identified as breaking things, so posting here

This looks to be fixed. It was happening with re-installs of the demo site, but is working fine after updating the modules.

**Comment by willguv** [comment]
Thanks!
