### ISSUE TITLE
Move editing buttons to the bottom of the admin view

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#526]
Brighton & Hove has made this change 

![Image](https://user-images.githubusercontent.com/708140/231484040-4c52bf89-7280-4744-971d-1a185e872447.png)

**Comment by willguv** [comment]
Thanks @andybroomfield for sharing

@benhillsjones and content group, would you discuss if this is needed? Many thanks

**Comment by markconroy** [comment]
I think this is a change that probably should be made on a case-by-case basis. I have a feeling 50% of people will want it at the top and 50% will want it at the bottom and another 50% will want a "Tools" button that shows/hides all that stuff and slides it out from an off-canvas region only when needed.

**Comment by willguv** [comment]
Content group is used to what it's used to - 25 April

**Comment by keelanfh** [comment]
Linking #574 as that accessibility issue might be fixed by this change (though it could be fixed separately).

**Comment by andybroomfield** [comment]
<img width="1342" alt="Screenshot 2023-06-29 at 3 00 22 pm" src="https://github.com/localgovdrupal/localgov/assets/1467480/de5fbe68-bc65-4838-88f1-070b188f108f">

**Comment by keelanfh** [comment]
just to note, the accessibility issue flagged was for text only being increased to 200%, not zoom of 200%. Zoom of 200% works fine.

**Comment by andybroomfield** [comment]
<img width="1257" alt="Screenshot 2023-06-29 at 3 17 46 pm" src="https://github.com/localgovdrupal/localgov/assets/1467480/b560880c-467d-4db8-b6c4-b8113ad650f8">

My bad, here is Firefox text enlarged to 200% with the tabs at the bottom.

**Comment by andybroomfield** [comment]
Assuming closed.
