### ISSUE TITLE
Document changes to config, content types, fields etc. Add wiki page (or similar)

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#53]

**Comment by andybroomfield** [comment]
Its [here](https://localgovdrupal.org/config/content-types.html)!

But people do need to add them, so I will keep this issue open.

**Comment by msayoung** [comment]
I think its here now: https://docs.localgovdrupal.org/devs/general/content-types.html 
Is this still needed @andybroomfield ?

**Comment by andybroomfield** [comment]
Looks complete to me @msayoung
