### ISSUE TITLE
Change to when tabs are shown

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#538]
Following on from [Andy's comment](https://github.com/localgovdrupal/localgov/issues/487#issuecomment-1514413600)

> For the details group / tabs, we changed the switch between then to 1138px, so narrow viewports use detail dropdowns between the sections instead of vertical tabs.

Let's consider the impact of this change

**Comment by finnlewis** [comment]
Note; this is configuration in the tab group. Setting up vertical tabs, allows you to set the breakpoint. 



![Image](https://github.com/localgovdrupal/localgov/assets/326588/ebd51595-b3d9-459a-8e5f-b95f7e0ec022)

**Comment by finnlewis** [comment]
Note: this would probably just be for new installs.

Tasks:

- [ ] identify all vertical tab groups in the LocalGov Drupal distribution.
- [ ] Update configuration for each to 1138px breakpoint
- [ ] possibly update the README.md for each repo
- [ ] create pull requests in each repo with recommended release notes.

**Comment by agile-simon** [comment]
Pull requests

Directories
https://github.com/localgovdrupal/localgov_directories/pull/329

News
https://github.com/localgovdrupal/localgov_news/pull/100

Services
https://github.com/localgovdrupal/localgov_services/pull/235

Subsites
https://github.com/localgovdrupal/localgov_subsites/pull/136

**Comment by willguv** [comment]
@stephen-cox please review Simon's PRs - thanks

**Comment by willguv** [comment]
@stephen-cox have you reviewed/ finished these PRs? Thanks

**Comment by stephen-cox** [comment]
Hi @willguv - these are all merged apart from https://github.com/localgovdrupal/localgov_services/pull/235, which has test failures that we haven't got to the bottom of.

**Comment by alexjohntweedie** [comment]
Yes

**Comment by markconroy** [comment]
I've merged the latest 2.x into the PR at [#235](https://github.com/localgovdrupal/localgov_services/pull/235)

All tests are passing now, and the PR is working. I'm going to mark it as approved.

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by mccrodp** [comment]
Hey @markconroy, what remains as an open action in this issue following your merge above? It wasn't clear to me if anything else is required or if this can be closed now. Thanks.

**Comment by markconroy** [comment]
I think we can close this one if all the PRs are merged.
