### ISSUE TITLE
Add basic media handling to localgov_core.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#54]
Media uploading is currently done using IMCE (https://www.drupal.org/project/imce). We should be using core media for this, possibly with a basic entity browser setup.

I'm assuming this will be required by most modules and so should go in localgov_core, but we could put it in its own module.

**Comment by Adnan-cds** [comment]
Hi Finn,
As discussed, I am having a go at it. @finnlewis

**Comment by finnlewis** [comment]
This is merged in for now. 
But there is still discussion about namespacing media config to localgov_ @ekes @Adnan-cds
