### ISSUE TITLE
PHP Fatal error NewsPageTest.php on line 54

### ISSUE THREAD

**Issue by 2dareis2do** [localgovdrupal/localgov#541]
PHP Fatal error:  Declaration of Drupal\Tests\localgov_news\Functional\NewsPageTest::setUp() must be compatible with Drupal\Tests\BrowserTestBase::setUp(): void in /var/www/html/web/modules/contrib/localgov_news/tests/src/Functional/NewsPageTest.php on line 54

was 

`  protected function setUp() {
`

should be 

`  protected function setUp(): void {
`

same for NewsSearchTest::setUp and PromotedNewsWidgetTest::setUp

**Comment by andybroomfield** [comment]
Looks like this has been done
