### ISSUE TITLE
Block concurrent editing

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#543]
This has been raised by @keelanfh and others. I'll confirm with the content group this need is common

Two users should not be able to edit content at the same time

Ideally...

- /admin/content and other list pages (eg /admin/content/alert-banner) should show content that is locked and name of user that's editing)

- there should be some way to override a lock

This module looks like a good fit: https://www.drupal.org/project/content_lock

**Comment by willguv** [comment]
Andy recommends the sub module that clears out locks on chron (should be already included). Also a permission that be assigned to editors to break locks

Stephen: there's an admin overhead so maybe point to it rather than include for all? Can play havoc with autosaving

Keelan: Remembers 2 year old content locks in previous system, one admin because people had left

Finn: difference between installing and making easy to configure, vs we recommend. Check with content group

**Comment by willguv** [comment]
Content group 23 May says this is a good idea. General feeling was that this feature should really be included

@stephen-cox could this be installed on test please

**Comment by stephen-cox** [comment]
@willguv I've deployed Content Lock to the test site: https://test.localgovdrupal.org

**Comment by willguv** [comment]
Having a look now, thanks @stephen-cox. Posting any issues as I see them

1) Status messages need a bit of work. Don't think any headings are needed

![Image](https://github.com/localgovdrupal/localgov/assets/708140/07032048-99bf-4bbd-ba4e-df6323a3b24f)

Locked by [name] [time] ago


![Image](https://github.com/localgovdrupal/localgov/assets/708140/68a56b4b-48a6-4e97-8fa5-e697ad85415c)

Content locked. Remember to save or unlock before you leave


![Image](https://github.com/localgovdrupal/localgov/assets/708140/043c0a52-1a31-4017-904a-7848433bf1d2)


![Image](https://github.com/localgovdrupal/localgov/assets/708140/2374c4a4-97a1-47df-8c73-ae2e27321683)



2) First article in this list is being edited and so is locked. It's not clear without clicking on the article


![Image](https://github.com/localgovdrupal/localgov/assets/708140/d341acf8-a5dc-4327-a78d-2e5c2aad5ddb)

**Comment by willguv** [comment]
At BG group today we agreed:

1) Add code to distribution, default off. In core rather than workflow

2) Let's see how easy it is to:

- configure status messages @stephen-cox to find out
- add "locked by" messages to /content view

Consider including "content lock time out" sub module 

3) Write "how to" documentation. Consider "how to extend LGD" section

**Comment by willguv** [comment]
@stephen-cox am really keen to get this done in the next month, in time for product update 3

Could you have a look at the points in (ii) above please? Also do you have 10 mins to show me the content lock time out controls?

Thanks, Will

**Comment by stephen-cox** [comment]
@willguv There's a PR for this here #580.

It just installs the Content Lock module and will do this for any sites updating LGD as well as new installs.

> do you have 10 mins to show me the content lock time out controls?

Happy to show you them, but they're very simple. You can see them here: https://test.localgovdrupal.org/admin/config/content/content_lock/timeout

![image](https://github.com/localgovdrupal/localgov/assets/7189914/faad056b-68f7-4669-a5f4-b0de332b0f7c)

On the questions:

It's not straightforward to override the messages displayed by this module. They are hardcoded into the module in a Drupal service. It's may be possible to inject our own service that extends the ContentLock class and changes these messages. We could also just patch the module, but for either option the Content Lock module could introduce changes that break our changes and so maintaining them could be a pain.

It is possible to add the user who locked the content to the main content overview, but I would be wary about changing this. We certainly don't want to do this for existing installs. Changing this for new installs is possible, but would be a little complex. The module provides a locked content view which includes this sort if information (https://test.localgovdrupal.org/admin/content/locked-content). Would making this more visible by adding it to the content menu and tabs be sufficient?

**Comment by willguv** [comment]
@stephen-cox thanks for doing this

I don't want to introduce customisations that we need to keep an eye on. Instead is it possible to submit a PR to the module maintainer that allows custom wording to be added? If that's not lots of effort I'd be keen to look at that

Adding the locked content view: that's a good compromise. Could it go in the oveview/ moderated content/ approvals dashboard line at the end? Label would be "Locked"

**Comment by willguv** [comment]
Hi @stephen-cox any thoughts on the above please? Would be good to know the plan before today's backlog group - many thanks

**Comment by stephen-cox** [comment]
@willguv Adding the ability to edit messages will be quite time consuming as there will need to be an admin UI for this that supports tokens (so things like usernames can be added).

Much easier to add some menu items for the view when it's enabled.

**Comment by willguv** [comment]
Add "Locked" to the content sub tabs ie the line with overview on

**Comment by stephen-cox** [comment]
@willguv This is now on the test site for you to have a look at: https://test.localgovdrupal.org/admin/content/locked-content

I've create a wrapper module (localgov_content_lock) which enables and configures the content_lock and content_lock_timeout modules. There's some basic docs here https://github.com/localgovdrupal/localgov/blob/feature/2.x/543-content-locl/modules/localgov_content_lock/README.md

**Comment by willguv** [comment]
@stephen-cox I'm getting page not found for https://test.localgovdrupal.org/admin/content/locked-content

**Comment by stephen-cox** [comment]
@willguv I've enabled the LocalGov Content Lock module. As the test site gets reset every night this will have to be done whenever you want to test things it

**Comment by willguv** [comment]
@stephen-cox just tried it, looks great thank you

I would still like to tidy up the notification messages as they're very verbose, but I guess we'll have to let that go

Could we a message to the module issue queue about this?
