### ISSUE TITLE
Agree policy for adding features to LGD - DUPLICATE

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#544]
Following on from @finnlewis post https://github.com/localgovdrupal/localgov/issues/466#issuecomment-1399251736 

> This issue has highlighted the question of how we decide what features to add and enable by default in the distribution.
> 
> I've started drafting a policy here:
> https://github.com/localgovdrupal/localgov/wiki/%5BDraft%5D-Policy-for-adding-a-new-feature,-functionality-or-modules-to-LocalGov-Drupal
> 
> It would be good to answer the questions raised so far on this issue:
> 
> 1. Does more than one council want this feature? / Does a significant proportion of our users want this feature?
> 2. Can the feature be disabled after installation without any dependency problems?
> 3. Does the product group / product owner / product lead want to prioritise this feature?
> 4. Will this enhancement be communicated to users with an existing installation? (e.g. release notes / README.md / drupal_set_message )
> 

I'm keen that we develop product principles, and this is part of it

Let's discuss as a Backlog group and add any comments - thanks Finn for getting the ball rolling

**Comment by andybroomfield** [comment]
Would we be looking at a scoring system, or just something more generic?
Are we looking at the main localgov profile being more of a framework that councils build with, or more of a finished product whose feautre set is static?

**Comment by andybroomfield** [comment]
Also need to consider a modules securirty support status, release state (activly maintaned, fixes only, abandoned?), Is it a full release, or beta / alpha / dev version only? does it need patches to work correctly?
Are there other modules or processes a council is using / would use instead and would they raise complications with the proposed module?
Does any feature change / module also change the hosting requirements (updates to apache / PHP / MySQL) or dramatically increase number of website requests.

**Comment by willguv** [comment]
Thanks for your thoughts @andybroomfield - let's discuss today. Think we also need a tech group view

**Comment by willguv** [comment]
Closing this in favour of https://github.com/localgovdrupal/localgov/issues/488
