### ISSUE TITLE
Adding non-existent permissions to a role is not allowed when installing profile

### ISSUE THREAD

**Issue by 2dareis2do** [localgovdrupal/localgov#545]
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /core/install.php?langcode=en&profile=localgov&id=1&op=do_nojs&op=do
StatusText: OK
ResponseText: RuntimeException: Adding non-existent permissions to a role is not allowed. The incorrect permissions are "create document media", "create image media", "create remote_video media", "delete own document media", "delete own image media", "delete own remote_video media", "edit any document media", "edit any image media", "edit any remote_video media", "edit own document media", "edit own image media", "edit own remote_video media". in Drupal\user\Entity\Role->calculateDependencies() (line 207 of /var/www/html/web/core/modules/user/src/Entity/Role.php).

see html/web/modules/contrib/localgov_core/modules/localgov_media/localgov_media.module

**Comment by keelanfh** [comment]
Are you attempting to install LocalGov Drupal with Drupal 10?

LocalGov Drupal currently only supports Drupal 9.

For this specific issue, there is an issue for this at https://github.com/localgovdrupal/localgov/issues/531 as part of the Drupal 10 compatibility work.

**Comment by 2dareis2do** [comment]
Yes I think it is Drupal 10. Just following instructions here. 

https://docs.localgovdrupal.org/devs/getting-started/working-with-ddev.html#installing-localgov-drupal-locally-with-composer-and-ddev

commented out those permissions and was able to complete installation of install profile.

Also paratest's fail when running run-tests.sh

``` Line   modules/contrib/localgov_services/modules/localgov_services_status/src/ServiceStatus.php  
 ------ ------------------------------------------------------------------------------------------ 
  138    Relying on entity queries to check access by                                              
         default is deprecated in drupal:9.2.0 and an error                                        
         will be thrown from drupal:10.0.0. Call                                                   
         \Drupal\Core\Entity\Query\QueryInterface::accessCheck()                                   
         with TRUE or FALSE to specify whether access                                              
         should be checked.                                                                        
         💡 See https://www.drupal.org/node/3201242                                                
 ------ ------------------------------------------------------------------------------------------ 


                                                             
 [ERROR] Found 1 error                                       
                                                             

Running tests
ParaTest v6.9.1 upon PHPUnit 9.6.7 by Sebastian Bergmann and contributors.

...............................................................  63 / 157 ( 40%)
EE.PHP Fatal error:  Uncaught AssertionError: assert(count($nodes) === 1) in /var/www/html/vendor/brianium/paratest/src/Logging/JUnit/TestCase.php:79```

**Comment by stephen-cox** [comment]
Drupal 10 support is still in development and doesn't work fully at the moment.

The 3.x branch installs Drupal 10, but unless you're interested in helping fix all the Drupal 10 bugs you should be using the 2.x branch which installs Drupal 9.

The current status of Drupal 10 support is detailed on this issue: https://github.com/localgovdrupal/localgov/issues/480

**Comment by finnlewis** [comment]
> Yes I think it is Drupal 10. Just following instructions here.
> 
> https://docs.localgovdrupal.org/devs/getting-started/working-with-ddev.html#installing-localgov-drupal-locally-with-composer-and-ddev
> 

I'll check the docs there, they should probably be updated to install the 2.x branch by default.

**Comment by 2dareis2do** [comment]
Thanks. 

Not sure what happened. Will make sure I stick with 2.x for now

**Comment by 2dareis2do** [comment]
Not sure why but when I type `lando composer install` it tells me that composer install is required.

As I have composer installed locally, I am just running composer install for now.

Also in the install profile there is a patch than cannot be applied:

```
Applying patches for drupal/core
    https://www.drupal.org/files/issues/2021-01-12/3192365-3.patch (Fix tests running with paratest. See https://www.drupal.org/project/drupal/issues/3192365)
   Could not apply patch! Skipping. The error was: The process "patch '-p1' --no-backup-if-mismatch -d 'web/core' < '/var/folders/pn/ngzsxydj2ng4d1yjdflg6tx40000gn/T/64526479e2479.patch'" exceeded the timeout of 300 seconds.
```

and also 

```
https://www.drupal.org/files/issues/2022-06-17/2845144-67.patch (Users can't reference unpublished content even when they have access to it. See https://www.drupal.org/project/drupal/issues/2845144)
   Could not apply patch! Skipping. The error was: The process "patch '-p1' --no-backup-if-mismatch -d 'web/core' < '/var/folders/pn/ngzsxydj2ng4d1yjdflg6tx40000gn/T/645265a61a8ed.patch'" exceeded the timeout of 300 seconds.
```
   
   looks like both these issues are closed now
   
   Also 
```
Applying patches for drupal/media_library_edit
    https://git.drupalcode.org/issue/media_library_edit-3315757/-/commit/9b590f1d93d8c0f750c50d90c422343ecf5e9e72.patch (Fix schema #3315757)
   Could not apply patch! Skipping. The error was: The process "patch '-p1' --no-backup-if-mismatch -d 'web/modules/contrib/media_library_edit' < '/var/folders/pn/ngzsxydj2ng4d1yjdflg6tx40000gn/T/645266d275304.patch'" exceeded the timeout of 300 seconds.
```

in localgov_paragraphs 

and 
```
Applying patches for drupal/gin_login
    https://www.drupal.org/files/issues/2021-01-13/gin_login-config_schema-3192526-8.patch (Fix schema for gin_toolbar, see https://www.drupal.org/project/gin_login/issues/3192526)
   Could not apply patch! Skipping. The error was: The process "patch '-p1' --no-backup-if-mismatch -d 'web/modules/contrib/gin_login' < '/var/folders/pn/ngzsxydj2ng4d1yjdflg6tx40000gn/T/64526804bb620.patch'" exceeded the timeout of 300 seconds.
```
   
 I am also having a problem running `lando drush si localgov -y` 
 
 ```
lando drush si localgov -y
PHP Fatal error:  Uncaught Exception: Could not locate autoload.php. cwd is /app; __DIR__ is /app/vendor/drush/drush in /app/vendor/drush/drush/drush.php:58
Stack trace:
#0 /app/vendor/drush/drush/drush(4): require()
#1 /app/bin/drush(120): include('/app/vendor/dru...')
#2 {main}
  thrown in /app/vendor/drush/drush/drush.php on line 58

Fatal error: Uncaught Exception: Could not locate autoload.php. cwd is /app; __DIR__ is /app/vendor/drush/drush in /app/vendor/drush/drush/drush.php:58
Stack trace:
#0 /app/vendor/drush/drush/drush(4): require()
#1 /app/bin/drush(120): include('/app/vendor/dru...')
#2 {main}
  thrown in /app/vendor/drush/drush/drush.php on line 58
```
  
ok so I can see drush is installed as part of the profile. For some reason .bin directory is not in vendor but in /app/ and I get the following message when running when attempting to run  `lando drush si localgov -y`

```
PHP Fatal error:  Uncaught Exception: Could not locate autoload.php. cwd is /app; __DIR__ is /app/vendor/drush/drush in /app/vendor/drush/drush/drush.php:58
Stack trace:
#0 /app/vendor/drush/drush/drush(4): require()
#1 /app/bin/drush(120): include('/app/vendor/dru...')
#2 {main}
  thrown in /app/vendor/drush/drush/drush.php on line 58

Fatal error: Uncaught Exception: Could not locate autoload.php. cwd is /app; __DIR__ is /app/vendor/drush/drush in /app/vendor/drush/drush/drush.php:58
Stack trace:
#0 /app/vendor/drush/drush/drush(4): require()
#1 /app/bin/drush(120): include('/app/vendor/dru...')
#2 {main}
  thrown in /app/vendor/drush/drush/drush.php on line 58
```

**Comment by 2dareis2do** [comment]
Ok decided to restart and rebuild lando. Now `lando composer install` is working for me as is `lando drush si localgov -y` 

I can also use `lando phpunit` which is what I was mainly interested in.

Thanks

**Comment by 2dareis2do** [comment]
Just found this as well https://agile.coop/blog/drupal-phpunit-tests-lando/

**Comment by keelanfh** [comment]
Closing as related to Drupal 10 upgrade, and covered in other places.
