### ISSUE TITLE
Rationalise menu link groups

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov#546]
Guide pages and Guide overviews appear in a little sub-menu.

Step-by-step pages and Step-by-step overview don't have their own sub-menu.

This inconsistency could be confusing.

![image](https://github.com/localgovdrupal/localgov/assets/19519457/bed37359-106e-44d9-b1ab-811d0c447d8b)

**Comment by willguv** [comment]
It's missing some menu link groups

/admin/structure/menu/localgov_menu_link_group



![Image](https://github.com/localgovdrupal/localgov/assets/708140/713e3f7a-9ed9-4758-bce5-657a6eb8240e)


Very quick to create

@stephen-cox can you make something that applies to all new installs

**Comment by andybroomfield** [comment]
I think these should have config in the corresponding modules, some modules should already have them so the rest need to be added.

**Comment by keelanfh** [comment]
I'm personally not a fan of the heavily nested structure (it requires a lot of hovering in the right places), but I'd still vote for consistency.

**Comment by stephen-cox** [comment]
This is something I've been meaning to look at for a while. It's easy to do so assigning to me to look at when I have a chance.
