### ISSUE TITLE
Encouraging regular checks by subject matter experts

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#548]
[Content group thread](https://localgovdrupal.slack.com/archives/C020SJRQX2M/p1684492136566859) by David

> how does everyone make sure pages are kept up to date and regularly checked by the page owner/subject matter expert? We have an automated email that sends out a message to the page owner every six months. But they are often ignored

Comments from the thread

**Comment by andybroomfield** [comment]
This is done with:

- https://github.com/localgovdrupal/localgov_workflows/pull/104
- https://github.com/localgovdrupal/localgov_workflows/pull/74
