### ISSUE TITLE
Intermittent errors when creating redirects

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov#551]
I'm intermittently getting this kind of error when creating redirects:

![image](https://github.com/localgovdrupal/localgov/assets/19519457/ac5883d9-ac7f-44a1-8678-604996c187c0)

I can't see any errors in the Network tab in Dev Tools, so it looks like this is a problem with some client-side validating.

Refreshing the page a couple of times often helps, but it's quite a nuisance when you're doing a lot of these.

**Comment by keelanfh** [comment]
This seems to come up more often when clicking through to create redirects from the sidebar when creating content. Creating them from Content > redirects seems more reliable.

**Comment by andybroomfield** [comment]
[Drupal.org issue](https://www.drupal.org/project/redirect/issues/3057250) has a patch which might be worth trying to see if it resolves this.
