### ISSUE TITLE
Update Simple XML Sitemap to version 4 on 2.x branch 

### ISSUE THREAD

**Issue by MattOz-CDS** [localgovdrupal/localgov#558]
Maybe we should consider updating the Simple XML Sitemap to the version 4x branch as the version 3x branch is no longer supported.

**Comment by andybroomfield** [comment]
> Notice that 3.x has been upgraded to Simple site map 4. We could do with the same in 2.x as 4.1.6 is listed as the only release.
> 
> > [4.1.6](https://www.drupal.org/project/simple_sitemap/releases/4.1.6) Stable release covered by the Drupal Security Team released 9 June 2023
> > Works with Drupal: ^9.3 || ^10
