### ISSUE TITLE
Split Preview Link from workflow

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#559]
Council content teams need to be able to send a preview link to a service colleague who's not signed in - I've seen this in all of the councils I've worked in

This functionality is often missed as Workflow is not installed

Can we please estimate offering Preview Link (and Responsive Preview if needed too) as a standalone module to be downloaded

Also I think we need this included in the install profile, defaulting to switched on

**Comment by andybroomfield** [comment]
Also needs to be upgraded to 2.x version as this is both Drupal 9 and Druapl 10 compatible.

**Comment by stephen-cox** [comment]
2 PRs for this #563 and https://github.com/localgovdrupal/localgov_workflows/pull/57

I have kept the Preview Link module version as 1 for now as 2 is still alpha, but will update the D10 3.x branch to install version 2 once this is merged.

**Comment by stephen-cox** [comment]
@willguv Preview Link is now installed and enabled with [release 2.3.17](https://github.com/localgovdrupal/localgov/releases/tag/2.3.17)
