### ISSUE TITLE
Should the readme instructions still have --stability dev in them?

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov#572]
Noting that https://github.com/localgovdrupal/localgov/blame/b6805f518004f1a0e4ea1395dac64557c9bcda2c/README.md#L95 has:

`lando composer create-project localgovdrupal/localgov-project MY_PROJECT --stability dev --no-cache  --no-install`

I think the result of this is that it attempts to install a D10 site. This was flagged over on drupal.org: https://www.drupal.org/project/localgov/issues/3307516. Should we change this?

And also change this on drupal.org? https://www.drupal.org/project/localgov#:~:text=to%20be%20called.-,composer%20create%2Dproject%20%2D%2Dstability%20dev%20localgovdrupal/localgov%2Dproject%20MY_PROJECT,-Change%20directory%20into

**Comment by finnlewis** [comment]
Good call @keelanfh , I will test and update.

**Comment by finnlewis** [comment]
I think this should help @keelanfh https://github.com/localgovdrupal/localgov/pull/573

**Comment by finnlewis** [comment]
I've updated the readme and drupal.org page. https://www.drupal.org/project/localgov

Thanks @keelanfh !!!
