### ISSUE TITLE
LocalGov Theme: confirm any architectural decisions on base-theme and default layout

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#58]
It would be good to confirm: 
 - what the overarching theme architecture is
 - base theme decisions
 - bootstrap usage - usage of bootstrap classes in modules or just in theme? 
 - sass usage 
 - other policies on LocalGov base theme 
 - follow gov.uk design system / guidance

Probably lives in README.md

**Comment by finnlewis** [comment]
Note: we should have a meeting with @cjstevens78 and others and assign resposibility for writing this up.

**Comment by finnlewis** [comment]
Also see https://github.com/localgovdrupal/localgov_theme/issues/18

**Comment by cjstevens78** [comment]
Croydon Design System - Why we chose bootstrap https://new.croydon.gov.uk/design-system/front-end-framework/bootstrap-css-framework
