### ISSUE TITLE
Move devel to `require-dev`?

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov#585]
[following-up https://www.drupal.org/project/localgov/issues/3372234]

If we still want it in this particular composer.json at all. 
https://github.com/localgovdrupal/localgov/blob/6fc64d8f6c931615499359f39aa357580bf40eae/composer.json#L16

This was the reasoning before I think https://github.com/localgovdrupal/localgov/issues/25 But we've moved from there.

**Comment by ekes** [comment]
@stephen-cox maybe?

**Comment by andybroomfield** [comment]
Yes, I belive this should now be in require-dev.
Theres some context in #25.

**Comment by stephen-cox** [comment]
Yep - Devel should certainly be in require-dev. I had been meaning to do this.

There's a patch on the issue queue so will create a PR for this.

**Comment by stephen-cox** [comment]
PR for this #587 

It looks like I removed Devel entirely from the 3.x branch. Is it worth adding back as a dev dependency for consistency?
