### ISSUE TITLE
Support Drupal 9

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#59]
[Drupal 9 is released June 3rd (Today!)
](https://www.drupal.org/about/9)

We should support the shiny new version of Drupal from the go!

**Comment by finnlewis** [comment]
Bump! 

We mentioned this the other day. It would be great to start a branch and get a first pass of the whole distro working in Drupal 9.

**Comment by finnlewis** [comment]
Here's a branch: https://github.com/localgovdrupal/localgov/tree/feature/59-drupal-9

Let's see what issues we get!

**Comment by andybroomfield** [comment]
Getting Drupal 9 support will also be a BHCC requirement soonish as we will need to use Acquia BLT, and you can only add that to distributions instead of the project using version 12 which is Drupal 9 only. https://docs.acquia.com/blt/#releases-and-versioning

**Comment by andybroomfield** [comment]
Tracking ticket for Drupal 9 is now #181
