### ISSUE TITLE
Add GPL licence

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#6]

**Comment by stephen-cox** [comment]
All LocalGovDrupal 3 repos have been initialised with the GPLv3 license as a LICENSE file in the root. This was generated directly from GitHub's template.

- https://github.com/localgovdrupal/localgov/blob/master/LICENSE
- https://github.com/localgovdrupal/localgov_core/blob/master/LICENSE
- https://github.com/localgovdrupal/localgov_project/blob/master/LICENSE

Is the GPL v3 okay or do we want to use a different version?

**Comment by andybroomfield** [comment]
Drupal is GPLv2 or later. 
https://www.drupal.org/about/licensing
For uptake it would it not be better to stay with the same license?

**Comment by finnlewis** [comment]
Yeah, GPLv2 probably makes sense.

**Comment by finnlewis** [comment]
Changed these to GPLv2 for now. 
This looks to follow suit with others: 
Thunder, https://github.com/BurdaMagazinOrg/thunder-distribution/edit/8.x-2.x/LICENSE.txt
Open Social https://github.com/goalgorilla/open_social/blob/8.x-9.x/LICENSE.txt
