### ISSUE TITLE
Change name of "Scheduled transitions" to "Scheduling"

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#602]
(Continuing our work to make LGD admin easier to read for content designers)

How easy is it to change all mentions of "Scheduled publishing" to "Scheduling"

Is it one value to replace somewhere or more complex than that?

Does this create a problem if the module is updated by others?

**Comment by alexburrows** [comment]
`hook_menu_local_tasks_alter() ` will solve it. 

Its declared in `web/modules/contrib/scheduled_transitions/src/Entity/ScheduledTransition.php` So its in a contrib module but if we want to customise it then its simple enough to do.

**Comment by msayoung** [comment]
Just having a quick look at this @willguv 


This will need to be changed:

- in the Admin > Content tabs

![Image](https://github.com/localgovdrupal/localgov/assets/3852805/f995a69b-506b-4190-a123-a3d7043544d3)

- on the node local tasks

![Image](https://github.com/localgovdrupal/localgov/assets/3852805/5d145e12-507b-4920-8120-e30e3d98fe69)

Do you want to update the button text too? 



![Image](https://github.com/localgovdrupal/localgov/assets/3852805/ce717b26-bb38-4df4-bf04-43273e62d0ab)

What should the wording be here?

Also:
- The Scheduled Transitions view title.
- in the Admin > Content menu item

There may be others.

**Comment by willguv** [comment]
@msayoung 

"Scheduled transitions" to "Scheduling"

"Add Scheduled transition" to "Add schedule"

**Comment by willguv** [comment]
Hi @stephen-cox @msayoung could you let me know when this is planned to be done? Cheers

**Comment by stephen-cox** [comment]
Hi @willguv - just finishing off https://github.com/localgovdrupal/localgov_workflows/issues/12 which will be ready for review later this week. Will prioritise this once that's done.

**Comment by willguv** [comment]
Could we knock this off quickly as it's been around for a while @stephen-cox

**Comment by stephen-cox** [comment]
PR for this here https://github.com/localgovdrupal/localgov_workflows/pull/88

I will deploy to the product site for testing.

**Comment by willguv** [comment]
Thanks @stephen-cox
