### ISSUE TITLE
Generate default content

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov#61]
For testing and theming it would be good to have some default content. If this was packaged into it's own module it could be enabled when showing off the distribution.

One thought is do we want default content to go with each site component – e.g. services would have its own default content module, as would directories – or one default content module that contains everything for an all singing and dancing demo site?

**Comment by andybroomfield** [comment]
Have installed this and it works great.
It has to be enabled post install, would it be preferable to enable it in default install or if possible include it as a post install option (maybe a message after install to say to see demo content, enable the localgov_demo module).

**Comment by ekes** [comment]
> or if possible include it as a post install option

I think this was the idea. To have more options on which features you wanted enabled in the profile.
