### ISSUE TITLE
Can councils upgrade to Drupal 10 themselves?

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#615]
Jamie asked if councils can handle the upgrade themselves, or would they need to re-engage with their agency

Is there a way of assessing how much work there is to be done?

@andybroomfield suggested using https://www.drupal.org/project/upgrade_status to scan all modules, check compatibility and create a list of work

Then use https://www.drupal.org/project/rector to upgrade code as needed

We could do and show and tell, explaining how upgrade status works

Is there anything else we can add to help councils make this decision @finnlewis ?

**Comment by stephen-cox** [comment]
Along with assessing what work is needed to prepare the site, there's a technical aspect to performing upgrade. Whoever performs it will need to be happy working with Composer on a commandline, so at a minimum any council upgrading the site themselves needs a technical team/person happy running and debugging the necessary Composer and Drush commands.

A council with a technical team should be able to install the Upgrade Status module and use it to analyse the site. This should given them enough information to estimate whether they have the skills and time to do the upgrade in house or whether extra support is needed.

**Comment by andybroomfield** [comment]
If we have documentation for this, we can close this down?
I believe most councils will be working with their dev team / suppliers to perform the update.

**Comment by willguv** [comment]
Good call Andy, thanks. The backlog is due a clear out, I’ll close this one
