### ISSUE TITLE
Tests that use the localgov profile fail if they test the home page

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#622]
Now that #612 and #613 are merged, the default homepage is the user login which should user Gin login.
This means that tests that include
````php
  /**
   * {@inheritdoc}
   */
  protected $profile = 'localgov';
````
and then don't create any content and try to load that page content will now fail.

This causes [a problem in the Alert banner](https://github.com/localgovdrupal/localgov_alert_banner/issues/282) because it was trying to test the alert banner block which wasn't there.

The solution in that case is just not test against the profile since that isn't nesscary here. Modules that do need the profile will now need to create some front page example content first.

We could include a trait that does this.

**Comment by stephen-cox** [comment]
Most tests should use the 'testing' profile. If they are testing integration with the profile then they can use the 'localgov' profile, but then you should be testing specific functionality.

I'd also suggest that there's no guarantee the front page is set so you should always create a node or other entity and test against that.
