### ISSUE TITLE
Enable redirect by default

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#624]
Seems odd it's [missing from this list](https://github.com/localgovdrupal/localgov/blob/3bf25430295beca5b465f775051d9339a84c14e1/localgov.info.yml#L33) ~~though is included in composer.json~~ __is not actully included but comes from localgov_core__  so is there and quite a common feature.
Add `redirect:redirect` to the contrib section of install for it to be enabled by default.

**Comment by markconroy** [comment]
I'm very surprised this is not enabled by default as well. Especially given the amount of times people on Slack are asking "how do you create short URLs?"

**Comment by finnlewis** [comment]
Sounds good to me !

**Comment by willguv** [comment]
@finnlewis @markconroy is this still an issue? Could be a quick win

**Comment by markconroy** [comment]
PR #716 ready for this

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
