### ISSUE TITLE
Drupal 10 / 3.x beta release

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#627]
Issue to track testing of alpha and push towards a beta.

Currently we have alpha releases 

https://github.com/localgovdrupal/localgov_project/releases/tag/3.0.0-alpha1

https://github.com/localgovdrupal/localgov/releases/tag/3.0.0-alpha4

We need to have some evidence of people testing the alpha in the wild.

If you are a council or supplier who can test an existing site, please let us know and also let us know if we can help.

**Comment by finnlewis** [comment]
We have confirmation that @andybroomfield is testing the upgrade of BHCC to localgov 3 alpha! :)

**Comment by finnlewis** [comment]
@Adnan-cds when do you think you might be able to test an upgrade?

**Comment by Adnan-cds** [comment]
I upgraded my local site to localgov:3.x yesterday.  So should be able to provide a quick report on Monday hopefully.  We have spotted various issues around contrib modules (e.g. openid_connect for SSO) which I am trying resolve now.  But those are unrelated to localgov.

**Comment by finnlewis** [comment]
Dicsussing in tech drop-in. 

We've got the localgov_geo issues in flight, which we want to get fixed before a beta. 

- [x] https://github.com/localgovdrupal/localgov_geo/pull/90

We've also got lots of PHP8.2 issues that we also want to fix before a beta release. 

- [x] https://github.com/localgovdrupal/localgov_project/issues/133

**Comment by stephen-cox** [comment]
If we're planning to fully support PHP 8.2 (which we should for Drupal 10 as this is supported by core https://www.drupal.org/docs/getting-started/system-requirements/php-requirements), then we should also be updating the GitHub workflows to test again PHP 8.2

**Comment by millnut** [comment]
Agreed @stephen-cox I have PRs for localgov_project and localgov_microsites_project which add PHP 8.2 to the workflows. I'll start going through the other modules this weekend or next week and create PRs for PHP 8.2 in the workflow.

I guess one question is should we add PHP 8.3 simultaneously if we can and ignore any failures until the beta of Drupal 10.2 is released? Just so it's already in place and ready for when we want to support it and will give us some visibility of PHP 8.3 issues if any? 

PHP 8.3 is currently in RC3 at the moment and there is a [docker image ](https://hub.docker.com/layers/library/php/8.3-rc-apache/images/sha256-bb99ae37a13f802fc2c8a8c97a0ba24b8be25223fe2b309195ffc5519262838e?context=explore) that we can use in the drupal container image for now.

**Comment by Boosmith** [comment]
I've been testing the beta. There are issues but it's difficult to work out which are local gov drupal and which are contrib module related eg. incompatible modules. 

I hope to spend some more time next week testing it out, as the deadline is getting closer. Eeek!

**Comment by Boosmith** [comment]
I've successfully got the composer dependencies to work on our site with the beta release so that is looking good. We have other issues but they are independent of localgov packages.
