### ISSUE TITLE
Path maintance -- Pathauto -- Path Redirect 

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov#63]
Reminded by localgovdrupal/localgov_services#28

Assuming:-
 * All paths have readable friendly paths;
 * Paths should not change (much);
 * Old paths should be maintained.

Suggesting that:-
 * Pathauto should only create and not update paths;
 * If paths are changed there should be a redirects created to maintain the old one;
 * If paths are dependent on a parent entities path (lots of pages under landing pages are) there should be a hook/event looking for update of the parent to update the children (and create redirects).

**Comment by ekes** [comment]
@andybroomfield You probably have a good idea of this? I remember you mentioning people to change the paths manually to correct/change the breadcrumb/hierarchy.

Do the landing page path aliases _never_ change?
What cases are there for things moving around, and or getting renamed?

**Comment by andybroomfield** [comment]
Not sure there is any further updates to this. 
@ekes is there anything to update or can I close this.
To late answer your question, I don't think we do manually update paths at present, though the possiblity of doing so is always going to be a question. Our breadcrumb works on the path though my understanding is localgov_services_navigation handles keeping everything in the hirechy.

**Comment by ekes** [comment]
I think we create an issue when someone pulls up something specific.

I will note that I know that the paths are being modified by some sites manually specifically for breaking the services hierarchy to make it deeper :-( which as I understood the architecture was specifically to avoid doing this; but then maintaining this seems very much dependent on the site doing it I think.

**Comment by amoebanath** [comment]
Heya. We're noticing that if a landing page (or anything above the bottom of the hierarchy) is renamed, its children's aliases aren't updated. I feel like this ticket is looking for our use case?? :) 

Is this a discussion you guys are up for resuming? We're happy to help out making this happen.

**Comment by andybroomfield** [comment]
@amoebanath Thanks for comment. 
Related to this, https://github.com/localgovdrupal/localgov_services/issues/141 there is also an issue when links entered need redirected they can be broken. I think we need a tool or an automated process that can go through the entire landing -> sub landing -> page and correct any alias and fix broken links.

I think its worth reopening this conversation as [a new issue on the localgov_services repo](https://github.com/localgovdrupal/localgov_services/issues/new) and we can take it from there.
