### ISSUE TITLE
Install 'Media Entity Usage' or 'Entity Usage'

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#647]
In /admin/content/files the "used in" column shows number of uses of a specific asset

![Image](https://github.com/localgovdrupal/localgov/assets/708140/ab21e0b0-be16-435d-a83d-1ddbc1bbd3f3)

It appears to be a link, but clicking on it does nothing

Would be really useful to click and see urls where an asset is used

**Comment by willguv** [comment]
Stephen: It's a UI issue

- Click on the "2 places" link above and be taken to a page with links to the places
- Need to take into account images used in blocks

Jamie says there's a way to show "usage"

**Comment by stephen-cox** [comment]
For media, perhaps it's this module: https://www.drupal.org/project/media_entity_usage

**Comment by Dixonj1** [comment]
@stephen-cox yes, Webcurl have confirmed that we are using that module. It works for all types of media.

![Entity usage module on Wirral website](https://github.com/localgovdrupal/localgov/assets/109518515/c578c264-510d-461b-9c50-4f08728a672d)

**Comment by willguv** [comment]
@dedavidson suggests https://www.drupal.org/project/entity_usage

**Comment by andybroomfield** [comment]
Entity usage should already be installed
```
$ composer why drupal/entity_usage
localgovdrupal/localgov_paragraphs 2.4.3 requires drupal/entity_usage (^2.0@beta)
```

**Comment by dedavidson** [comment]
It just needs configuration for it to be shown by default for Media.

**Comment by willguv** [comment]
Hide the 'files' tab to non admins please @markconroy

**Comment by willguv** [comment]
Hi @stephen-cox @markconroy when will I see this in action please? Does the Demo site rebuild every night with the latest stuff? Thanks

**Comment by willguv** [comment]
@markconroy @stephen-cox could you check Editors, Authors and Contributors can see the Usage tab please? I just logged in as Editor on the Demo site and couldn't see it

Thanks

**Comment by markconroy** [comment]
@willguv I don't have access to the repo/build tools for the demo site, so can't really test it.

If the latest version of the profile is installed the tab should be there, unless those roles don't have permission to view it.

@stephen-cox is probably best to test this is working on the demo site.

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
