### ISSUE TITLE
LocalGov Drupal needs a [not a logo] but better colours

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#65]
For marketing, having in the default theme, favicon and mobile icon, stickers, [mascots](https://twitter.com/mondomascots).

**Comment by andybroomfield** [comment]
UAT one now has one!
<img width="121" alt="Screenshot 2020-06-10 at 11 58 07 am" src="https://user-images.githubusercontent.com/1467480/84260270-ac326900-ab11-11ea-8276-52817086d9e4.png">

**Comment by finnlewis** [comment]
@willguv wants to get this moving in Croydon's next sprint.

**Comment by finnlewis** [comment]
@willguv any news from Dave?

**Comment by willguv** [comment]
Yes, we're about to go into a 1 week firebreak and Dave has 2 days to work on this

**Comment by finnlewis** [comment]
Dave has made a start. Will and Dave will get back to the group soon.

**Comment by willguv** [comment]
@finnlewis Dave has done a lot of thinking about this - see attached

It's quite a departure from Sally's work, so I'm keen that we discuss as a group. I personally like it, but think it's a bit masculine and that might not help us as a project

The last couple of pages set out theming ideas, so we could potentially agree those first to unlock Chris' front end work. Then we can pick up the rest later

Dave can join at the end of tomorrow's stand up, to discuss for 30 mins. Shall we do that to start with?

[0101_CDS_20_LocalGov_Brand_Proposition-2.pdf](https://github.com/localgovdrupal/localgov/files/4919329/0101_CDS_20_LocalGov_Brand_Proposition-2.pdf)

**Comment by finnlewis** [comment]
Discuss in sprint planning: 

@cjstevens78 is going to work on this. We're not taking too much of the design direction from the document. 

[ ]  - Not changing logo.
[ ]  - Implement the colours specificied.
