### ISSUE TITLE
Drupal 9 support and testing

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov#666]
There are still quite a few repos running tests against Drupal 9. This is out of support, but I'm aware that not all councils have managed to upgrade to Drupal 10 yet.

How long are we going to support Drupal 9 for? It would be good to rationalise all the Github testing configuration as the config is slowly diverging across the different repos and we might as well wait until we no longer need to test against Drupal 9.

**Comment by andybroomfield** [comment]
I think we stopped on the profile?
In any case we might be requiring minimum core of 10.2 in next minor release, and I think it's now time to stop.

**Comment by stephen-cox** [comment]
We've agreed to stop supporting Drupal 9 and with the roll out of https://github.com/localgovdrupal/localgov_shared_workflows/ testing against D9 is being removed
