### ISSUE TITLE
The reference unpublish content patch is failing on Drupal 10.1

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#670]
This is the patch added in #336 and updated in #667 to allow editors to reference unpublished content.

On latest update I'm now seeing 
> Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2024-01-07/2845144-78.patch

Updating to the latest patch appears to resolve, though I'm going to have to test it's doing the right think as the diff is a lot shorter.

https://www.drupal.org/project/drupal/issues/2845144#comment-15389555

**Comment by andybroomfield** [comment]
This might be a 10.1 issue, as the patch applies on my 10.2 branch, updating title to reflect this.

**Comment by joachim-n** [comment]
It fails on 10.2.3 as well, which is what Composer is installing for me for localgov.
