### ISSUE TITLE
Write up architectural decisions to date

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#73]

**Comment by ekes** [comment]
Large part of this related to entity types and fields is now written in YAML in the croydon_migration repo.

Still to do:
 * write a description about services parentage, and adding guides/step by step to services.
 * document the topics discussion when finalized.

**Comment by ekes** [comment]
> Still to do:
>   write a description about services parentage, and adding guides/step by step to services.
>    document the topics discussion when finalized.

Now exists here:
https://github.com/localgovdrupal/localgov/wiki/Structure

**Comment by stephen-cox** [comment]
Closing at sprint 3
