### ISSUE TITLE
Test failure in localgov_content_lock module

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov#731]
```
1) Drupal\Tests\localgov_content_lock\Functional\ContentLockTest::testContentLockConfiguration
Behat\Mink\Exception\ElementNotFoundException: Element matching xpath "./ancestor::form" not found.

/var/www/html/vendor/behat/mink/src/WebAssert.php:465
/var/www/html/web/core/tests/Drupal/Tests/UiHelperTrait.php:79
/var/www/html/web/profiles/contrib/localgov/modules/localgov_content_lock/tests/src/Functional/ContentLockTest.php:46
/var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php:729
```

**Comment by millnut** [comment]
Looked into this a bit in https://github.com/localgovdrupal/localgov/pull/730#issuecomment-2176831091 looks related to the gin theme latest update, I have also submitted a ticket on the gin theme issue queue

**Comment by stephen-cox** [comment]
@millnut Good catch picking this up as a problem with the Gin theme. 

It looks like they won't fix the issus in Gin (https://www.drupal.org/project/gin/issues/3455524) so I think the simplest solution for now is to switch to the Claro theme for this test.

PR for this here https://github.com/localgovdrupal/localgov/pull/732
