### ISSUE TITLE
Standardise bug report template.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#74]
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by andybroomfield** [comment]
Is there any updates on this? Would be useful now to get the standard templates written up.
This is how Backdrop have it set up.
https://github.com/backdrop/backdrop-issues/tree/master/.github/ISSUE_TEMPLATE

**Comment by andybroomfield** [comment]
Do we know what we would want in a template as it would be good to get this in place.

**Comment by finnlewis** [comment]
@j4-m you were asking about this today. 

So @andybroomfield merged in this: https://github.com/localgovdrupal/.github/pull/8

What else do we need to do to enable templates for issues / bug reports / feature requests etc?

**Comment by andybroomfield** [comment]
Does each repo need to update to get the template?
There is a setting in each repo under issues that says set up templates, so maybe it has to be done there?

**Comment by j4-m** [comment]
@andybroomfield unfortunately I don't have the access to try that out on the LGD repos... are you able to try it out?

**Comment by finnlewis** [comment]
@andybroomfield just tried adding default templates to the main localgov repo: 

https://github.com/localgovdrupal/localgov/pull/433

It does look like we need them on each repo, so let's get them working here then copy elsewhere as needed.

**Comment by finnlewis** [comment]
Added default templates, so we can see how they go and iterate on the specific content of each: https://github.com/localgovdrupal/localgov/issues/new/choose
