### ISSUE TITLE
module contrib offer/proposal: Job Vacancies

### ISSUE THREAD

**Issue by ctorgalson** [localgovdrupal/localgov#761]
Annertech has incoroporated a "Job Vacancies" content type + views + search etc into a couple of LGD sites.

I've cleaned up the initial config--the module at this stage is _only_ config--to make it fit for general use. We wanted to find out if there's interest in the first place, but also if the community would like more/different features than the module currently includes.

We've built:

- a Job Vacancy content type with `body`, closing_date`, and `application_forms` fields
- a search_api (db) server and index to index the rendered item, body, and title fields
- a Job Vacancies view with a separate exposed filters block
- various additional config such as pathauto alias patterns for Job Vacancy etc

[localgov_job_vacancies-0.3.1.zip](https://github.com/user-attachments/files/16689124/localgov_job_vacancies-0.3.1.zip)

---

My time on this provided by [Annertech](https://www.annertech.com)

**Comment by andybroomfield** [comment]
Looks insteresting, I just did a quick test and it installs and works to create jobs pages and a view with search.
Many (most?) councils use Tribepad or simmilar to handle recuriting, and would be looking for integration with that, pulling the job feeds from there. BHCC has something for it's jobs pages but it's very old and is a controller that calls the API, not content.

**Comment by andybroomfield** [comment]
@ctorgalson I suggest making a repo for it under the localgovdrupal name space for issues to be looked at. I think we can designate modules as Contrib?

**Comment by andybroomfield** [comment]
What it looks like
<img width="1442" alt="Screenshot 2024-08-21 at 12 23 02 PM" src="https://github.com/user-attachments/assets/a38331fa-5eda-4ad7-b14a-d946cf980d67">

**Comment by ctorgalson** [comment]
> I suggest making a repo for it under the localgovdrupal name space for issues to be looked at.

Sounds good to me. 

> I think we can designate modules as Contrib?

I'm not sure what you mean? We're happy to contribute it (and implement features/correct bugs/omissions etc).

**Comment by ctorgalson** [comment]
I realized that I have _not_ correctly namespaced the fields per https://github.com/localgovdrupal/localgov/wiki/Naming-Conventions (h/t @finnlewis)

If someone can create a repo for this, I can make those changes and push it up.

**Comment by finnlewis** [comment]
Sure, what shall we call it? 

localgov_jobs
localgov_vacancies

or something else?

**Comment by finnlewis** [comment]
Ah - I see now  - localgov_job_vacancies !

**Comment by ctorgalson** [comment]
Unless you want to go short with `localgov_jobs` or something since I'll be mucking around in config anyhow :-s

**Comment by finnlewis** [comment]
https://github.com/localgovdrupal/localgov_job_vacancies/

**Comment by ctorgalson** [comment]
Further conversations to https://github.com/localgovdrupal/localgov_job_vacancies/.

**Comment by ctorgalson** [comment]
Closing
