### ISSUE TITLE
Inclusive preview for guides and step-by-step pages not working

### ISSUE THREAD

**Issue by DavidBAsch** [localgovdrupal/localgov#774]
Although the option for including child pages of guides and step-by-steps is available in the preview panel, only the top level of the section is included when the page is viewed by an anonymous user.

![image](https://github.com/user-attachments/assets/878e34c5-8639-40d1-bdb8-986713d1a6a5)
![image](https://github.com/user-attachments/assets/a949ed53-3fa9-4c69-847a-b42c39046266)
![image](https://github.com/user-attachments/assets/c87105fa-8b34-490a-a3e4-7712541734b9)

**Comment by stephen-cox** [comment]
Thanks for the bug report @DavidBAsch. This looks to be the same problems being discussed on #771

**Comment by andybroomfield** [comment]
This is fixed now
<img width="1468" alt="Screenshot 2024-12-24 at 10 33 18 am" src="https://github.com/user-attachments/assets/3b51ebb4-6bcb-4bba-9fa4-908ab687740c" />
