### ISSUE TITLE
Remove content-moderation-workspaces-query patch 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#779]
```
https://www.drupal.org/files/issues/2024-08-11/3179199-3132022-content-moderation-workspaces-query.patch (Content moderation and Workspaces https://www.drupal.org/project/drupal/issues/3179199#comment-15711680)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2024-08-11/3179199-3132022-content-moderation-workspaces-query.patch
```

Looks like the patch in https://github.com/localgovdrupal/localgov/blob/3.x/composer.json#L63 has been committed to Drupal core.

**Comment by millnut** [comment]
Yep looks like this has been commited to core for 11 and 10.3 only, so for older than 10.3 I guess we'll need to do the same as last time https://github.com/localgovdrupal/localgov_project/blob/3.x/composer.json#L74 and then remove from `localgov` when 10.2 is end of life in Dec 2024 iirc

**Comment by ekes** [comment]
I think just removing it should be fine. Put it in the release notes just in case anyone is using workspaces in 10.2, but I'd be very surprised if there is anyone.

**Comment by tanc** [comment]
This is currently blocking Drupal from being upgraded as far as I can tell (the patch doesn't apply)

**Comment by andybroomfield** [comment]
See [patch policy](https://docs.localgovdrupal.org/governance/patch-maintenance-policy.html#_4-0-patching-major-versions-of-drupal-core) which I think will apply here. It looks like this needs to go in patches-ignore in the project composer.json.

**Comment by andybroomfield** [comment]
and also this [proposed wip RFC](https://github.com/localgovdrupal/localgov/issues/662)

**Comment by millnut** [comment]
PR here https://github.com/localgovdrupal/localgov_project/pull/177 following the patches-ignore approach

**Comment by millnut** [comment]
Closing as this has been merged into 3.x
