### ISSUE TITLE
Confirming the name of the project, and naming conventions.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#78]
As with all projects, consistency is important in naming both for the outward facing project name and internal naming conventions.

We had a discussion early in this project about the name, which it appears that @stephen-cox and I took differently.

I understood the name would be 

**LocalGov Drupal**

(with a space between LocalGov and Drupal)

@stephen-cox understood the name would be:

**LocalGovDrupal**

(all one word, no space)

I would like to gather opinion to see if others thought is was one or the other or have a preference for one or the other.

Could you share your preference and thoughts? 
@willguv @bhccwebmaster @andybroomfield @andybroomfield @bhccwebmaster @danchamp @ekes 

The other more technical side to this is the conventions in machine names, which @ekes has started defining here https://github.com/localgovdrupal/localgov/wiki/Naming-conventions - specifically that "content type, views, and module, prefix always descriptive name with `localgov_`"

**Comment by finnlewis** [comment]
Personally I'm still keen on **LocalGov Drupal**, with the space.
This might be just because I misunderstood the earlier conversation and that now I've got used to that, as that was my working assumption. 

But I do also think it scans better, and (again maybe due to my assumptions) it has already been used in that form in reports and presentations : 

https://www.youtube.com/watch?v=GFzqXnpgZgs 

https://docs.google.com/presentation/d/1tTajs8t8QQwqyJ-zP9ZW-hK1aM9CtTMPcihTnaG0vCM/edit

https://croydon.digital/2020/05/30/multi-council-drupal-code-sharing-alpha-sprint-1-notes/

**Comment by willguv** [comment]
I've been using LocalGov Drupal everywhere and prefer it

**Comment by ekes** [comment]
The namespace as just `localgov_` I think we discussed. `lg_` was the other less semantic option so less desirable. It's obviously Drupal by context, and `localgov_` is way long enough. Fits with using a space in LocalGov Drupal maybe.

I've used LocalGovDrupal as the package name for consistency with existing modules. It does allow a space, and is displayed to users, so a space should be easy enough to add. I don't think it's been used anywhere that you can't add a space.

**Comment by andybroomfield** [comment]
Is this considered done?
Name of project = LocalGov Drupal
Organisation = Open Digital Co-operative.
