### ISSUE TITLE
When do we need to add hook_update_N to our modules

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#79]
See localgovdrupal/localgov_alert_banner#16.
If we convert the entity from ECK, normally we would provide an update hook.
As we do a fresh install each time this isn't really needed right now, however it will be in the future once the sitesd start getting installed.
What is the criteria for when we start doing this?

**Comment by Adnan-cds** [comment]
Hi Andy,
Thanks for pointing me to this.  The [UAT site](https://localgovdrupal.agile.coop/) has some content in it, so may not be installed fresh any more.  Or is this content entirely coming out of the [Demo content module](https://github.com/localgovdrupal/localgov_demo)?  Steve may know better.  If this site has manually edited content then we should start adding update hooks now.

FAO @andybroomfield @stephen-cox @danchamp

**Comment by stephen-cox** [comment]
The UAT site has been re-installed periodically with the content being created by the demo content module. To demonstrate recent work we need a site such as UAT that can be wiped regularly.

We will need to start writing update hooks as soon as LocalGov Drupal starts being used as a base for a new site or Croydon or BHCC adopt part or all of the codebase. While this might not be immediately it is likely to be soon, so it makes sense to start thinking about this.

**Comment by Adnan-cds** [comment]
Thanks Stephen :)  I hope Will is aware that manually edited content from the UAT will disappear from time to time.

Based on what Stephen has said, looks like Andy can skip the update hook for now.

@stephen-cox @willguv @andybroomfield

**Comment by andybroomfield** [comment]
Not sure why this issue was closed as we still need an answer to the question.
Now that sites are looking at migrating onto it we should document the process of putting in updates hook, and when a module needs to start doing this.

**Comment by stephen-cox** [comment]
We do need to start providing update hooks for changes to services, guides, step by steps and campaigns. These are now being used by Lambeth Council to build a new website and so breaking config changes will need to be dealt with.

We should discuss the best way to handle and test these. Now councils are actually using the distribution we might also want to look at doing tagged releases as well; rather than just using the master branch for everything.

**Comment by andybroomfield** [comment]
Thanks @stephen-cox So that confirms that now is the time to start adding update hooks. Just need to add this to the developer documention (Wiki or Readme) and if we have a preffered format eg. Start at 8000 and go 8001 or use the Drupal base version eg. 8900, 8901 etc...

**Comment by andybroomfield** [comment]
The answer is always!
