### ISSUE TITLE
Automated testing - explore options 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#8]
Gitlab? 50,000 mins
Github?  2000mins
CirclCI? 
Azure Devops? Don't bother.

Investigate and document options.

**Comment by stephen-cox** [comment]
I have GitHub actions working for the https://github.com/localgovdrupal/drupal-container repo. You can see a successful run here: https://github.com/localgovdrupal/drupal-container/runs/674632523?check_suite_focus=true

This approach - using Docker Compose with a custom Docker image - should work for most CI environments. If we're happy to give GitHub Actions a go, the next step is to decide when tests are run and what to test.
