### ISSUE TITLE
"Development and contribution processes and standards" URL is broken

### ISSUE THREAD

**Issue by waldoj** [localgovdrupal/localgov#83]
[The Contributing section of the README](https://github.com/localgovdrupal/localgov#contributing) says:

> The development and contribution processes and standards proposed in the discovery phase can be found here: https://drive.google.com/open?id=1CJWkNMh6rjF6Ml-WwEwWgt9UPNpTEgODYJN3hCaySJk?

That URL 404s.

[CONTRIBUTING.md](https://github.com/localgovdrupal/localgov/blob/master/CONTRIBUTING.md) seems quite robust, so I'm not sure that I'm missing anything important by not being able to read the Google Doc. I thought it would be presumptuous to file a PR eliminating that paragraph and link, but perhaps that's the best solution?

**Comment by stephen-cox** [comment]
Hi @waldoj - we seemed to have missed this issue. Any help improving the docs is appreciated. Feel free to send a PR to remove the paragraph - the Google Doc doesn't contain anything that's not in CONTRIBUTING.
