### ISSUE TITLE
Handling titles across the site

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov#87]
There is a generic [NodeHeaderBlock](https://github.com/localgovdrupal/localgov_core/blob/master/src/Plugin/Block/NodeHeaderBlock.php) in core that displays the title and body summary text for any node on the site. This works okay for nodes in most cases but there are cases where a module wants to control this.

* Guide pages should show the title and summary of the associated overview page.
* Campaign pages have their own banner block that includes an image.

The Croydon and BHCC sites also have a [TermHeaderBlock](https://github.com/bhccwebmaster/bhccdirectories-campaigns/blob/master/bhcc_helper/src/Plugin/Block/TermHeaderBlock.php) that hasn't been ported yet. We also need to think about displaying titles for pages that don't have an associated entity.

I suggest we need a standard header block that will display titles with a node summary or term description for relevant entities. Modules also need to be able to turn this block off if they provide their own header block. This could be implemented as some sort of [event](https://www.drupal.org/docs/creating-custom-modules/subscribe-to-and-dispatch-events) that modules could subscribe to and pass config to the header block. The config could just be whether to display the block, but it could also allow modules to change the title and lede fields of the block. Care would be needed to ensure we don't introduce extra dependencies between modules, but if this all lived in core then it should be fine. Although there maybe better ways to deal with this. 

@Adnan-cds @andybroomfield @ekes @finnlewis do you have any thoughts on this proposal?

**Comment by Adnan-cds** [comment]
> Modules also need to be able to turn this block off if they provide their own header block. This could be implemented as some sort of event that modules could subscribe to and pass config to the header block

Hi Steve,
This should work of course.

An alternative would be to turn the generic NodeHeader block on or off as part of block configuration.  This means there has to be separate NodeHeader block implementations for Guide pages and Campaign pages.  An interface can ensure some uniformity across these blocks.  Downside of this approach is that the block config files will have to explicitly list content types which may complicate site upgrades for localgov profile users.  Upside is that you will not need a debugger to figure out who is providing the node header block content.

FAO @stephen-cox

**Comment by andybroomfield** [comment]
This comes from not using the default title block, so TermHeaderBlock and ViewsHeaderBlock had to be created as there where pages when no title would get displayed.

I think it all comes about due to the special handling of titles, and the original overrides of NodeStorage which are no longer used in Localgov. It would be better to extend the core title block and opt in the extra `lede` for content that requires it which is most node types. So a way of content types opting in if they need to display this.

(The current way in BHCC is to define content types and/or paths where the block is not to be shown, but I guess thats not feasable for a distrobution).

**Comment by stephen-cox** [comment]
Thanks for the input on this.

I think having blocks that are only enabled for certain content types or paths is not ideal when we're not certain which content types will be enabled on a site.

I will have a go at extending the core title block and allow modules to add content and turn it off using a custom event. I'll create a pull request once there's something to test and feed back on.
