### ISSUE TITLE
As a News editor, create and manage news pages

### ISSUE THREAD

**Issue by OliverHannan** [localgovdrupal/localgov#92]
In most councils News is written, uploaded and edited by a separate team. Content designers can be called on to help, so should have all of these permissions.

As a news editor
I want to create and manage news pages
So that I can share what the council is doing with local citizens

### Notes
News comprises parent "news homepage" and child "news articles"

### News homepage
https://lbc-app-w-corpwebsite-dev1.azurewebsites.net/node/add/newsroom_page

https://new.brighton-hove.gov.uk/news

- Featured - not sure what this does
- Select up to 3 news articles (type name to auto select), can remove
- Add a featured event with title, date,time, location, image, summary and URL
- Add Useful links (URLs and link text)
- Hard coded are email newsletter panel, newsroom search, social links, list of latest news article - most recent first

### News article
https://lbc-app-w-corpwebsite-dev1.azurewebsites.net/node/add/news
https://new.brighton-hove.gov.uk/news/2020/events-madeira-drive-0

- Add a title
- Add a summary
- Set a publish date
- Pick one from category list
- Pick a call out [dunno what this is]
- Upload or pick from list a thumbnail
- Add story (ultimately add reusable para eg quote)
- Manually pick 3 related articles

**Comment by willguv** [comment]
@finnlewis @ekes Oliver and I have written a basic spec for news, based on what Brighton has. This is fine for both Croydon and London Councils as a starter. We can obviously add to it at a later date
