### ISSUE TITLE
[1d] ‘Content > Add Content’ menu - make it possible to group menu items

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#95]
We want to collect /node/add menu items into groups, like: 

Add content  
> Directories: 
> > Add Directory channel
> > Add Director page
> > Add Directory VEnue

> Services
> > Add service lanading page
> > Add service sub landing page
> > Add service page

Set up default menu configuration for each menu item from all localgov menus. 

Allow the menu items to be managed by admins.

As a Drupal admin
I want to be able manage the menu items
So that we can change the structure. 

As a content designer
i wnt to see all directores content types under a directories parent menu 
So that I can see a shorted list of conte add.

**Comment by Adnan-cds** [comment]
With significant input from @ekes and @stephen-cox we have agreed to the following implementation approach after trying various alternatives:
- A custom config entity will provide the mapping between Categories and content types.  By "Category", we mean terms like "Directories", "Services", etc.  When a module will define a content type, it will also define these mappings in the form of config entity files.
- A menu link plugin derivative, similar to [admin_toolbar_tools' ExtraLink](https://git.drupalcode.org/project/admin_toolbar/-/blob/8.x-2.x/admin_toolbar_tools/src/Plugin/Derivative/ExtraLinks.php) will generate the menu links for the Categories.
- Based on the custom config entities, we will modify the existing node.add.{bundle} menu links to sit under their parent Categories in Drupal's menu tree.
- There is a need to add new Categories from Drupal's UI.  We will decide how best to deal with it later.

FAO @finnlewis @andybroomfield

**Comment by andybroomfield** [comment]
Basically makes sense. We'd like to incorporate the category menu, we have lots of new content types so need to put them in their own groups and have ways to define them.
Possibly out of scope, but we also make a lot of custom entities now and would be good if this functionality could be ported to them.

**Comment by willguv** [comment]
Don't make it core, keep separate

**Comment by Adnan-cds** [comment]
New module created under new repository: https://github.com/localgovdrupal/localgov_menu_link_group

Initial pull request: https://github.com/localgovdrupal/localgov_menu_link_group/pull/1

This implementation follows the previously agreed approach above with one notable exception.  Instead of assigning categories to entity types (e.g. content types), we now deal with menu links only.  This means our custom config entity points to a few menu links rather than any category.  These menu links are then grouped together under a Group specific parent menu link.  Example:
```
-- Add content
---- Directory <- This menu link is generated from the label of our custom config entity.  This label serves as the group name.
-------- Directory channel  <- This menu link is referenced by the "Directory" group.
-------- Directory entry      <- Same as above.
```

**Comment by Adnan-cds** [comment]
New module has been [accepted](https://github.com/localgovdrupal/localgov_menu_link_group/pull/1).  Thanks @andybroomfield @stephen-cox . Remaining tasks:
- Create package in packagist.org
- Update the [localgov](https://github.com/localgovdrupal/localgov) Drupal profile to actually use the new module.

**Comment by Adnan-cds** [comment]
Closing as this task was complete a while ago.
